import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = <String, Map<String, String>>{
    //ITALIANO
    'it': {
      //LOGIN PAGE & REGISTER PAGE
      'push_init_failed': 'Inizializzazione notifiche non riuscita',
      'error_login': 'Errore durante il login',
      'error_user_not_found': 'Utente non trovato',
      'error_wrong_password': 'Password errata',
      'error_invalid_email': 'Email non valida',
      'error_unexpected_login': 'Errore imprevisto durante il login',
      'error_google_login': 'Errore durante il login con Google',
      'error_account_exists_different_credential': 'Account già esistente con un altro metodo di accesso',
      'error_invalid_google_credential': 'Credenziali di Google errate',
      'error_user_disabled': 'Utente non abilitato',
      'error_google_login_generic': 'Errore durante l’accesso con Google',
      'login_title': 'Bentornato!',
      'login_subtitle': 'Accedi per continuare',
      'email_label': 'Email',
      'validation_insert_email': 'Inserisci la tua email',
      'validation_email_invalid': 'Email non valida',
      'password_label': 'Password',
      'validation_insert_password': 'Inserisci la password',
      'validation_min_6_chars': 'Minimo 6 caratteri',
      'forgot_password': 'Password dimenticata?',
      'password_reset_sent': 'Email di reset della password inviata',
      'error_password_reset': 'Errore durante il reset della password',
      'error_too_many_requests': 'Troppi tentativi. Riprova più tardi',
      'error_unexpected_reset': 'Errore imprevisto durante il reset della password',
      'login_button': 'Accedi',
      'login_with_google_loading': 'Accesso con Google...',
      'login_with_google': 'Registrati con Google',
      'no_account': 'Non hai un account?',
      'go_to_register': 'Registrati',

      'registration_success': 'Registrazione avvenuta con successo.\nTi diamo il benvenuto in Grouply',
      'error_register': 'Errore durante la registrazione',
      'error_email_in_use': 'Questa email è già registrata',
      'error_weak_password': 'La password è troppo debole',
      'error_unexpected_register': 'Errore imprevisto durante la registrazione',
      'error_google_register': 'Errore durante la registrazione con Google',
      'register_title': 'Crea un account',
      'register_subtitle': 'Registrati per iniziare',
      'go_to_login_button': 'Vai alla pagina di login',
      'validation_insert_password_register': 'Inserisci una password',
      'validation_confirm_password': 'Conferma la password',
      'validation_passwords_not_match': 'Le password non coincidono',
      'register_button': 'Registrati',
      'register_with_google_loading': 'Registrazione con Google...',
      'register_with_google': 'Registrati con Google',
      'have_account': 'Hai già un account?',

      //HOME PAGE
      'snack_group_created': 'Gruppo creato! Codice: {code}',
      'error': 'Errore',
      'error_code_not_found': 'Nessun gruppo trovato con questo codice',
      'error_already_member': 'Fai già parte di questo gruppo!',
      'snack_join_success': 'Ti sei unito al gruppo {groupName}!',
      'snack_join_error': 'Errore durante l\'unione: {error}',
      'dialog_join_group_title': 'Unisciti a un Gruppo',
      'label_insert_code': 'Inserisci codice invito (6 caratteri)',
      'button_cancel': 'Annulla',
      'validation_code_length': 'Il codice deve essere lungo 6 caratteri',
      'button_join': 'Unisciti',
      'dialog_create_group_title': 'Crea Nuovo Gruppo',
      'label_team_name': 'Nome del Team (es. Real Madrid)',
      'label_team_sport': 'Sport (es. Calcio)',
      'button_create': 'Crea',
      'home_groups_dialog_title': 'Gruppi',
      'home_groups_create': 'Crea nuovo gruppo',
      'home_groups_join': 'Inserisci codice gruppo',
      'close_button': 'Chiudi',
      'home_tab_events': 'Eventi',
      'home_tab_posts': 'Post',
      'home_tab_polls': 'Sondaggi',
      'home_no_groups': 'Non sei in nessun gruppo. Unisciti a uno per vedere gli eventi!',
      'home_no_events': 'Nessun evento in programma',
      'post_delete_title': 'Elimina post',
      'confirm_post_delete': 'Vuoi davvero eliminare questo post?',
      'post_delete_cancel': 'Annulla',
      'post_delete_delete': 'Elimina',
      'post_deleted_success': 'Post eliminato',
      'home_no_posts': 'Nessun post in bacheca',
      'home_no_polls': 'Nessun sondaggio attivo',
      'poll_vote_saved': 'Voto salvato',
      'poll_delete_title': 'Elimina sondaggio',
      'poll_delete_confirm': 'Vuoi davvero eliminare questo sondaggio del gruppo {groupName}?',
      'button_delete': 'Elimina',
      'poll_deleted_success': 'Sondaggio eliminato',
      'poll_total_votes': '{count} voti',
      'poll_multiple_hint': 'Puoi selezionare più opzioni',
      'label_today': 'Oggi',
      'label_tomorrow': 'Domani',
      'generic_event': 'Evento',
      'tournament_event': 'Torneo',

      //CREATE EVENT PAGE
      'tournament_min_3': 'Un torneo deve avere almeno 3 squadre!',
      'error_missing_fields': 'Compila tutti i campi obbligatori',
      'event_created_success': 'Evento creato con successo!',
      'match_type_home': 'Partita in casa',
      'match_type_away': 'Partita in trasferta',
      'match_type_tournament': 'Torneo',
      'match_type_friendly': 'Amichevole',
      'create_event_title': 'Crea evento',
      'label_match_type': 'Tipo di partita',
      'label_date': 'Data',
      'label_start_time': 'Orario di inizio',
      'label_match_location': 'Luogo della partita',
      'map_select_placeholder': 'Seleziona sulla mappa',
      'label_meeting_point': 'Luogo di ritrovo',
      'label_meeting_time': 'Orario ritrovo',
      'label_home_team': 'Squadra in casa',
      'label_away_team': 'Squadra fuori casa',
      'label_tournament_teams': 'Squadre partecipanti',
      'hint_team_n': 'Squadra {number}',
      'btn_add_team': 'Aggiungi squadra',

      //CREATE PAYMENT REQUEST PAGE
      'toast_login_required': 'Devi effettaure il login per salvare',
      'payment_admin_only_error': "Solo l'amministratore può creare richieste di pagamento",
      'payment_no_recipients_error': 'Seleziona almeno una persona',
      'payment_invalid_amount_error': 'Inserisci un importo valido',
      'payment_missing_fields_error': 'Compila tutti i campi richiesti',
      'payment_request_created_success': 'Richiesta creata con successo!',
      'payment_pick_date': 'Scegli data',
      'payment_create_title': 'Richiesta di pagamento',
      'payment_recipients_label': 'Destinatari',
      'payment_amount_label': 'Importo',
      'payment_amount_hint': 'Es. 10,00',
      'payment_note_label': 'Descrizione',
      'payment_note_hint': 'Es. Quota mensile / Campo / Divise...',
      'payment_due_date_label': 'Scadenza (opzionale)',
      'payment_creating': 'Invio...',
      'payment_send_request': 'Invia richiesta',

      //CREATE POLL PAGE
      'poll_missing_fields_error': 'Compila domanda e opzioni',
      'poll_min_options_error': 'Inserisci almeno 2 opzioni',
      'poll_created_success': 'Sondaggio creato con successo!',
      'create_poll_title': 'Crea un sondaggio',
      'poll_question_label': 'Domanda',
      'poll_question_hint': 'Es. Chi viene all’allenamento?',
      'poll_allow_multiple': 'Consenti selezioni multiple',
      'poll_option_label': 'Opzione {number}',
      'poll_remove_option': 'Rimuovi',
      'poll_add_option': 'Aggiungi opzione',
      'poll_creating': 'Creazione sondaggio...',
      'poll_publish': 'Pubblica sondaggio',

      //CREATE POST PAGE
      'image_size_error': 'Immagine troppo pesante! Riprova con una più piccola o fai uno screenshot',
      'file_size_error': 'File troppo grande per Firestore (Limite 1MB)',
      'post_created_success': 'Post pubblicato con successo!',
      'error_save': 'Errore durante il salvataggio',
      'error_post_size_limit': 'Limite superato! Il post (testo + immagini) pesa più di 1MB',
      'create_post_title': 'Crea un post',
      'label_publish_in': 'Pubblica in:',
      'label_post_title': 'Titolo del post',
      'label_post_description': 'Descrizione',
      'btn_add_media': 'Foto/Video',
      'btn_add_attachment': 'Allegato',
      'btn_publish': 'Pubblica',

      //CREATE RECURRING EVENT PAGE
      'default_event_training': 'Allenamento',
      'recurrence_daily': 'Ogni giorno',
      'recurrence_weekly': 'Ogni settimana',
      'recurrence_monthly': 'Ogni mese',
      'create_recurring_event_title': 'Crea evento ricorrente',
      'label_event_name': 'Nome evento',
      'label_location': 'Luogo',
      'label_recurrence': 'Ripetizione',
      'recurrence_info': 'Verranno generati eventi per i prossimi 3 mesi.',

      //EVENT DETAILS PAGE
      'delete_event_title': 'Elimina evento',
      'delete_event_confirm': 'Sei sicuro di voler eliminare questo evento? L\'azione è irreversibile.',
      'event_not_found': 'Evento non trovato',
      'event_details_title': 'Dettagli Evento',
      'status_title': 'La tua presenza',
      'btn_decline': 'Non ci sarò',
      'btn_accept': 'Ci sarò',
      'status_going': 'Presente',
      'status_not_going': 'Assente',
      'status_pending': 'In attesa',

      //EVENT TYPE SELECTOR PAGE
      'event_select_type_title': 'Seleziona tipo',
      'event_type_single': 'Evento',
      'event_type_single_sub': 'Invita persone a partite, tornei o altri eventi sociali',
      'event_type_recurring': 'Evento ricorrente',
      'event_type_recurring_sub': 'Invita persone ad allenamenti o altri eventi',

      //GROUP CHAT PAGE
      'chat_send_error': 'Errore invio: {error}',
      'chat_empty': 'Nessun messaggio. Scrivi il primo!',
      'chat_hint': 'Scrivi un messaggio...',

      //GROUP DASHBOARD PAGE
      'admin_only_delete': 'Solo l\' amministratore può eliminare contenuti',
      'delete_post_title': 'Elimina post',
      'delete_post_confirm': 'Vuoi eliminare i {count} post selezionati?',
      'elements_deleted': '{count} elementi eliminati',
      'fab_option_event': 'Evento',
      'fab_option_post': 'Post',
      'fab_option_post_sub': 'Condividi informazioni, foto e file',
      'fab_option_poll': 'Sondaggio',
      'fab_option_poll_sub': 'Chiedi ai membri la loro opinione',
      'fab_option_payment': 'Richieste di pagamento',
      'fab_option_payment_sub': 'Raccogli quote dai membri',
      'dialog_leave_title': 'Vuoi uscire dal gruppo?',
      'dialog_leave_content': 'Non vedrai più questo gruppo nella tua lista',
      'info_leave_group': 'Esci dal gruppo',
      'leave_success': 'Sei uscito dal gruppo correttamente.',
      'leave_error': 'Errore durante l\'uscita: {error}',
      'items_selected': '{count} selezionati',
      'tab_board': 'Bacheca',
      'tab_members': 'Membri',
      'tab_info': 'Info',
      'home_upcoming_events': 'Prossimi Eventi',
      'location_not_specified': 'Posizione non specificata',
      'team_generic': 'Squadra',
      'without_title': 'Senza titolo',
      'info_invite_code_label': 'Codice invito',
      'info_code_copied': 'Codice copiato negli appunti',
      'info_sport': 'Sport',
      'loading': 'Caricamento...',

      //GROUP PAGE
      'login_error_group': 'Effettua il login per vedere i gruppi',
      'group_empty_title': 'Nessun gruppo',
      'group_empty_subtitle': 'Non fai ancora parte di nessun gruppo.\nCrealo o unisciti a uno esistente!',
      'group': 'Gruppo',
      'group_members_count': '{count} membri',

      //LOCATION PICKER PAGE
      'touch_map': 'Tocca la mappa o cerca un indirizzo',
      "location_not_found_query": "Nessun luogo trovato per \"{query}\"",
      'server_error': 'Errore server',
      'connection_error': 'Errore di connessione. Controlla internet',
      'searching_address': 'Ricerca indirizzo...',
      'unknown_address': 'Indirizzo sconosciuto',
      'address_not_found': 'Indirizzo sconosciuto',
      'hint_location': 'Cerca città o via...',
      'searching': 'Ricerca in corso...',
      'confirm_position': 'CONFERMA POSIZIONE',

      //MEMBER LIST PAGE
      'members_error': 'Impossibile caricare i membri',
      'no_members': 'Nessun membro nel gruppo',
      'members_list_title': 'Membri del team',
      'unknown_user': 'Utente sconosciuto',
      'you': ' (Tu)',
      'member_admin_badge': 'Admin',

      //MESSAGES PAGE
      'messages_empty_title': 'Nessuna chat',
      'messages_empty_subtitle': 'Entra in un gruppo per iniziare a chattare.',
      'chat_no_messages_yet': 'Nessun messaggio ancora',
      'chat_message_deleted_or_empty': '(messaggio vuoto)',

      //PAYMENTS SELECT RECIPIENTS PAGE
      'payment_select_people_title': 'Seleziona membri',
      'payment_select_people_subtitle': 'Scegli le persone a cui inviare la richiesta di pagamento',
      'payment_select_all': 'Seleziona tutti',
      'payment_clear_all': 'Deseleziona',
      'error_generic_with_details': 'Errore: {error}',

      //PAYMENTS PAGE
      'payment_delete_title': 'Elimina richiesta',
      'payment_delete_confirm': "Vuoi davvero eliminare questa richiesta di pagamento del gruppo \"{groupName}\"?",
      'payment_deleted_success': 'Richiesta di pagamento eliminata',
      'home_no_payments': 'Nessuna richiesta di pagamento',
      'payment_status_pending': 'In sospeso',
      'payment_status_paid': 'Pagato',
      'payment_status_partial': 'Parziale',
      'payment_default_title': 'Richiesta di pagamento',
      'user': 'Utente',

      //PROFILE SETTINGS PAGE
      'image_size_error_settings': 'Immagine troppo pesante per Firestore. Riprova',
      'toast_photo_error': 'Errore durante il caricamento della foto',
      'toast_save_success': 'Dati profilo salvati',
      'profile_title': 'Gestione Profilo',
      'profile_change_photo': 'Cambia foto profilo',
      'label_name': 'Nome',
      'label_day': 'Giorno',
      'label_month': 'Mese',
      'label_year': 'Anno',
      'label_gender': 'Genere',
      'label_sport': 'Sport praticato',
      'label_role': 'Ruolo del giocatore',
      'button_save': 'Salva',
      'month_01': 'Gennaio',
      'month_02': 'Febbraio',
      'month_03': 'Marzo',
      'month_04': 'Aprile',
      'month_05': 'Maggio',
      'month_06': 'Giugno',
      'month_07': 'Luglio',
      'month_08': 'Agosto',
      'month_09': 'Settembre',
      'month_10': 'Ottobre',
      'month_11': 'Novembre',
      'month_12': 'Dicembre',
      'gender_male': 'Maschio',
      'gender_female': 'Femmina',
      'gender_other': 'Altro',
      'logout_button': 'Esci',

      //SETTINGS PAGE
      'settings_language_app': 'Lingua dell\'applicazione',
      'language_italian': 'Italiano',
      'language_english': 'Inglese',
      'language_spanish': 'Spagnolo',
      'language_french': 'Francese',
      'language_german': 'Tedesco',
      'language_portuguese': 'Portoghese',
      'language_changed_snackbar': 'Lingua impostata su {language}',
      'settings_title': 'Impostazioni',
      'settings_section_theme': 'Tema',
      'settings_change_theme': 'Cambia tema',
      'settings_theme_dark_active': 'Il tema scuro è attivo',
      'settings_theme_light_active': 'Il tema chiaro è attivo',
      'settings_section_account': 'Account',
      'no_user': 'Nessun utente',
      'settings_account_email_subtitle': 'Email collegata all\'account',
      'settings_section_profile': 'Profilo',
      'settings_profile_manage_title': 'Gestione profilo',
      'settings_profile_manage_subtitle': 'Modifica nome, nascita, ruolo, sport...',
      'settings_section_language': 'Lingua',

      //USER PROFILE PAGE
      'profile_not_found': 'Profilo non trovato',
      'without_name': 'Senza nome',
      'birth_date': 'Data di nascita',
    },

    //INGLESE
    'en': {
      // LOGIN PAGE & REGISTER PAGE
      'push_init_failed': 'Notification initialization failed',
      'error_login': 'Error during login',
      'error_user_not_found': 'User not found',
      'error_wrong_password': 'Incorrect password',
      'error_invalid_email': 'Invalid email address',
      'error_unexpected_login': 'Unexpected error during login',
      'error_google_login': 'Error during Google login',
      'error_account_exists_different_credential': 'An account already exists with a different sign-in method',
      'error_invalid_google_credential': 'Invalid Google credentials',
      'error_user_disabled': 'User account disabled',
      'error_google_login_generic': 'Error during Google sign-in',
      'login_title': 'Welcome back!',
      'login_subtitle': 'Sign in to continue',
      'email_label': 'Email',
      'validation_insert_email': 'Enter your email',
      'validation_email_invalid': 'Invalid email',
      'password_label': 'Password',
      'validation_insert_password': 'Enter your password',
      'validation_min_6_chars': 'Minimum 6 characters',
      'forgot_password': 'Forgot password?',
      'password_reset_sent': 'Password reset email sent',
      'error_password_reset': 'Error during password reset',
      'error_too_many_requests': 'Too many attempts. Try again later',
      'error_unexpected_reset': 'Unexpected error during password reset',
      'login_button': 'Sign in',
      'login_with_google_loading': 'Signing in with Google...',
      'login_with_google': 'Sign up with Google',
      'no_account': 'Don’t have an account?',
      'go_to_register': 'Sign up',

      'registration_success': 'Registration completed successfully.\nWelcome to Grouply',
      'error_register': 'Error during registration',
      'error_email_in_use': 'This email is already registered',
      'error_weak_password': 'The password is too weak',
      'error_unexpected_register': 'Unexpected error during registration',
      'error_google_register': 'Error during Google registration',
      'register_title': 'Create an account',
      'register_subtitle': 'Sign up to get started',
      'go_to_login_button': 'Go to login page',
      'validation_insert_password_register': 'Enter a password',
      'validation_confirm_password': 'Confirm the password',
      'validation_passwords_not_match': 'Passwords do not match',
      'register_button': 'Sign up',
      'register_with_google_loading': 'Signing up with Google...',
      'register_with_google': 'Sign up with Google',
      'have_account': 'Already have an account?',

      // HOME PAGE
      'snack_group_created': 'Group created! Code: {code}',
      'error': 'Error',
      'error_code_not_found': 'No group found with this code',
      'error_already_member': 'You are already a member of this group!',
      'snack_join_success': 'You joined the group {groupName}!',
      'snack_join_error': 'Error while joining: {error}',
      'dialog_join_group_title': 'Join a Group',
      'label_insert_code': 'Enter invitation code (6 characters)',
      'button_cancel': 'Cancel',
      'validation_code_length': 'The code must be 6 characters long',
      'button_join': 'Join',
      'dialog_create_group_title': 'Create New Group',
      'label_team_name': 'Team name (e.g. Real Madrid)',
      'label_team_sport': 'Sport (e.g. Football)',
      'button_create': 'Create',
      'home_groups_dialog_title': 'Groups',
      'home_groups_create': 'Create new group',
      'home_groups_join': 'Enter group code',
      'close_button': 'Close',
      'home_tab_events': 'Events',
      'home_tab_posts': 'Posts',
      'home_tab_polls': 'Polls',
      'home_no_groups': 'You are not in any group. Join one to see events!',
      'home_no_events': 'No upcoming events',
      'post_delete_title': 'Delete post',
      'confirm_post_delete': 'Do you really want to delete this post?',
      'post_delete_cancel': 'Cancel',
      'post_delete_delete': 'Delete',
      'post_deleted_success': 'Post deleted',
      'home_no_posts': 'No posts on the board',
      'home_no_polls': 'No active polls',
      'poll_vote_saved': 'Vote saved',
      'poll_delete_title': 'Delete poll',
      'poll_delete_confirm': 'Do you really want to delete this poll from the group {groupName}?',
      'button_delete': 'Delete',
      'poll_deleted_success': 'Poll deleted',
      'poll_total_votes': '{count} votes',
      'poll_multiple_hint': 'You can select multiple options',
      'label_today': 'Today',
      'label_tomorrow': 'Tomorrow',
      'generic_event': 'Event',
      'tournament_event': 'Tournament',

      // CREATE EVENT PAGE
      'tournament_min_3': 'A tournament must have at least 3 teams!',
      'error_missing_fields': 'Please fill in all required fields',
      'event_created_success': 'Event created successfully!',
      'match_type_home': 'Home match',
      'match_type_away': 'Away match',
      'match_type_tournament': 'Tournament',
      'match_type_friendly': 'Friendly match',
      'create_event_title': 'Create event',
      'label_match_type': 'Match type',
      'label_date': 'Date',
      'label_start_time': 'Start time',
      'label_match_location': 'Match location',
      'map_select_placeholder': 'Select on the map',
      'label_meeting_point': 'Meeting point',
      'label_meeting_time': 'Meeting time',
      'label_home_team': 'Home team',
      'label_away_team': 'Away team',
      'label_tournament_teams': 'Participating teams',
      'hint_team_n': 'Team {number}',
      'btn_add_team': 'Add team',

      // CREATE PAYMENT REQUEST PAGE
      'toast_login_required': 'You must be logged in to save',
      'payment_admin_only_error': 'Only the administrator can create payment requests',
      'payment_no_recipients_error': 'Select at least one person',
      'payment_invalid_amount_error': 'Enter a valid amount',
      'payment_missing_fields_error': 'Please fill in all required fields',
      'payment_request_created_success': 'Request created successfully!',
      'payment_pick_date': 'Choose date',
      'payment_create_title': 'Payment request',
      'payment_recipients_label': 'Recipients',
      'payment_amount_label': 'Amount',
      'payment_amount_hint': 'e.g. 10.00',
      'payment_note_label': 'Description',
      'payment_note_hint': 'e.g. Monthly fee / Field / Kits...',
      'payment_due_date_label': 'Due date (optional)',
      'payment_creating': 'Sending...',
      'payment_send_request': 'Send request',

      // CREATE POLL PAGE
      'poll_missing_fields_error': 'Fill in the question and options',
      'poll_min_options_error': 'Enter at least 2 options',
      'poll_created_success': 'Poll created successfully!',
      'create_poll_title': 'Create a poll',
      'poll_question_label': 'Question',
      'poll_question_hint': 'e.g. Who is coming to training?',
      'poll_allow_multiple': 'Allow multiple selections',
      'poll_option_label': 'Option {number}',
      'poll_remove_option': 'Remove',
      'poll_add_option': 'Add option',
      'poll_creating': 'Creating poll...',
      'poll_publish': 'Publish poll',

      // CREATE POST PAGE
      'image_size_error': 'Image too large! Try a smaller one or take a screenshot',
      'file_size_error': 'File too large for Firestore (1MB limit)',
      'post_created_success': 'Post published successfully!',
      'error_save': 'Error during saving',
      'error_post_size_limit': 'Limit exceeded! The post (text + images) exceeds 1MB',
      'create_post_title': 'Create a post',
      'label_publish_in': 'Publish in:',
      'label_post_title': 'Post title',
      'label_post_description': 'Description',
      'btn_add_media': 'Photo/Video',
      'btn_add_attachment': 'Attachment',
      'btn_publish': 'Publish',

      // CREATE RECURRING EVENT PAGE
      'default_event_training': 'Training',
      'recurrence_daily': 'Every day',
      'recurrence_weekly': 'Every week',
      'recurrence_monthly': 'Every month',
      'create_recurring_event_title': 'Create recurring event',
      'label_event_name': 'Event name',
      'label_location': 'Location',
      'label_recurrence': 'Recurrence',
      'recurrence_info': 'Events will be generated for the next 3 months.',

      // EVENT DETAILS PAGE
      'delete_event_title': 'Delete event',
      'delete_event_confirm': 'Are you sure you want to delete this event? This action is irreversible.',
      'event_not_found': 'Event not found',
      'event_details_title': 'Event details',
      'status_title': 'Your attendance',
      'btn_decline': 'I will not attend',
      'btn_accept': 'I will attend',
      'status_going': 'Going',
      'status_not_going': 'Not going',
      'status_pending': 'Pending',

      // EVENT TYPE SELECTOR PAGE
      'event_select_type_title': 'Select type',
      'event_type_single': 'Event',
      'event_type_single_sub': 'Invite people to matches, tournaments or other social events',
      'event_type_recurring': 'Recurring event',
      'event_type_recurring_sub': 'Invite people to training sessions or other events',

      // GROUP CHAT PAGE
      'chat_send_error': 'Send error: {error}',
      'chat_empty': 'No messages yet. Write the first one!',
      'chat_hint': 'Write a message...',

      // GROUP DASHBOARD PAGE
      'admin_only_delete': 'Only the administrator can delete content',
      'delete_post_title': 'Delete posts',
      'delete_post_confirm': 'Do you want to delete the {count} selected posts?',
      'elements_deleted': '{count} items deleted',
      'fab_option_event': 'Event',
      'fab_option_post': 'Post',
      'fab_option_post_sub': 'Share information, photos and files',
      'fab_option_poll': 'Poll',
      'fab_option_poll_sub': 'Ask members for their opinion',
      'fab_option_payment': 'Payment requests',
      'fab_option_payment_sub': 'Collect fees from members',
      'dialog_leave_title': 'Do you want to leave the group?',
      'dialog_leave_content': 'You will no longer see this group in your list',
      'info_leave_group': 'Leave group',
      'leave_success': 'You have successfully left the group.',
      'leave_error': 'Error while leaving: {error}',
      'items_selected': '{count} selected',
      'tab_board': 'Board',
      'tab_members': 'Members',
      'tab_info': 'Info',
      'home_upcoming_events': 'Upcoming events',
      'location_not_specified': 'Location not specified',
      'team_generic': 'Team',
      'without_title': 'Untitled',
      'info_invite_code_label': 'Invite code',
      'info_code_copied': 'Code copied to clipboard',
      'info_sport': 'Sport',
      'loading': 'Loading...',

      // GROUP PAGE
      'login_error_group': 'Please log in to view groups',
      'group_empty_title': 'No groups',
      'group_empty_subtitle': 'You are not part of any group yet.\nCreate one or join an existing one!',
      'group': 'Group',
      'group_members_count': '{count} members',

      // LOCATION PICKER PAGE
      'touch_map': 'Tap the map or search for an address',
      'location_not_found_query': 'No location found for "{query}"',
      'server_error': 'Server error',
      'connection_error': 'Connection error. Check your internet connection',
      'searching_address': 'Searching address...',
      'unknown_address': 'Unknown address',
      'address_not_found': 'Address not found',
      'hint_location': 'Search city or street...',
      'searching': 'Searching...',
      'confirm_position': 'CONFIRM POSITION',

      // MEMBER LIST PAGE
      'members_error': 'Unable to load members',
      'no_members': 'No members in the group',
      'members_list_title': 'Team members',
      'unknown_user': 'Unknown user',
      'you': ' (You)',
      'member_admin_badge': 'Admin',

      // MESSAGES PAGE
      'messages_empty_title': 'No chats',
      'messages_empty_subtitle': 'Join a group to start chatting.',
      'chat_no_messages_yet': 'No messages yet',
      'chat_message_deleted_or_empty': '(empty message)',

      // PAYMENTS SELECT RECIPIENTS PAGE
      'payment_select_people_title': 'Select members',
      'payment_select_people_subtitle': 'Choose the people to send the payment request to',
      'payment_select_all': 'Select all',
      'payment_clear_all': 'Deselect',
      'error_generic_with_details': 'Error: {error}',

      // PAYMENTS PAGE
      'payment_delete_title': 'Delete request',
      'payment_delete_confirm': 'Do you really want to delete this payment request for the group "{groupName}"?',
      'payment_deleted_success': 'Payment request deleted',
      'home_no_payments': 'No payment requests',
      'payment_status_pending': 'Pending',
      'payment_status_paid': 'Paid',
      'payment_status_partial': 'Partial',
      'payment_default_title': 'Payment request',
      'user': 'User',

      // PROFILE SETTINGS PAGE
      'image_size_error_settings': 'Image too large for Firestore. Please try again',
      'toast_photo_error': 'Error while uploading photo',
      'toast_save_success': 'Profile data saved',
      'profile_title': 'Profile settings',
      'profile_change_photo': 'Change profile picture',
      'label_name': 'Name',
      'label_day': 'Day',
      'label_month': 'Month',
      'label_year': 'Year',
      'label_gender': 'Gender',
      'label_sport': 'Practiced sport',
      'label_role': 'Player role',
      'button_save': 'Save',
      'month_01': 'January',
      'month_02': 'February',
      'month_03': 'March',
      'month_04': 'April',
      'month_05': 'May',
      'month_06': 'June',
      'month_07': 'July',
      'month_08': 'August',
      'month_09': 'September',
      'month_10': 'October',
      'month_11': 'November',
      'month_12': 'December',
      'gender_male': 'Male',
      'gender_female': 'Female',
      'gender_other': 'Other',
      'logout_button': 'Log out',

      // SETTINGS PAGE
      'settings_language_app': 'App language',
      'language_italian': 'Italian',
      'language_english': 'English',
      'language_spanish': 'Spanish',
      'language_french': 'French',
      'language_german': 'German',
      'language_portuguese': 'Portuguese',
      'language_changed_snackbar': 'Language set to {language}',
      'settings_title': 'Settings',
      'settings_section_theme': 'Theme',
      'settings_change_theme': 'Change theme',
      'settings_theme_dark_active': 'Dark theme is active',
      'settings_theme_light_active': 'Light theme is active',
      'settings_section_account': 'Account',
      'no_user': 'No user',
      'settings_account_email_subtitle': 'Email linked to the account',
      'settings_section_profile': 'Profile',
      'settings_profile_manage_title': 'Profile management',
      'settings_profile_manage_subtitle': 'Edit name, birth date, role, sport...',
      'settings_section_language': 'Language',

      // USER PROFILE PAGE
      'profile_not_found': 'Profile not found',
      'without_name': 'No name',
      'birth_date': 'Birth date',
    },

    //SPAGNOLO
    'es': {
      // LOGIN PAGE & REGISTER PAGE
      'push_init_failed': 'Error al inicializar las notificaciones',
      'error_login': 'Error durante el inicio de sesión',
      'error_user_not_found': 'Usuario no encontrado',
      'error_wrong_password': 'Contraseña incorrecta',
      'error_invalid_email': 'Correo electrónico no válido',
      'error_unexpected_login': 'Error inesperado durante el inicio de sesión',
      'error_google_login': 'Error durante el inicio de sesión con Google',
      'error_account_exists_different_credential': 'Ya existe una cuenta con otro método de acceso',
      'error_invalid_google_credential': 'Credenciales de Google incorrectas',
      'error_user_disabled': 'Usuario deshabilitado',
      'error_google_login_generic': 'Error al iniciar sesión con Google',
      'login_title': '¡Bienvenido de nuevo!',
      'login_subtitle': 'Inicia sesión para continuar',
      'email_label': 'Correo electrónico',
      'validation_insert_email': 'Introduce tu correo electrónico',
      'validation_email_invalid': 'Correo electrónico no válido',
      'password_label': 'Contraseña',
      'validation_insert_password': 'Introduce la contraseña',
      'validation_min_6_chars': 'Mínimo 6 caracteres',
      'forgot_password': '¿Olvidaste la contraseña?',
      'password_reset_sent': 'Correo de restablecimiento enviado',
      'error_password_reset': 'Error al restablecer la contraseña',
      'error_too_many_requests': 'Demasiados intentos. Inténtalo más tarde',
      'error_unexpected_reset': 'Error inesperado al restablecer la contraseña',
      'login_button': 'Iniciar sesión',
      'login_with_google_loading': 'Iniciando sesión con Google...',
      'login_with_google': 'Regístrate con Google',
      'no_account': '¿No tienes una cuenta?',
      'go_to_register': 'Regístrate',

      'registration_success': 'Registro completado con éxito.\nTe damos la bienvenida a Grouply',
      'error_register': 'Error durante el registro',
      'error_email_in_use': 'Este correo electrónico ya está registrado',
      'error_weak_password': 'La contraseña es demasiado débil',
      'error_unexpected_register': 'Error inesperado durante el registro',
      'error_google_register': 'Error durante el registro con Google',
      'register_title': 'Crear una cuenta',
      'register_subtitle': 'Regístrate para comenzar',
      'go_to_login_button': 'Ir a la página de inicio de sesión',
      'validation_insert_password_register': 'Introduce una contraseña',
      'validation_confirm_password': 'Confirma la contraseña',
      'validation_passwords_not_match': 'Las contraseñas no coinciden',
      'register_button': 'Registrarse',
      'register_with_google_loading': 'Registrándose con Google...',
      'register_with_google': 'Registrarse con Google',
      'have_account': '¿Ya tienes una cuenta?',

      // HOME PAGE
      'snack_group_created': '¡Grupo creado! Código: {code}',
      'error': 'Error',
      'error_code_not_found': 'No se encontró ningún grupo con este código',
      'error_already_member': '¡Ya formas parte de este grupo!',
      'snack_join_success': '¡Te uniste al grupo {groupName}!',
      'snack_join_error': 'Error al unirse: {error}',
      'dialog_join_group_title': 'Unirse a un grupo',
      'label_insert_code': 'Introduce el código de invitación (6 caracteres)',
      'button_cancel': 'Cancelar',
      'validation_code_length': 'El código debe tener 6 caracteres',
      'button_join': 'Unirse',
      'dialog_create_group_title': 'Crear nuevo grupo',
      'label_team_name': 'Nombre del equipo (ej. Real Madrid)',
      'label_team_sport': 'Deporte (ej. Fútbol)',
      'button_create': 'Crear',
      'home_groups_dialog_title': 'Grupos',
      'home_groups_create': 'Crear nuevo grupo',
      'home_groups_join': 'Introducir código del grupo',
      'close_button': 'Cerrar',
      'home_tab_events': 'Eventos',
      'home_tab_posts': 'Publicaciones',
      'home_tab_polls': 'Encuestas',
      'home_no_groups': 'No estás en ningún grupo. ¡Únete a uno para ver los eventos!',
      'home_no_events': 'No hay eventos programados',
      'post_delete_title': 'Eliminar publicación',
      'confirm_post_delete': '¿Seguro que deseas eliminar esta publicación?',
      'post_delete_cancel': 'Cancelar',
      'post_delete_delete': 'Eliminar',
      'post_deleted_success': 'Publicación eliminada',
      'home_no_posts': 'No hay publicaciones',
      'home_no_polls': 'No hay encuestas activas',
      'poll_vote_saved': 'Voto guardado',
      'poll_delete_title': 'Eliminar encuesta',
      'poll_delete_confirm': '¿Seguro que deseas eliminar esta encuesta del grupo {groupName}?',
      'button_delete': 'Eliminar',
      'poll_deleted_success': 'Encuesta eliminada',
      'poll_total_votes': '{count} votos',
      'poll_multiple_hint': 'Puedes seleccionar varias opciones',
      'label_today': 'Hoy',
      'label_tomorrow': 'Mañana',
      'generic_event': 'Evento',
      'tournament_event': 'Torneo',

      // CREATE EVENT PAGE
      'tournament_min_3': '¡Un torneo debe tener al menos 3 equipos!',
      'error_missing_fields': 'Completa todos los campos obligatorios',
      'event_created_success': '¡Evento creado con éxito!',
      'match_type_home': 'Partido en casa',
      'match_type_away': 'Partido fuera de casa',
      'match_type_tournament': 'Torneo',
      'match_type_friendly': 'Amistoso',
      'create_event_title': 'Crear evento',
      'label_match_type': 'Tipo de partido',
      'label_date': 'Fecha',
      'label_start_time': 'Hora de inicio',
      'label_match_location': 'Lugar del partido',
      'map_select_placeholder': 'Seleccionar en el mapa',
      'label_meeting_point': 'Punto de encuentro',
      'label_meeting_time': 'Hora de encuentro',
      'label_home_team': 'Equipo local',
      'label_away_team': 'Equipo visitante',
      'label_tournament_teams': 'Equipos participantes',
      'hint_team_n': 'Equipo {number}',
      'btn_add_team': 'Agregar equipo',

      // CREATE PAYMENT REQUEST PAGE
      'toast_login_required': 'Debes iniciar sesión para guardar',
      'payment_admin_only_error': 'Solo el administrador puede crear solicitudes de pago',
      'payment_no_recipients_error': 'Selecciona al menos una persona',
      'payment_invalid_amount_error': 'Introduce un importe válido',
      'payment_missing_fields_error': 'Completa todos los campos requeridos',
      'payment_request_created_success': '¡Solicitud creada con éxito!',
      'payment_pick_date': 'Elegir fecha',
      'payment_create_title': 'Solicitud de pago',
      'payment_recipients_label': 'Destinatarios',
      'payment_amount_label': 'Importe',
      'payment_amount_hint': 'Ej. 10,00',
      'payment_note_label': 'Descripción',
      'payment_note_hint': 'Ej. Cuota mensual / Campo / Equipaciones...',
      'payment_due_date_label': 'Fecha de vencimiento (opcional)',
      'payment_creating': 'Enviando...',
      'payment_send_request': 'Enviar solicitud',

      // CREATE POLL PAGE
      'poll_missing_fields_error': 'Completa la pregunta y las opciones',
      'poll_min_options_error': 'Introduce al menos 2 opciones',
      'poll_created_success': '¡Encuesta creada con éxito!',
      'create_poll_title': 'Crear una encuesta',
      'poll_question_label': 'Pregunta',
      'poll_question_hint': 'Ej. ¿Quién viene al entrenamiento?',
      'poll_allow_multiple': 'Permitir selecciones múltiples',
      'poll_option_label': 'Opción {number}',
      'poll_remove_option': 'Eliminar',
      'poll_add_option': 'Agregar opción',
      'poll_creating': 'Creando encuesta...',
      'poll_publish': 'Publicar encuesta',

      // CREATE POST PAGE
      'image_size_error': '¡Imagen demasiado grande! Prueba con una más pequeña o haz una captura',
      'file_size_error': 'Archivo demasiado grande para Firestore (límite 1MB)',
      'post_created_success': '¡Publicación creada con éxito!',
      'error_save': 'Error durante el guardado',
      'error_post_size_limit': '¡Límite superado! La publicación (texto + imágenes) supera 1MB',
      'create_post_title': 'Crear una publicación',
      'label_publish_in': 'Publicar en:',
      'label_post_title': 'Título de la publicación',
      'label_post_description': 'Descripción',
      'btn_add_media': 'Foto/Video',
      'btn_add_attachment': 'Adjunto',
      'btn_publish': 'Publicar',

      // CREATE RECURRING EVENT PAGE
      'default_event_training': 'Entrenamiento',
      'recurrence_daily': 'Cada día',
      'recurrence_weekly': 'Cada semana',
      'recurrence_monthly': 'Cada mes',
      'create_recurring_event_title': 'Crear evento recurrente',
      'label_event_name': 'Nombre del evento',
      'label_location': 'Lugar',
      'label_recurrence': 'Repetición',
      'recurrence_info': 'Se generarán eventos para los próximos 3 meses.',

      // EVENT DETAILS PAGE
      'delete_event_title': 'Eliminar evento',
      'delete_event_confirm': '¿Estás seguro de que deseas eliminar este evento? Esta acción es irreversible.',
      'event_not_found': 'Evento no encontrado',
      'event_details_title': 'Detalles del evento',
      'status_title': 'Tu asistencia',
      'btn_decline': 'No asistiré',
      'btn_accept': 'Asistiré',
      'status_going': 'Asistiré',
      'status_not_going': 'No asistiré',
      'status_pending': 'Pendiente',

      // EVENT TYPE SELECTOR PAGE
      'event_select_type_title': 'Seleccionar tipo',
      'event_type_single': 'Evento',
      'event_type_single_sub': 'Invita personas a partidos, torneos u otros eventos sociales',
      'event_type_recurring': 'Evento recurrente',
      'event_type_recurring_sub': 'Invita personas a entrenamientos u otros eventos',

      // GROUP CHAT PAGE
      'chat_send_error': 'Error al enviar: {error}',
      'chat_empty': 'No hay mensajes. ¡Escribe el primero!',
      'chat_hint': 'Escribe un mensaje...',

      // GROUP DASHBOARD PAGE
      'admin_only_delete': 'Solo el administrador puede eliminar contenido',
      'delete_post_title': 'Eliminar publicaciones',
      'delete_post_confirm': '¿Deseas eliminar las {count} publicaciones seleccionadas?',
      'elements_deleted': '{count} elementos eliminados',
      'fab_option_event': 'Evento',
      'fab_option_post': 'Publicación',
      'fab_option_post_sub': 'Comparte información, fotos y archivos',
      'fab_option_poll': 'Encuesta',
      'fab_option_poll_sub': 'Pregunta la opinión de los miembros',
      'fab_option_payment': 'Solicitudes de pago',
      'fab_option_payment_sub': 'Recoge cuotas de los miembros',
      'dialog_leave_title': '¿Deseas salir del grupo?',
      'dialog_leave_content': 'Ya no verás este grupo en tu lista',
      'info_leave_group': 'Salir del grupo',
      'leave_success': 'Has salido del grupo correctamente.',
      'leave_error': 'Error al salir: {error}',
      'items_selected': '{count} seleccionados',
      'tab_board': 'Tablón',
      'tab_members': 'Miembros',
      'tab_info': 'Info',
      'home_upcoming_events': 'Próximos eventos',
      'location_not_specified': 'Ubicación no especificada',
      'team_generic': 'Equipo',
      'without_title': 'Sin título',
      'info_invite_code_label': 'Código de invitación',
      'info_code_copied': 'Código copiado al portapapeles',
      'info_sport': 'Deporte',
      'loading': 'Cargando...',

      // GROUP PAGE
      'login_error_group': 'Inicia sesión para ver los grupos',
      'group_empty_title': 'Sin grupos',
      'group_empty_subtitle': 'Aún no formas parte de ningún grupo.\n¡Crea uno o únete a uno existente!',
      'group': 'Grupo',
      'group_members_count': '{count} miembros',

      // LOCATION PICKER PAGE
      'touch_map': 'Toca el mapa o busca una dirección',
      'location_not_found_query': 'No se encontró ningún lugar para "{query}"',
      'server_error': 'Error del servidor',
      'connection_error': 'Error de conexión. Comprueba tu conexión a internet',
      'searching_address': 'Buscando dirección...',
      'unknown_address': 'Dirección desconocida',
      'address_not_found': 'Dirección no encontrada',
      'hint_location': 'Buscar ciudad o calle...',
      'searching': 'Buscando...',
      'confirm_position': 'CONFIRMAR POSICIÓN',

      // MEMBER LIST PAGE
      'members_error': 'No se pueden cargar los miembros',
      'no_members': 'No hay miembros en el grupo',
      'members_list_title': 'Miembros del equipo',
      'unknown_user': 'Usuario desconocido',
      'you': ' (Tú)',
      'member_admin_badge': 'Admin',

      // MESSAGES PAGE
      'messages_empty_title': 'Sin chats',
      'messages_empty_subtitle': 'Únete a un grupo para empezar a chatear.',
      'chat_no_messages_yet': 'Aún no hay mensajes',
      'chat_message_deleted_or_empty': '(mensaje vacío)',

      // PAYMENTS SELECT RECIPIENTS PAGE
      'payment_select_people_title': 'Seleccionar miembros',
      'payment_select_people_subtitle': 'Elige las personas a las que enviar la solicitud de pago',
      'payment_select_all': 'Seleccionar todos',
      'payment_clear_all': 'Deseleccionar',
      'error_generic_with_details': 'Error: {error}',

      // PAYMENTS PAGE
      'payment_delete_title': 'Eliminar solicitud',
      'payment_delete_confirm': '¿Deseas eliminar esta solicitud de pago del grupo "{groupName}"?',
      'payment_deleted_success': 'Solicitud de pago eliminada',
      'home_no_payments': 'No hay solicitudes de pago',
      'payment_status_pending': 'Pendiente',
      'payment_status_paid': 'Pagado',
      'payment_status_partial': 'Parcial',
      'payment_default_title': 'Solicitud de pago',
      'user': 'Usuario',

      // PROFILE SETTINGS PAGE
      'image_size_error_settings': 'Imagen demasiado grande para Firestore. Inténtalo de nuevo',
      'toast_photo_error': 'Error al cargar la foto',
      'toast_save_success': 'Datos del perfil guardados',
      'profile_title': 'Gestión del perfil',
      'profile_change_photo': 'Cambiar foto de perfil',
      'label_name': 'Nombre',
      'label_day': 'Día',
      'label_month': 'Mes',
      'label_year': 'Año',
      'label_gender': 'Género',
      'label_sport': 'Deporte practicado',
      'label_role': 'Rol del jugador',
      'button_save': 'Guardar',
      'month_01': 'Enero',
      'month_02': 'Febrero',
      'month_03': 'Marzo',
      'month_04': 'Abril',
      'month_05': 'Mayo',
      'month_06': 'Junio',
      'month_07': 'Julio',
      'month_08': 'Agosto',
      'month_09': 'Septiembre',
      'month_10': 'Octubre',
      'month_11': 'Noviembre',
      'month_12': 'Diciembre',
      'gender_male': 'Masculino',
      'gender_female': 'Femenino',
      'gender_other': 'Otro',
      'logout_button': 'Cerrar sesión',

      // SETTINGS PAGE
      'settings_language_app': 'Idioma de la aplicación',
      'language_italian': 'Italiano',
      'language_english': 'Inglés',
      'language_spanish': 'Español',
      'language_french': 'Francés',
      'language_german': 'Alemán',
      'language_portuguese': 'Portugués',
      'language_changed_snackbar': 'Idioma configurado en {language}',
      'settings_title': 'Configuración',
      'settings_section_theme': 'Tema',
      'settings_change_theme': 'Cambiar tema',
      'settings_theme_dark_active': 'El tema oscuro está activo',
      'settings_theme_light_active': 'El tema claro está activo',
      'settings_section_account': 'Cuenta',
      'no_user': 'Ningún usuario',
      'settings_account_email_subtitle': 'Correo electrónico vinculado a la cuenta',
      'settings_section_profile': 'Perfil',
      'settings_profile_manage_title': 'Gestión del perfil',
      'settings_profile_manage_subtitle': 'Editar nombre, fecha de nacimiento, rol, deporte...',
      'settings_section_language': 'Idioma',

      // USER PROFILE PAGE
      'profile_not_found': 'Perfil no encontrado',
      'without_name': 'Sin nombre',
      'birth_date': 'Fecha de nacimiento',
    },

    //FRANCESE
    'fr': {
      // LOGIN PAGE & REGISTER PAGE
      'push_init_failed': 'Échec de l’initialisation des notifications',
      'error_login': 'Erreur lors de la connexion',
      'error_user_not_found': 'Utilisateur introuvable',
      'error_wrong_password': 'Mot de passe incorrect',
      'error_invalid_email': 'Adresse e-mail invalide',
      'error_unexpected_login': 'Erreur inattendue lors de la connexion',
      'error_google_login': 'Erreur lors de la connexion avec Google',
      'error_account_exists_different_credential': 'Un compte existe déjà avec une autre méthode de connexion',
      'error_invalid_google_credential': 'Identifiants Google invalides',
      'error_user_disabled': 'Utilisateur désactivé',
      'error_google_login_generic': 'Erreur lors de la connexion avec Google',
      'login_title': 'Bon retour !',
      'login_subtitle': 'Connectez-vous pour continuer',
      'email_label': 'E-mail',
      'validation_insert_email': 'Entrez votre e-mail',
      'validation_email_invalid': 'E-mail invalide',
      'password_label': 'Mot de passe',
      'validation_insert_password': 'Entrez votre mot de passe',
      'validation_min_6_chars': 'Minimum 6 caractères',
      'forgot_password': 'Mot de passe oublié ?',
      'password_reset_sent': 'E-mail de réinitialisation envoyé',
      'error_password_reset': 'Erreur lors de la réinitialisation du mot de passe',
      'error_too_many_requests': 'Trop de tentatives. Réessayez plus tard',
      'error_unexpected_reset': 'Erreur inattendue lors de la réinitialisation',
      'login_button': 'Se connecter',
      'login_with_google_loading': 'Connexion avec Google...',
      'login_with_google': 'S’inscrire avec Google',
      'no_account': 'Vous n’avez pas de compte ?',
      'go_to_register': 'S’inscrire',

      'registration_success': 'Inscription réussie.\nBienvenue sur Grouply',
      'error_register': 'Erreur lors de l’inscription',
      'error_email_in_use': 'Cette adresse e-mail est déjà enregistrée',
      'error_weak_password': 'Le mot de passe est trop faible',
      'error_unexpected_register': 'Erreur inattendue lors de l’inscription',
      'error_google_register': 'Erreur lors de l’inscription avec Google',
      'register_title': 'Créer un compte',
      'register_subtitle': 'Inscrivez-vous pour commencer',
      'go_to_login_button': 'Aller à la page de connexion',
      'validation_insert_password_register': 'Entrez un mot de passe',
      'validation_confirm_password': 'Confirmez le mot de passe',
      'validation_passwords_not_match': 'Les mots de passe ne correspondent pas',
      'register_button': 'S’inscrire',
      'register_with_google_loading': 'Inscription avec Google...',
      'register_with_google': 'S’inscrire avec Google',
      'have_account': 'Vous avez déjà un compte ?',

      // HOME PAGE
      'snack_group_created': 'Groupe créé ! Code : {code}',
      'error': 'Erreur',
      'error_code_not_found': 'Aucun groupe trouvé avec ce code',
      'error_already_member': 'Vous faites déjà partie de ce groupe !',
      'snack_join_success': 'Vous avez rejoint le groupe {groupName} !',
      'snack_join_error': 'Erreur lors de l’adhésion : {error}',
      'dialog_join_group_title': 'Rejoindre un groupe',
      'label_insert_code': 'Entrez le code d’invitation (6 caractères)',
      'button_cancel': 'Annuler',
      'validation_code_length': 'Le code doit contenir 6 caractères',
      'button_join': 'Rejoindre',
      'dialog_create_group_title': 'Créer un nouveau groupe',
      'label_team_name': 'Nom de l’équipe (ex. Real Madrid)',
      'label_team_sport': 'Sport (ex. Football)',
      'button_create': 'Créer',
      'home_groups_dialog_title': 'Groupes',
      'home_groups_create': 'Créer un nouveau groupe',
      'home_groups_join': 'Entrer le code du groupe',
      'close_button': 'Fermer',
      'home_tab_events': 'Événements',
      'home_tab_posts': 'Publications',
      'home_tab_polls': 'Sondages',
      'home_no_groups': 'Vous n’êtes dans aucun groupe. Rejoignez-en un pour voir les événements !',
      'home_no_events': 'Aucun événement prévu',
      'post_delete_title': 'Supprimer la publication',
      'confirm_post_delete': 'Voulez-vous vraiment supprimer cette publication ?',
      'post_delete_cancel': 'Annuler',
      'post_delete_delete': 'Supprimer',
      'post_deleted_success': 'Publication supprimée',
      'home_no_posts': 'Aucune publication',
      'home_no_polls': 'Aucun sondage actif',
      'poll_vote_saved': 'Vote enregistré',
      'poll_delete_title': 'Supprimer le sondage',
      'poll_delete_confirm': 'Voulez-vous vraiment supprimer ce sondage du groupe {groupName} ?',
      'button_delete': 'Supprimer',
      'poll_deleted_success': 'Sondage supprimé',
      'poll_total_votes': '{count} votes',
      'poll_multiple_hint': 'Vous pouvez sélectionner plusieurs options',
      'label_today': 'Aujourd’hui',
      'label_tomorrow': 'Demain',
      'generic_event': 'Événement',
      'tournament_event': 'Tournoi',

      // CREATE EVENT PAGE
      'tournament_min_3': 'Un tournoi doit avoir au moins 3 équipes !',
      'error_missing_fields': 'Veuillez remplir tous les champs obligatoires',
      'event_created_success': 'Événement créé avec succès !',
      'match_type_home': 'Match à domicile',
      'match_type_away': 'Match à l’extérieur',
      'match_type_tournament': 'Tournoi',
      'match_type_friendly': 'Match amical',
      'create_event_title': 'Créer un événement',
      'label_match_type': 'Type de match',
      'label_date': 'Date',
      'label_start_time': 'Heure de début',
      'label_match_location': 'Lieu du match',
      'map_select_placeholder': 'Sélectionner sur la carte',
      'label_meeting_point': 'Lieu de rendez-vous',
      'label_meeting_time': 'Heure du rendez-vous',
      'label_home_team': 'Équipe à domicile',
      'label_away_team': 'Équipe à l’extérieur',
      'label_tournament_teams': 'Équipes participantes',
      'hint_team_n': 'Équipe {number}',
      'btn_add_team': 'Ajouter une équipe',

      // CREATE PAYMENT REQUEST PAGE
      'toast_login_required': 'Vous devez être connecté pour enregistrer',
      'payment_admin_only_error': 'Seul l’administrateur peut créer des demandes de paiement',
      'payment_no_recipients_error': 'Sélectionnez au moins une personne',
      'payment_invalid_amount_error': 'Entrez un montant valide',
      'payment_missing_fields_error': 'Veuillez remplir tous les champs requis',
      'payment_request_created_success': 'Demande créée avec succès !',
      'payment_pick_date': 'Choisir une date',
      'payment_create_title': 'Demande de paiement',
      'payment_recipients_label': 'Destinataires',
      'payment_amount_label': 'Montant',
      'payment_amount_hint': 'Ex. 10,00',
      'payment_note_label': 'Description',
      'payment_note_hint': 'Ex. Cotisation mensuelle / Terrain / Équipements...',
      'payment_due_date_label': 'Date d’échéance (optionnelle)',
      'payment_creating': 'Envoi...',
      'payment_send_request': 'Envoyer la demande',

      // CREATE POLL PAGE
      'poll_missing_fields_error': 'Remplissez la question et les options',
      'poll_min_options_error': 'Entrez au moins 2 options',
      'poll_created_success': 'Sondage créé avec succès !',
      'create_poll_title': 'Créer un sondage',
      'poll_question_label': 'Question',
      'poll_question_hint': 'Ex. Qui vient à l’entraînement ?',
      'poll_allow_multiple': 'Autoriser les sélections multiples',
      'poll_option_label': 'Option {number}',
      'poll_remove_option': 'Supprimer',
      'poll_add_option': 'Ajouter une option',
      'poll_creating': 'Création du sondage...',
      'poll_publish': 'Publier le sondage',

      // CREATE POST PAGE
      'image_size_error': 'Image trop lourde ! Essayez une plus petite ou prenez une capture d’écran',
      'file_size_error': 'Fichier trop volumineux pour Firestore (limite 1MB)',
      'post_created_success': 'Publication créée avec succès !',
      'error_save': 'Erreur lors de l’enregistrement',
      'error_post_size_limit': 'Limite dépassée ! La publication (texte + images) dépasse 1MB',
      'create_post_title': 'Créer une publication',
      'label_publish_in': 'Publier dans :',
      'label_post_title': 'Titre de la publication',
      'label_post_description': 'Description',
      'btn_add_media': 'Photo/Vidéo',
      'btn_add_attachment': 'Pièce jointe',
      'btn_publish': 'Publier',

      // CREATE RECURRING EVENT PAGE
      'default_event_training': 'Entraînement',
      'recurrence_daily': 'Chaque jour',
      'recurrence_weekly': 'Chaque semaine',
      'recurrence_monthly': 'Chaque mois',
      'create_recurring_event_title': 'Créer un événement récurrent',
      'label_event_name': 'Nom de l’événement',
      'label_location': 'Lieu',
      'label_recurrence': 'Répétition',
      'recurrence_info': 'Des événements seront générés pour les 3 prochains mois.',

      // EVENT DETAILS PAGE
      'delete_event_title': 'Supprimer l’événement',
      'delete_event_confirm': 'Êtes-vous sûr de vouloir supprimer cet événement ? Cette action est irréversible.',
      'event_not_found': 'Événement introuvable',
      'event_details_title': 'Détails de l’événement',
      'status_title': 'Votre présence',
      'btn_decline': 'Je ne serai pas présent',
      'btn_accept': 'Je serai présent',
      'status_going': 'Présent',
      'status_not_going': 'Absent',
      'status_pending': 'En attente',

      // EVENT TYPE SELECTOR PAGE
      'event_select_type_title': 'Sélectionner le type',
      'event_type_single': 'Événement',
      'event_type_single_sub': 'Invitez des personnes à des matchs, tournois ou autres événements sociaux',
      'event_type_recurring': 'Événement récurrent',
      'event_type_recurring_sub': 'Invitez des personnes à des entraînements ou autres événements',

      // GROUP CHAT PAGE
      'chat_send_error': 'Erreur d’envoi : {error}',
      'chat_empty': 'Aucun message. Écrivez le premier !',
      'chat_hint': 'Écrire un message...',

      // GROUP DASHBOARD PAGE
      'admin_only_delete': 'Seul l’administrateur peut supprimer du contenu',
      'delete_post_title': 'Supprimer les publications',
      'delete_post_confirm': 'Voulez-vous supprimer les {count} publications sélectionnées ?',
      'elements_deleted': '{count} éléments supprimés',
      'fab_option_event': 'Événement',
      'fab_option_post': 'Publication',
      'fab_option_post_sub': 'Partager des informations, photos et fichiers',
      'fab_option_poll': 'Sondage',
      'fab_option_poll_sub': 'Demander l’avis des membres',
      'fab_option_payment': 'Demandes de paiement',
      'fab_option_payment_sub': 'Collecter des cotisations auprès des membres',
      'dialog_leave_title': 'Voulez-vous quitter le groupe ?',
      'dialog_leave_content': 'Vous ne verrez plus ce groupe dans votre liste',
      'info_leave_group': 'Quitter le groupe',
      'leave_success': 'Vous avez quitté le groupe avec succès.',
      'leave_error': 'Erreur lors de la sortie : {error}',
      'items_selected': '{count} sélectionnés',
      'tab_board': 'Tableau',
      'tab_members': 'Membres',
      'tab_info': 'Infos',
      'home_upcoming_events': 'Événements à venir',
      'location_not_specified': 'Lieu non spécifié',
      'team_generic': 'Équipe',
      'without_title': 'Sans titre',
      'info_invite_code_label': 'Code d’invitation',
      'info_code_copied': 'Code copié dans le presse-papiers',
      'info_sport': 'Sport',
      'loading': 'Chargement...',

      // GROUP PAGE
      'login_error_group': 'Connectez-vous pour voir les groupes',
      'group_empty_title': 'Aucun groupe',
      'group_empty_subtitle': 'Vous ne faites partie d’aucun groupe pour le moment.\nCréez-en un ou rejoignez-en un existant !',
      'group': 'Groupe',
      'group_members_count': '{count} membres',

      // LOCATION PICKER PAGE
      'touch_map': 'Touchez la carte ou recherchez une adresse',
      'location_not_found_query': 'Aucun lieu trouvé pour "{query}"',
      'server_error': 'Erreur serveur',
      'connection_error': 'Erreur de connexion. Vérifiez votre connexion internet',
      'searching_address': 'Recherche de l’adresse...',
      'unknown_address': 'Adresse inconnue',
      'address_not_found': 'Adresse introuvable',
      'hint_location': 'Rechercher une ville ou une rue...',
      'searching': 'Recherche...',
      'confirm_position': 'CONFIRMER LA POSITION',

      // MEMBER LIST PAGE
      'members_error': 'Impossible de charger les membres',
      'no_members': 'Aucun membre dans le groupe',
      'members_list_title': 'Membres de l’équipe',
      'unknown_user': 'Utilisateur inconnu',
      'you': ' (Vous)',
      'member_admin_badge': 'Admin',

      // MESSAGES PAGE
      'messages_empty_title': 'Aucune discussion',
      'messages_empty_subtitle': 'Rejoignez un groupe pour commencer à discuter.',
      'chat_no_messages_yet': 'Aucun message pour le moment',
      'chat_message_deleted_or_empty': '(message vide)',

      // PAYMENTS SELECT RECIPIENTS PAGE
      'payment_select_people_title': 'Sélectionner des membres',
      'payment_select_people_subtitle': 'Choisissez les personnes à qui envoyer la demande de paiement',
      'payment_select_all': 'Tout sélectionner',
      'payment_clear_all': 'Désélectionner',
      'error_generic_with_details': 'Erreur : {error}',

      // PAYMENTS PAGE
      'payment_delete_title': 'Supprimer la demande',
      'payment_delete_confirm': 'Voulez-vous vraiment supprimer cette demande de paiement du groupe "{groupName}" ?',
      'payment_deleted_success': 'Demande de paiement supprimée',
      'home_no_payments': 'Aucune demande de paiement',
      'payment_status_pending': 'En attente',
      'payment_status_paid': 'Payé',
      'payment_status_partial': 'Partiel',
      'payment_default_title': 'Demande de paiement',
      'user': 'Utilisateur',

      // PROFILE SETTINGS PAGE
      'image_size_error_settings': 'Image trop volumineuse pour Firestore. Veuillez réessayer',
      'toast_photo_error': 'Erreur lors du chargement de la photo',
      'toast_save_success': 'Données du profil enregistrées',
      'profile_title': 'Gestion du profil',
      'profile_change_photo': 'Changer la photo de profil',
      'label_name': 'Nom',
      'label_day': 'Jour',
      'label_month': 'Mois',
      'label_year': 'Année',
      'label_gender': 'Genre',
      'label_sport': 'Sport pratiqué',
      'label_role': 'Rôle du joueur',
      'button_save': 'Enregistrer',
      'month_01': 'Janvier',
      'month_02': 'Février',
      'month_03': 'Mars',
      'month_04': 'Avril',
      'month_05': 'Mai',
      'month_06': 'Juin',
      'month_07': 'Juillet',
      'month_08': 'Août',
      'month_09': 'Septembre',
      'month_10': 'Octobre',
      'month_11': 'Novembre',
      'month_12': 'Décembre',
      'gender_male': 'Homme',
      'gender_female': 'Femme',
      'gender_other': 'Autre',
      'logout_button': 'Se déconnecter',

      // SETTINGS PAGE
      'settings_language_app': 'Langue de l’application',
      'language_italian': 'Italien',
      'language_english': 'Anglais',
      'language_spanish': 'Espagnol',
      'language_french': 'Français',
      'language_german': 'Allemand',
      'language_portuguese': 'Portugais',
      'language_changed_snackbar': 'Langue définie sur {language}',
      'settings_title': 'Paramètres',
      'settings_section_theme': 'Thème',
      'settings_change_theme': 'Changer le thème',
      'settings_theme_dark_active': 'Le thème sombre est actif',
      'settings_theme_light_active': 'Le thème clair est actif',
      'settings_section_account': 'Compte',
      'no_user': 'Aucun utilisateur',
      'settings_account_email_subtitle': 'Adresse e-mail associée au compte',
      'settings_section_profile': 'Profil',
      'settings_profile_manage_title': 'Gestion du profil',
      'settings_profile_manage_subtitle': 'Modifier le nom, la date de naissance, le rôle, le sport...',
      'settings_section_language': 'Langue',

      // USER PROFILE PAGE
      'profile_not_found': 'Profil introuvable',
      'without_name': 'Sans nom',
      'birth_date': 'Date de naissance',
    },

    //TEDESCO
    'de': {
      // LOGIN PAGE & REGISTER PAGE
      'push_init_failed': 'Initialisierung der Benachrichtigungen fehlgeschlagen',
      'error_login': 'Fehler beim Anmelden',
      'error_user_not_found': 'Benutzer nicht gefunden',
      'error_wrong_password': 'Falsches Passwort',
      'error_invalid_email': 'Ungültige E-Mail-Adresse',
      'error_unexpected_login': 'Unerwarteter Fehler beim Anmelden',
      'error_google_login': 'Fehler bei der Anmeldung mit Google',
      'error_account_exists_different_credential': 'Ein Konto mit einer anderen Anmeldemethode existiert bereits',
      'error_invalid_google_credential': 'Ungültige Google-Anmeldedaten',
      'error_user_disabled': 'Benutzer deaktiviert',
      'error_google_login_generic': 'Fehler bei der Anmeldung mit Google',
      'login_title': 'Willkommen zurück!',
      'login_subtitle': 'Melden Sie sich an, um fortzufahren',
      'email_label': 'E-Mail',
      'validation_insert_email': 'Geben Sie Ihre E-Mail ein',
      'validation_email_invalid': 'Ungültige E-Mail',
      'password_label': 'Passwort',
      'validation_insert_password': 'Geben Sie Ihr Passwort ein',
      'validation_min_6_chars': 'Mindestens 6 Zeichen',
      'forgot_password': 'Passwort vergessen?',
      'password_reset_sent': 'E-Mail zum Zurücksetzen gesendet',
      'error_password_reset': 'Fehler beim Zurücksetzen des Passworts',
      'error_too_many_requests': 'Zu viele Versuche. Bitte später erneut versuchen',
      'error_unexpected_reset': 'Unerwarteter Fehler beim Zurücksetzen',
      'login_button': 'Anmelden',
      'login_with_google_loading': 'Anmeldung mit Google...',
      'login_with_google': 'Mit Google registrieren',
      'no_account': 'Noch kein Konto?',
      'go_to_register': 'Registrieren',

      'registration_success': 'Registrierung erfolgreich abgeschlossen.\nWillkommen bei Grouply',
      'error_register': 'Fehler bei der Registrierung',
      'error_email_in_use': 'Diese E-Mail-Adresse ist bereits registriert',
      'error_weak_password': 'Das Passwort ist zu schwach',
      'error_unexpected_register': 'Unerwarteter Fehler bei der Registrierung',
      'error_google_register': 'Fehler bei der Registrierung mit Google',
      'register_title': 'Konto erstellen',
      'register_subtitle': 'Registrieren Sie sich, um zu starten',
      'go_to_login_button': 'Zur Login-Seite wechseln',
      'validation_insert_password_register': 'Geben Sie ein Passwort ein',
      'validation_confirm_password': 'Passwort bestätigen',
      'validation_passwords_not_match': 'Passwörter stimmen nicht überein',
      'register_button': 'Registrieren',
      'register_with_google_loading': 'Registrierung mit Google...',
      'register_with_google': 'Mit Google registrieren',
      'have_account': 'Haben Sie bereits ein Konto?',

      // HOME PAGE
      'snack_group_created': 'Gruppe erstellt! Code: {code}',
      'error': 'Fehler',
      'error_code_not_found': 'Keine Gruppe mit diesem Code gefunden',
      'error_already_member': 'Du bist bereits Mitglied dieser Gruppe!',
      'snack_join_success': 'Du bist der Gruppe {groupName} beigetreten!',
      'snack_join_error': 'Fehler beim Beitritt: {error}',
      'dialog_join_group_title': 'Gruppe beitreten',
      'label_insert_code': 'Einladungscode eingeben (6 Zeichen)',
      'button_cancel': 'Abbrechen',
      'validation_code_length': 'Der Code muss 6 Zeichen lang sein',
      'button_join': 'Beitreten',
      'dialog_create_group_title': 'Neue Gruppe erstellen',
      'label_team_name': 'Teamname (z.B. Real Madrid)',
      'label_team_sport': 'Sport (z.B. Fußball)',
      'button_create': 'Erstellen',
      'home_groups_dialog_title': 'Gruppen',
      'home_groups_create': 'Neue Gruppe erstellen',
      'home_groups_join': 'Gruppencode eingeben',
      'close_button': 'Schließen',
      'home_tab_events': 'Events',
      'home_tab_posts': 'Beiträge',
      'home_tab_polls': 'Umfragen',
      'home_no_groups': 'Du bist in keiner Gruppe. Tritt einer bei, um Events zu sehen!',
      'home_no_events': 'Keine geplanten Events',
      'post_delete_title': 'Beitrag löschen',
      'confirm_post_delete': 'Möchtest du diesen Beitrag wirklich löschen?',
      'post_delete_cancel': 'Abbrechen',
      'post_delete_delete': 'Löschen',
      'post_deleted_success': 'Beitrag gelöscht',
      'home_no_posts': 'Keine Beiträge vorhanden',
      'home_no_polls': 'Keine aktiven Umfragen',
      'poll_vote_saved': 'Stimme gespeichert',
      'poll_delete_title': 'Umfrage löschen',
      'poll_delete_confirm': 'Möchtest du diese Umfrage aus der Gruppe {groupName} wirklich löschen?',
      'button_delete': 'Löschen',
      'poll_deleted_success': 'Umfrage gelöscht',
      'poll_total_votes': '{count} Stimmen',
      'poll_multiple_hint': 'Mehrere Optionen können ausgewählt werden',
      'label_today': 'Heute',
      'label_tomorrow': 'Morgen',
      'generic_event': 'Event',
      'tournament_event': 'Turnier',

      // CREATE EVENT PAGE
      'tournament_min_3': 'Ein Turnier muss mindestens 3 Teams haben!',
      'error_missing_fields': 'Bitte füllen Sie alle Pflichtfelder aus',
      'event_created_success': 'Event erfolgreich erstellt!',
      'match_type_home': 'Heimspiel',
      'match_type_away': 'Auswärtsspiel',
      'match_type_tournament': 'Turnier',
      'match_type_friendly': 'Freundschaftsspiel',
      'create_event_title': 'Event erstellen',
      'label_match_type': 'Spieltyp',
      'label_date': 'Datum',
      'label_start_time': 'Startzeit',
      'label_match_location': 'Spielort',
      'map_select_placeholder': 'Auf der Karte auswählen',
      'label_meeting_point': 'Treffpunkt',
      'label_meeting_time': 'Treffzeit',
      'label_home_team': 'Heimmannschaft',
      'label_away_team': 'Auswärtsmannschaft',
      'label_tournament_teams': 'Teilnehmende Teams',
      'hint_team_n': 'Team {number}',
      'btn_add_team': 'Team hinzufügen',

      // CREATE PAYMENT REQUEST PAGE
      'toast_login_required': 'Du musst angemeldet sein, um zu speichern',
      'payment_admin_only_error': 'Nur der Administrator kann Zahlungsanfragen erstellen',
      'payment_no_recipients_error': 'Wähle mindestens eine Person aus',
      'payment_invalid_amount_error': 'Gib einen gültigen Betrag ein',
      'payment_missing_fields_error': 'Bitte fülle alle erforderlichen Felder aus',
      'payment_request_created_success': 'Anfrage erfolgreich erstellt!',
      'payment_pick_date': 'Datum auswählen',
      'payment_create_title': 'Zahlungsanfrage',
      'payment_recipients_label': 'Empfänger',
      'payment_amount_label': 'Betrag',
      'payment_amount_hint': 'z.B. 10,00',
      'payment_note_label': 'Beschreibung',
      'payment_note_hint': 'z.B. Monatsbeitrag / Platz / Trikots...',
      'payment_due_date_label': 'Fälligkeitsdatum (optional)',
      'payment_creating': 'Senden...',
      'payment_send_request': 'Anfrage senden',

      // CREATE POLL PAGE
      'poll_missing_fields_error': 'Frage und Optionen ausfüllen',
      'poll_min_options_error': 'Mindestens 2 Optionen eingeben',
      'poll_created_success': 'Umfrage erfolgreich erstellt!',
      'create_poll_title': 'Umfrage erstellen',
      'poll_question_label': 'Frage',
      'poll_question_hint': 'z.B. Wer kommt zum Training?',
      'poll_allow_multiple': 'Mehrfachauswahl erlauben',
      'poll_option_label': 'Option {number}',
      'poll_remove_option': 'Entfernen',
      'poll_add_option': 'Option hinzufügen',
      'poll_creating': 'Umfrage wird erstellt...',
      'poll_publish': 'Umfrage veröffentlichen',

      // CREATE POST PAGE
      'image_size_error': 'Bild zu groß! Versuche ein kleineres oder mache einen Screenshot',
      'file_size_error': 'Datei zu groß für Firestore (1MB-Limit)',
      'post_created_success': 'Beitrag erfolgreich veröffentlicht!',
      'error_save': 'Fehler beim Speichern',
      'error_post_size_limit': 'Limit überschritten! Der Beitrag (Text + Bilder) ist größer als 1MB',
      'create_post_title': 'Beitrag erstellen',
      'label_publish_in': 'Veröffentlichen in:',
      'label_post_title': 'Beitragstitel',
      'label_post_description': 'Beschreibung',
      'btn_add_media': 'Foto/Video',
      'btn_add_attachment': 'Anhang',
      'btn_publish': 'Veröffentlichen',

      // CREATE RECURRING EVENT PAGE
      'default_event_training': 'Training',
      'recurrence_daily': 'Jeden Tag',
      'recurrence_weekly': 'Jede Woche',
      'recurrence_monthly': 'Jeden Monat',
      'create_recurring_event_title': 'Wiederkehrendes Event erstellen',
      'label_event_name': 'Eventname',
      'label_location': 'Ort',
      'label_recurrence': 'Wiederholung',
      'recurrence_info': 'Für die nächsten 3 Monate werden Events erstellt.',

      // EVENT DETAILS PAGE
      'delete_event_title': 'Event löschen',
      'delete_event_confirm': 'Möchtest du dieses Event wirklich löschen? Diese Aktion ist nicht rückgängig zu machen.',
      'event_not_found': 'Event nicht gefunden',
      'event_details_title': 'Eventdetails',
      'status_title': 'Deine Teilnahme',
      'btn_decline': 'Ich komme nicht',
      'btn_accept': 'Ich komme',
      'status_going': 'Dabei',
      'status_not_going': 'Nicht dabei',
      'status_pending': 'Ausstehend',

      // EVENT TYPE SELECTOR PAGE
      'event_select_type_title': 'Typ auswählen',
      'event_type_single': 'Event',
      'event_type_single_sub': 'Lade Personen zu Spielen, Turnieren oder anderen sozialen Events ein',
      'event_type_recurring': 'Wiederkehrendes Event',
      'event_type_recurring_sub': 'Lade Personen zu Trainings oder anderen Events ein',

      // GROUP CHAT PAGE
      'chat_send_error': 'Fehler beim Senden: {error}',
      'chat_empty': 'Keine Nachrichten. Schreibe die erste!',
      'chat_hint': 'Nachricht schreiben...',

      // GROUP DASHBOARD PAGE
      'admin_only_delete': 'Nur der Administrator kann Inhalte löschen',
      'delete_post_title': 'Beiträge löschen',
      'delete_post_confirm': 'Möchtest du die {count} ausgewählten Beiträge löschen?',
      'elements_deleted': '{count} Elemente gelöscht',
      'fab_option_event': 'Event',
      'fab_option_post': 'Beitrag',
      'fab_option_post_sub': 'Informationen, Fotos und Dateien teilen',
      'fab_option_poll': 'Umfrage',
      'fab_option_poll_sub': 'Mitglieder nach ihrer Meinung fragen',
      'fab_option_payment': 'Zahlungsanfragen',
      'fab_option_payment_sub': 'Beiträge von Mitgliedern einziehen',
      'dialog_leave_title': 'Möchtest du die Gruppe verlassen?',
      'dialog_leave_content': 'Diese Gruppe wird nicht mehr in deiner Liste angezeigt',
      'info_leave_group': 'Gruppe verlassen',
      'leave_success': 'Du hast die Gruppe erfolgreich verlassen.',
      'leave_error': 'Fehler beim Verlassen: {error}',
      'items_selected': '{count} ausgewählt',
      'tab_board': 'Pinnwand',
      'tab_members': 'Mitglieder',
      'tab_info': 'Info',
      'home_upcoming_events': 'Kommende Events',
      'location_not_specified': 'Ort nicht angegeben',
      'team_generic': 'Team',
      'without_title': 'Ohne Titel',
      'info_invite_code_label': 'Einladungscode',
      'info_code_copied': 'Code in die Zwischenablage kopiert',
      'info_sport': 'Sport',
      'loading': 'Wird geladen...',

      // GROUP PAGE
      'login_error_group': 'Bitte melde dich an, um Gruppen zu sehen',
      'group_empty_title': 'Keine Gruppen',
      'group_empty_subtitle': 'Du bist noch in keiner Gruppe.\nErstelle eine oder tritt einer bestehenden bei!',
      'group': 'Gruppe',
      'group_members_count': '{count} Mitglieder',

      // LOCATION PICKER PAGE
      'touch_map': 'Tippe auf die Karte oder suche nach einer Adresse',
      'location_not_found_query': 'Kein Ort gefunden für "{query}"',
      'server_error': 'Serverfehler',
      'connection_error': 'Verbindungsfehler. Überprüfe deine Internetverbindung',
      'searching_address': 'Adresse wird gesucht...',
      'unknown_address': 'Unbekannte Adresse',
      'address_not_found': 'Adresse nicht gefunden',
      'hint_location': 'Stadt oder Straße suchen...',
      'searching': 'Suche...',
      'confirm_position': 'POSITION BESTÄTIGEN',

      // MEMBER LIST PAGE
      'members_error': 'Mitglieder konnten nicht geladen werden',
      'no_members': 'Keine Mitglieder in der Gruppe',
      'members_list_title': 'Teammitglieder',
      'unknown_user': 'Unbekannter Benutzer',
      'you': ' (Du)',
      'member_admin_badge': 'Admin',

      // MESSAGES PAGE
      'messages_empty_title': 'Keine Chats',
      'messages_empty_subtitle': 'Tritt einer Gruppe bei, um zu chatten.',
      'chat_no_messages_yet': 'Noch keine Nachrichten',
      'chat_message_deleted_or_empty': '(leere Nachricht)',

      // PAYMENTS SELECT RECIPIENTS PAGE
      'payment_select_people_title': 'Mitglieder auswählen',
      'payment_select_people_subtitle': 'Wähle die Personen aus, an die die Zahlungsanfrage gesendet wird',
      'payment_select_all': 'Alle auswählen',
      'payment_clear_all': 'Abwählen',
      'error_generic_with_details': 'Fehler: {error}',

      // PAYMENTS PAGE
      'payment_delete_title': 'Anfrage löschen',
      'payment_delete_confirm': 'Möchtest du diese Zahlungsanfrage der Gruppe "{groupName}" wirklich löschen?',
      'payment_deleted_success': 'Zahlungsanfrage gelöscht',
      'home_no_payments': 'Keine Zahlungsanfragen',
      'payment_status_pending': 'Ausstehend',
      'payment_status_paid': 'Bezahlt',
      'payment_status_partial': 'Teilweise',
      'payment_default_title': 'Zahlungsanfrage',
      'user': 'Benutzer',

      // PROFILE SETTINGS PAGE
      'image_size_error_settings': 'Bild zu groß für Firestore. Bitte erneut versuchen',
      'toast_photo_error': 'Fehler beim Hochladen des Fotos',
      'toast_save_success': 'Profildaten gespeichert',
      'profile_title': 'Profilverwaltung',
      'profile_change_photo': 'Profilbild ändern',
      'label_name': 'Name',
      'label_day': 'Tag',
      'label_month': 'Monat',
      'label_year': 'Jahr',
      'label_gender': 'Geschlecht',
      'label_sport': 'Ausgeübter Sport',
      'label_role': 'Spielerrolle',
      'button_save': 'Speichern',
      'month_01': 'Januar',
      'month_02': 'Februar',
      'month_03': 'März',
      'month_04': 'April',
      'month_05': 'Mai',
      'month_06': 'Juni',
      'month_07': 'Juli',
      'month_08': 'August',
      'month_09': 'September',
      'month_10': 'Oktober',
      'month_11': 'November',
      'month_12': 'Dezember',
      'gender_male': 'Männlich',
      'gender_female': 'Weiblich',
      'gender_other': 'Andere',
      'logout_button': 'Abmelden',

      // SETTINGS PAGE
      'settings_language_app': 'App-Sprache',
      'language_italian': 'Italienisch',
      'language_english': 'Englisch',
      'language_spanish': 'Spanisch',
      'language_french': 'Französisch',
      'language_german': 'Deutsch',
      'language_portuguese': 'Portugiesisch',
      'language_changed_snackbar': 'Sprache auf {language} eingestellt',
      'settings_title': 'Einstellungen',
      'settings_section_theme': 'Design',
      'settings_change_theme': 'Design ändern',
      'settings_theme_dark_active': 'Dunkles Design ist aktiv',
      'settings_theme_light_active': 'Helles Design ist aktiv',
      'settings_section_account': 'Konto',
      'no_user': 'Kein Benutzer',
      'settings_account_email_subtitle': 'Mit dem Konto verknüpfte E-Mail',
      'settings_section_profile': 'Profil',
      'settings_profile_manage_title': 'Profilverwaltung',
      'settings_profile_manage_subtitle': 'Name, Geburtsdatum, Rolle, Sport bearbeiten...',
      'settings_section_language': 'Sprache',

      // USER PROFILE PAGE
      'profile_not_found': 'Profil nicht gefunden',
      'without_name': 'Ohne Namen',
      'birth_date': 'Geburtsdatum',
    },

    //PORTOGHESE
    'pt': {
      // LOGIN PAGE & REGISTER PAGE
      'push_init_failed': 'Falha na inicialização das notificações',
      'error_login': 'Erro durante o login',
      'error_user_not_found': 'Usuário não encontrado',
      'error_wrong_password': 'Senha incorreta',
      'error_invalid_email': 'E-mail inválido',
      'error_unexpected_login': 'Erro inesperado durante o login',
      'error_google_login': 'Erro ao fazer login com o Google',
      'error_account_exists_different_credential': 'Já existe uma conta com outro método de acesso',
      'error_invalid_google_credential': 'Credenciais do Google inválidas',
      'error_user_disabled': 'Usuário desativado',
      'error_google_login_generic': 'Erro ao entrar com o Google',
      'login_title': 'Bem-vindo de volta!',
      'login_subtitle': 'Faça login para continuar',
      'email_label': 'E-mail',
      'validation_insert_email': 'Insira seu e-mail',
      'validation_email_invalid': 'E-mail inválido',
      'password_label': 'Senha',
      'validation_insert_password': 'Insira sua senha',
      'validation_min_6_chars': 'Mínimo de 6 caracteres',
      'forgot_password': 'Esqueceu a senha?',
      'password_reset_sent': 'E-mail de redefinição enviado',
      'error_password_reset': 'Erro ao redefinir a senha',
      'error_too_many_requests': 'Muitas tentativas. Tente novamente mais tarde',
      'error_unexpected_reset': 'Erro inesperado ao redefinir a senha',
      'login_button': 'Entrar',
      'login_with_google_loading': 'Entrando com Google...',
      'login_with_google': 'Cadastrar com Google',
      'no_account': 'Não tem uma conta?',
      'go_to_register': 'Cadastre-se',

      'registration_success': 'Registro concluído com sucesso.\nBem-vindo ao Grouply',
      'error_register': 'Erro durante o registro',
      'error_email_in_use': 'Este e-mail já está registrado',
      'error_weak_password': 'A senha é muito fraca',
      'error_unexpected_register': 'Erro inesperado durante o registro',
      'error_google_register': 'Erro durante o registro com Google',
      'register_title': 'Criar uma conta',
      'register_subtitle': 'Cadastre-se para começar',
      'go_to_login_button': 'Ir para a página de login',
      'validation_insert_password_register': 'Insira uma senha',
      'validation_confirm_password': 'Confirme a senha',
      'validation_passwords_not_match': 'As senhas não coincidem',
      'register_button': 'Cadastrar',
      'register_with_google_loading': 'Registrando com Google...',
      'register_with_google': 'Cadastrar com Google',
      'have_account': 'Já tem uma conta?',

      // HOME PAGE
      'snack_group_created': 'Grupo criado! Código: {code}',
      'error': 'Erro',
      'error_code_not_found': 'Nenhum grupo encontrado com este código',
      'error_already_member': 'Você já faz parte deste grupo!',
      'snack_join_success': 'Você entrou no grupo {groupName}!',
      'snack_join_error': 'Erro ao entrar: {error}',
      'dialog_join_group_title': 'Entrar em um grupo',
      'label_insert_code': 'Insira o código de convite (6 caracteres)',
      'button_cancel': 'Cancelar',
      'validation_code_length': 'O código deve ter 6 caracteres',
      'button_join': 'Entrar',
      'dialog_create_group_title': 'Criar novo grupo',
      'label_team_name': 'Nome do time (ex. Real Madrid)',
      'label_team_sport': 'Esporte (ex. Futebol)',
      'button_create': 'Criar',
      'home_groups_dialog_title': 'Grupos',
      'home_groups_create': 'Criar novo grupo',
      'home_groups_join': 'Inserir código do grupo',
      'close_button': 'Fechar',
      'home_tab_events': 'Eventos',
      'home_tab_posts': 'Postagens',
      'home_tab_polls': 'Enquetes',
      'home_no_groups': 'Você não está em nenhum grupo. Entre em um para ver os eventos!',
      'home_no_events': 'Nenhum evento programado',
      'post_delete_title': 'Excluir postagem',
      'confirm_post_delete': 'Deseja realmente excluir esta postagem?',
      'post_delete_cancel': 'Cancelar',
      'post_delete_delete': 'Excluir',
      'post_deleted_success': 'Postagem excluída',
      'home_no_posts': 'Nenhuma postagem',
      'home_no_polls': 'Nenhuma enquete ativa',
      'poll_vote_saved': 'Voto salvo',
      'poll_delete_title': 'Excluir enquete',
      'poll_delete_confirm': 'Deseja realmente excluir esta enquete do grupo {groupName}?',
      'button_delete': 'Excluir',
      'poll_deleted_success': 'Enquete excluída',
      'poll_total_votes': '{count} votos',
      'poll_multiple_hint': 'Você pode selecionar várias opções',
      'label_today': 'Hoje',
      'label_tomorrow': 'Amanhã',
      'generic_event': 'Evento',
      'tournament_event': 'Torneio',

      // CREATE EVENT PAGE
      'tournament_min_3': 'Um torneio deve ter pelo menos 3 equipes!',
      'error_missing_fields': 'Preencha todos os campos obrigatórios',
      'event_created_success': 'Evento criado com sucesso!',
      'match_type_home': 'Partida em casa',
      'match_type_away': 'Partida fora de casa',
      'match_type_tournament': 'Torneio',
      'match_type_friendly': 'Amistoso',
      'create_event_title': 'Criar evento',
      'label_match_type': 'Tipo de partida',
      'label_date': 'Data',
      'label_start_time': 'Hora de início',
      'label_match_location': 'Local da partida',
      'map_select_placeholder': 'Selecionar no mapa',
      'label_meeting_point': 'Ponto de encontro',
      'label_meeting_time': 'Horário do encontro',
      'label_home_team': 'Equipe da casa',
      'label_away_team': 'Equipe visitante',
      'label_tournament_teams': 'Equipes participantes',
      'hint_team_n': 'Equipe {number}',
      'btn_add_team': 'Adicionar equipe',

      // CREATE PAYMENT REQUEST PAGE
      'toast_login_required': 'Você precisa estar logado para salvar',
      'payment_admin_only_error': 'Somente o administrador pode criar solicitações de pagamento',
      'payment_no_recipients_error': 'Selecione pelo menos uma pessoa',
      'payment_invalid_amount_error': 'Insira um valor válido',
      'payment_missing_fields_error': 'Preencha todos os campos obrigatórios',
      'payment_request_created_success': 'Solicitação criada com sucesso!',
      'payment_pick_date': 'Escolher data',
      'payment_create_title': 'Solicitação de pagamento',
      'payment_recipients_label': 'Destinatários',
      'payment_amount_label': 'Valor',
      'payment_amount_hint': 'Ex. 10,00',
      'payment_note_label': 'Descrição',
      'payment_note_hint': 'Ex. Mensalidade / Campo / Uniformes...',
      'payment_due_date_label': 'Data de vencimento (opcional)',
      'payment_creating': 'Enviando...',
      'payment_send_request': 'Enviar solicitação',

      // CREATE POLL PAGE
      'poll_missing_fields_error': 'Preencha a pergunta e as opções',
      'poll_min_options_error': 'Insira pelo menos 2 opções',
      'poll_created_success': 'Enquete criada com sucesso!',
      'create_poll_title': 'Criar uma enquete',
      'poll_question_label': 'Pergunta',
      'poll_question_hint': 'Ex. Quem vem ao treino?',
      'poll_allow_multiple': 'Permitir seleções múltiplas',
      'poll_option_label': 'Opção {number}',
      'poll_remove_option': 'Remover',
      'poll_add_option': 'Adicionar opção',
      'poll_creating': 'Criando enquete...',
      'poll_publish': 'Publicar enquete',

      // CREATE POST PAGE
      'image_size_error': 'Imagem muito grande! Tente uma menor ou faça uma captura de tela',
      'file_size_error': 'Arquivo muito grande para o Firestore (limite de 1MB)',
      'post_created_success': 'Publicação criada com sucesso!',
      'error_save': 'Erro ao salvar',
      'error_post_size_limit': 'Limite excedido! A publicação (texto + imagens) ultrapassa 1MB',
      'create_post_title': 'Criar uma publicação',
      'label_publish_in': 'Publicar em:',
      'label_post_title': 'Título da publicação',
      'label_post_description': 'Descrição',
      'btn_add_media': 'Foto/Vídeo',
      'btn_add_attachment': 'Anexo',
      'btn_publish': 'Publicar',

      // CREATE RECURRING EVENT PAGE
      'default_event_training': 'Treino',
      'recurrence_daily': 'Todos os dias',
      'recurrence_weekly': 'Toda semana',
      'recurrence_monthly': 'Todo mês',
      'create_recurring_event_title': 'Criar evento recorrente',
      'label_event_name': 'Nome do evento',
      'label_location': 'Local',
      'label_recurrence': 'Recorrência',
      'recurrence_info': 'Eventos serão gerados para os próximos 3 meses.',

      // EVENT DETAILS PAGE
      'delete_event_title': 'Excluir evento',
      'delete_event_confirm': 'Tem certeza de que deseja excluir este evento? Esta ação é irreversível.',
      'event_not_found': 'Evento não encontrado',
      'event_details_title': 'Detalhes do evento',
      'status_title': 'Sua presença',
      'btn_decline': 'Não estarei presente',
      'btn_accept': 'Estarei presente',
      'status_going': 'Presente',
      'status_not_going': 'Ausente',
      'status_pending': 'Pendente',

      // EVENT TYPE SELECTOR PAGE
      'event_select_type_title': 'Selecionar tipo',
      'event_type_single': 'Evento',
      'event_type_single_sub': 'Convide pessoas para partidas, torneios ou outros eventos sociais',
      'event_type_recurring': 'Evento recorrente',
      'event_type_recurring_sub': 'Convide pessoas para treinos ou outros eventos',

      // GROUP CHAT PAGE
      'chat_send_error': 'Erro ao enviar: {error}',
      'chat_empty': 'Nenhuma mensagem. Escreva a primeira!',
      'chat_hint': 'Escreva uma mensagem...',

      // GROUP DASHBOARD PAGE
      'admin_only_delete': 'Somente o administrador pode excluir conteúdo',
      'delete_post_title': 'Excluir publicações',
      'delete_post_confirm': 'Deseja excluir as {count} publicações selecionadas?',
      'elements_deleted': '{count} elementos excluídos',
      'fab_option_event': 'Evento',
      'fab_option_post': 'Publicação',
      'fab_option_post_sub': 'Compartilhe informações, fotos e arquivos',
      'fab_option_poll': 'Enquete',
      'fab_option_poll_sub': 'Pergunte a opinião dos membros',
      'fab_option_payment': 'Solicitações de pagamento',
      'fab_option_payment_sub': 'Cobrar contribuições dos membros',
      'dialog_leave_title': 'Deseja sair do grupo?',
      'dialog_leave_content': 'Você não verá mais este grupo na sua lista',
      'info_leave_group': 'Sair do grupo',
      'leave_success': 'Você saiu do grupo com sucesso.',
      'leave_error': 'Erro ao sair: {error}',
      'items_selected': '{count} selecionados',
      'tab_board': 'Mural',
      'tab_members': 'Membros',
      'tab_info': 'Info',
      'home_upcoming_events': 'Próximos eventos',
      'location_not_specified': 'Local não especificado',
      'team_generic': 'Equipe',
      'without_title': 'Sem título',
      'info_invite_code_label': 'Código de convite',
      'info_code_copied': 'Código copiado para a área de transferência',
      'info_sport': 'Esporte',
      'loading': 'Carregando...',

      // GROUP PAGE
      'login_error_group': 'Faça login para ver os grupos',
      'group_empty_title': 'Nenhum grupo',
      'group_empty_subtitle': 'Você ainda não faz parte de nenhum grupo.\nCrie um ou entre em um existente!',
      'group': 'Grupo',
      'group_members_count': '{count} membros',

      // LOCATION PICKER PAGE
      'touch_map': 'Toque no mapa ou procure um endereço',
      'location_not_found_query': 'Nenhum local encontrado para "{query}"',
      'server_error': 'Erro do servidor',
      'connection_error': 'Erro de conexão. Verifique sua internet',
      'searching_address': 'Buscando endereço...',
      'unknown_address': 'Endereço desconhecido',
      'address_not_found': 'Endereço não encontrado',
      'hint_location': 'Buscar cidade ou rua...',
      'searching': 'Buscando...',
      'confirm_position': 'CONFIRMAR POSIÇÃO',

      // MEMBER LIST PAGE
      'members_error': 'Não foi possível carregar os membros',
      'no_members': 'Nenhum membro no grupo',
      'members_list_title': 'Membros da equipe',
      'unknown_user': 'Usuário desconhecido',
      'you': ' (Você)',
      'member_admin_badge': 'Admin',

      // MESSAGES PAGE
      'messages_empty_title': 'Nenhuma conversa',
      'messages_empty_subtitle': 'Entre em um grupo para começar a conversar.',
      'chat_no_messages_yet': 'Nenhuma mensagem ainda',
      'chat_message_deleted_or_empty': '(mensagem vazia)',

      // PAYMENTS SELECT RECIPIENTS PAGE
      'payment_select_people_title': 'Selecionar membros',
      'payment_select_people_subtitle': 'Escolha as pessoas para enviar a solicitação de pagamento',
      'payment_select_all': 'Selecionar todos',
      'payment_clear_all': 'Desmarcar',
      'error_generic_with_details': 'Erro: {error}',

      // PAYMENTS PAGE
      'payment_delete_title': 'Excluir solicitação',
      'payment_delete_confirm': 'Deseja realmente excluir esta solicitação de pagamento do grupo "{groupName}"?',
      'payment_deleted_success': 'Solicitação de pagamento excluída',
      'home_no_payments': 'Nenhuma solicitação de pagamento',
      'payment_status_pending': 'Pendente',
      'payment_status_paid': 'Pago',
      'payment_status_partial': 'Parcial',
      'payment_default_title': 'Solicitação de pagamento',
      'user': 'Usuário',

      // PROFILE SETTINGS PAGE
      'image_size_error_settings': 'Imagem muito grande para o Firestore. Tente novamente',
      'toast_photo_error': 'Erro ao carregar a foto',
      'toast_save_success': 'Dados do perfil salvos',
      'profile_title': 'Gerenciamento do perfil',
      'profile_change_photo': 'Alterar foto do perfil',
      'label_name': 'Nome',
      'label_day': 'Dia',
      'label_month': 'Mês',
      'label_year': 'Ano',
      'label_gender': 'Gênero',
      'label_sport': 'Esporte praticado',
      'label_role': 'Função do jogador',
      'button_save': 'Salvar',
      'month_01': 'Janeiro',
      'month_02': 'Fevereiro',
      'month_03': 'Março',
      'month_04': 'Abril',
      'month_05': 'Maio',
      'month_06': 'Junho',
      'month_07': 'Julho',
      'month_08': 'Agosto',
      'month_09': 'Setembro',
      'month_10': 'Outubro',
      'month_11': 'Novembro',
      'month_12': 'Dezembro',
      'gender_male': 'Masculino',
      'gender_female': 'Feminino',
      'gender_other': 'Outro',
      'logout_button': 'Sair',

      // SETTINGS PAGE
      'settings_language_app': 'Idioma do aplicativo',
      'language_italian': 'Italiano',
      'language_english': 'Inglês',
      'language_spanish': 'Espanhol',
      'language_french': 'Francês',
      'language_german': 'Alemão',
      'language_portuguese': 'Português',
      'language_changed_snackbar': 'Idioma definido para {language}',
      'settings_title': 'Configurações',
      'settings_section_theme': 'Tema',
      'settings_change_theme': 'Alterar tema',
      'settings_theme_dark_active': 'O tema escuro está ativo',
      'settings_theme_light_active': 'O tema claro está ativo',
      'settings_section_account': 'Conta',
      'no_user': 'Nenhum usuário',
      'settings_account_email_subtitle': 'E-mail vinculado à conta',
      'settings_section_profile': 'Perfil',
      'settings_profile_manage_title': 'Gerenciamento do perfil',
      'settings_profile_manage_subtitle': 'Editar nome, data de nascimento, função, esporte...',
      'settings_section_language': 'Idioma',

      // USER PROFILE PAGE
      'profile_not_found': 'Perfil não encontrado',
      'without_name': 'Sem nome',
      'birth_date': 'Data de nascimento',
    },
  };

  //SELEZIONA LA LINGUA LOCALE E SE NON É SUPPORTATA FA IL FALLBACK IN INGLESE PER EVITARE CRASH
  String t(String key, {Map<String, String>? params}) {
    final langCode = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';

    String value =
        _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;

    //SOSTITUZIONE DEI PARAMETRI DINAMICI
    if (params != null) {
      params.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }

    return value;
  }
}

//AGGIORNA LE TRADUZIONI CON I LCAMBIO DI LINGUA
class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['it', 'en', 'es', 'fr', 'de', 'pt'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}