import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = <String, Map<String, String>>{
    // 🇮🇹 ITALIANO
    'it': {
      'app_title': 'Grouply - Team Manager',
      // Login
      'login_title': 'Bentornato!',
      'login_subtitle': 'Accedi per continuare',
      'email_label': 'Email',
      'password_label': 'Password',
      'forgot_password': 'Password dimenticata?',
      'login_button': 'Accedi',
      'login_with_google': 'Accedi con Google',
      'no_account': 'Non hai un account?',
      'go_to_register': 'Registrati',
      'or_label': 'oppure',
      'google_signin_loading': 'Accesso con Google...',
      'google_signup_loading': 'Registrazione con Google...',
      // Register
      'register_title': 'Crea un account',
      'register_subtitle': 'Registrati per iniziare',
      'confirm_password_label': 'Conferma password',
      'register_button': 'Registrati',
      'register_with_google': 'Registrati con Google',
      'registration_success': 'Registrazione avvenuta con successo.\nTi diamo il benvenuto in Grouply',
      'go_to_login_button': 'Vai alla pagina di login',
      'have_account': 'Hai già un account?',
      // Home
      'home_title': 'Home',
      'home_message': 'Benvenuto nella Home di Grouply',
      'close_button': 'Chiudi',
      'home_groups_dialog_title': 'Gruppi',
      'home_groups_create': 'Crea nuovo gruppo',
      'home_groups_join': 'Inserisci codice gruppo',
      'home_groups_create_snackbar': 'Funzione "Crea nuovo gruppo" in sviluppo',
      'home_groups_join_snackbar': 'Funzione "Inserisci codice gruppo" in sviluppo',
      'dialog_create_group_title': 'Crea Nuovo Gruppo',
      'label_team_name': 'Nome del Team (es. Real Madrid)',
      'label_team_sport': 'Sport (es. Calcio)',
      'button_cancel': 'Annulla',
      'button_create': 'Crea',
      'snack_group_created': 'Gruppo creato! Codice: {code}',
      'snack_create_error': 'Errore creazione gruppo: {error}',
      'group_placeholder': 'Sezione Gruppo',
      'group_empty_title': 'Nessun gruppo',
      'group_empty_subtitle': 'Non fai ancora parte di nessun team.\nCrea un gruppo o unisciti a uno esistente!',
      'group_members_count': '{count} membri',
      // Dashboard
      'tab_board': 'Bacheca',
      'tab_members': 'Membri',
      'tab_info': 'Info',
      'info_invite_code_label': 'Codice Invito',
      'info_copy_code': 'Copia codice',
      'info_code_copied': 'Codice copiato negli appunti',
      'info_sport': 'Sport',
      'board_empty': 'Nessun avviso in bacheca',
      'members_list_title': 'Membri del team',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Esci dal gruppo',
      'dialog_leave_title': 'Vuoi uscire dal gruppo?',
      'dialog_leave_content': 'Non vedrai più questo gruppo nella tua lista.',
      'leave_success': 'Sei uscito dal gruppo correttamente.',
      'leave_error': 'Errore durante l\'uscita: {error}',
      'messages_placeholder': 'Sezione Messaggi\n(qui vedrai le tue chat)',
      'payments_placeholder': 'Sezione Pagamenti\n(qui gestirai abbonamenti, quote, ecc.)',
      // Profile
      'profile_title': 'Gestione Profilo',
      'profile_change_photo': 'Cambia foto profilo',
      'label_name': 'Nome',
      'label_day': 'Giorno',
      'label_month': 'Mese',
      'label_year': 'Anno',
      'label_gender': 'Genere',
      'label_sport': 'Sport praticato',
      'label_role': 'Ruolo del giocatore',
      'button_save': 'Salva',
      'toast_save_success': 'Dati profilo salvati',
      'toast_login_required': 'Devi essere loggato per salvare',
      'toast_photo_error': 'Errore durante il caricamento della foto',
      // Settings
      'settings_title': 'Impostazioni',
      'settings_section_theme': 'Tema',
      'settings_change_theme': 'Cambia tema',
      'settings_theme_dark_active': 'Il tema scuro è attivo',
      'settings_theme_light_active': 'Il tema chiaro è attivo',
      'settings_section_account': 'Account',
      'settings_section_profile': 'Profilo',
      'settings_profile_manage_title': 'Gestione profilo',
      'settings_profile_manage_subtitle': 'Modifica nome, nascita, ruolo, sport...',
      'settings_section_language': 'Lingua',
      'settings_language_app': 'Lingua dell\'app',
      'settings_language_select_title': 'Seleziona lingua',
      'settings_account_email_subtitle': 'Email collegata all\'account',
      'language_italian': 'Italiano',
      'language_english': 'Inglese',
      'language_spanish': 'Spagnolo',
      'language_french': 'Francese',
      'language_german': 'Tedesco',
      'language_portuguese': 'Portoghese',
      'language_changed_snackbar': 'Lingua impostata su {language}',
      'logout_button': 'Esci',
      // Errors
      'validation_insert_email': 'Inserisci la tua email',
      'validation_email_invalid': 'Email non valida',
      'validation_insert_password': 'Inserisci la password',
      'validation_insert_password_register': 'Inserisci una password',
      'validation_min_6_chars': 'Minimo 6 caratteri',
      'validation_confirm_password': 'Conferma la password',
      'validation_passwords_not_match': 'Le password non coincidono',
      'error_login': 'Errore durante il login',
      'error_register': 'Errore durante la registrazione',
      'error_unexpected_login': 'Errore imprevisto durante il login',
      'error_unexpected_register': 'Errore imprevisto durante la registrazione',
      'error_user_not_found': 'Utente non trovato',
      'error_wrong_password': 'Password errata',
      'error_invalid_email': 'Email non valida',
      'error_email_in_use': 'Questa email è già registrata',
      'error_weak_password': 'La password è troppo debole',
    },

    // 🇺🇸 ENGLISH
    'en': {
      'app_title': 'Grouply - Team Manager',
      'login_title': 'Welcome back!',
      'login_subtitle': 'Sign in to continue',
      'email_label': 'Email',
      'password_label': 'Password',
      'forgot_password': 'Forgot password?',
      'login_button': 'Sign in',
      'login_with_google': 'Sign in with Google',
      'no_account': 'Don\'t have an account?',
      'go_to_register': 'Register',
      'or_label': 'or',
      'google_signin_loading': 'Signing in with Google...',
      'google_signup_loading': 'Signing up with Google...',
      'register_title': 'Create an account',
      'register_subtitle': 'Sign up to get started',
      'confirm_password_label': 'Confirm password',
      'register_button': 'Sign up',
      'register_with_google': 'Sign up with Google',
      'registration_success': 'Registration successful.\nWelcome to Grouply',
      'go_to_login_button': 'Go to login page',
      'have_account': 'Already have an account?',
      'home_title': 'Home',
      'home_message': 'Welcome to Grouply Home',
      'close_button': 'Close',
      'home_groups_dialog_title': 'Groups',
      'home_groups_create': 'Create new group',
      'home_groups_join': 'Join existing group',
      'home_groups_create_snackbar': '“Create new group” feature under development',
      'home_groups_join_snackbar': '“Enter group code” feature under development',
      'dialog_create_group_title': 'Create New Group',
      'label_team_name': 'Team Name (e.g. Real Madrid)',
      'label_team_sport': 'Sport (e.g. Soccer)',
      'button_cancel': 'Cancel',
      'button_create': 'Create',
      'snack_group_created': 'Group created! Code: {code}',
      'snack_create_error': 'Error creating group: {error}',
      'group_placeholder': 'Group Section',
      'group_empty_title': 'No groups',
      'group_empty_subtitle': 'You are not part of any team yet.\nCreate a group or join an existing one!',
      'group_members_count': '{count} members',
      'tab_board': 'Board',
      'tab_members': 'Members',
      'tab_info': 'Info',
      'info_invite_code_label': 'Invite Code',
      'info_copy_code': 'Copy code',
      'info_code_copied': 'Code copied to clipboard',
      'info_sport': 'Sport',
      'board_empty': 'No posts on the board',
      'members_list_title': 'Team members',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Leave group',
      'dialog_leave_title': 'Leave group?',
      'dialog_leave_content': 'You will no longer see this group in your list.',
      'leave_success': 'You left the group.',
      'leave_error': 'Error leaving group: {error}',
      'messages_placeholder': 'Messages Section\n(view your chats here)',
      'payments_placeholder': 'Payments Section\n(manage subscriptions, fees, etc.)',
      'profile_title': 'Profile Management',
      'profile_change_photo': 'Change profile photo',
      'label_name': 'Name',
      'label_day': 'Day',
      'label_month': 'Month',
      'label_year': 'Year',
      'label_gender': 'Gender',
      'label_sport': 'Sport played',
      'label_role': 'Player role',
      'button_save': 'Save',
      'toast_save_success': 'Profile data saved',
      'toast_login_required': 'You must be logged in to save',
      'toast_photo_error': 'Error uploading photo',
      'settings_title': 'Settings',
      'settings_section_theme': 'Theme',
      'settings_change_theme': 'Change theme',
      'settings_theme_dark_active': 'Dark theme is active',
      'settings_theme_light_active': 'Light theme is active',
      'settings_section_account': 'Account',
      'settings_section_profile': 'Profile',
      'settings_profile_manage_title': 'Manage profile',
      'settings_profile_manage_subtitle': 'Edit name, birthday, role, sport...',
      'settings_section_language': 'Language',
      'settings_language_app': 'App language',
      'settings_language_select_title': 'Select language',
      'settings_account_email_subtitle': 'Email linked to the account',
      'language_italian': 'Italian',
      'language_english': 'English',
      'language_spanish': 'Spanish',
      'language_french': 'French',
      'language_german': 'German',
      'language_portuguese': 'Portuguese',
      'language_changed_snackbar': 'Language set to {language}',
      'logout_button': 'Logout',
      'validation_insert_email': 'Enter your email',
      'validation_email_invalid': 'Invalid email',
      'validation_insert_password': 'Enter your password',
      'validation_insert_password_register': 'Enter a password',
      'validation_min_6_chars': 'Minimum 6 characters',
      'validation_confirm_password': 'Confirm your password',
      'validation_passwords_not_match': 'Passwords do not match',
      'error_login': 'Error during login',
      'error_register': 'Error during registration',
      'error_unexpected_login': 'Unexpected error during login',
      'error_unexpected_register': 'Unexpected error during registration',
      'error_user_not_found': 'User not found',
      'error_wrong_password': 'Wrong password',
      'error_invalid_email': 'Invalid email',
      'error_email_in_use': 'This email is already registered',
      'error_weak_password': 'Password is too weak',
    },

    // 🇪🇸 SPANISH
    'es': {
      'app_title': 'Grouply - Team Manager',
      'login_title': '¡Bienvenido de nuevo!',
      'login_subtitle': 'Inicia sesión para continuar',
      'email_label': 'Correo electrónico',
      'password_label': 'Contraseña',
      'forgot_password': '¿Olvidaste la contraseña?',
      'login_button': 'Iniciar sesión',
      'login_with_google': 'Iniciar con Google',
      'no_account': '¿No tienes una cuenta?',
      'go_to_register': 'Regístrate',
      'or_label': 'o',
      'google_signin_loading': 'Iniciando con Google...',
      'google_signup_loading': 'Registrando con Google...',
      'register_title': 'Crea una cuenta',
      'register_subtitle': 'Regístrate para empezar',
      'confirm_password_label': 'Confirmar contraseña',
      'register_button': 'Registrarse',
      'register_with_google': 'Registrarse con Google',
      'registration_success': 'Registro exitoso.\nBienvenido a Grouply',
      'go_to_login_button': 'Ir a la página de inicio de sesión',
      'have_account': '¿Ya tienes una cuenta?',
      'home_title': 'Inicio',
      'home_message': 'Bienvenido al inicio de Grouply',
      'close_button': 'Cerrar',
      'home_groups_dialog_title': 'Grupos',
      'home_groups_create': 'Crear nuevo grupo',
      'home_groups_join': 'Unirse a un grupo',
      'home_groups_create_snackbar': 'Función "Crear nuevo grupo" en desarrollo',
      'home_groups_join_snackbar': 'Función "Introducir código" en desarrollo',
      'dialog_create_group_title': 'Crear Nuevo Grupo',
      'label_team_name': 'Nombre del Equipo (ej. Real Madrid)',
      'label_team_sport': 'Deporte (ej. Fútbol)',
      'button_cancel': 'Cancelar',
      'button_create': 'Crear',
      'snack_group_created': '¡Grupo creado! Código: {code}',
      'snack_create_error': 'Error al crear grupo: {error}',
      'group_placeholder': 'Sección de Grupos',
      'group_empty_title': 'Sin grupos',
      'group_empty_subtitle': 'Aún no eres parte de ningún equipo.\n¡Crea un grupo o únete a uno existente!',
      'group_members_count': '{count} miembros',
      'tab_board': 'Tablón',
      'tab_members': 'Miembros',
      'tab_info': 'Info',
      'info_invite_code_label': 'Código de invitación',
      'info_copy_code': 'Copiar código',
      'info_code_copied': 'Código copiado al portapapeles',
      'info_sport': 'Deporte',
      'board_empty': 'No hay avisos en el tablón',
      'members_list_title': 'Miembros del equipo',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Salir del grupo',
      'dialog_leave_title': '¿Salir del grupo?',
      'dialog_leave_content': 'Ya no verás este grupo en tu lista.',
      'leave_success': 'Has salido del grupo.',
      'leave_error': 'Error al salir: {error}',
      'messages_placeholder': 'Sección de Mensajes\n(aquí verás tus chats)',
      'payments_placeholder': 'Sección de Pagos\n(gestiona suscripciones, cuotas, etc.)',
      'profile_title': 'Gestión del Perfil',
      'profile_change_photo': 'Cambiar foto de perfil',
      'label_name': 'Nombre',
      'label_day': 'Día',
      'label_month': 'Mes',
      'label_year': 'Año',
      'label_gender': 'Género',
      'label_sport': 'Deporte practicado',
      'label_role': 'Rol del jugador',
      'button_save': 'Guardar',
      'toast_save_success': 'Datos del perfil guardados',
      'toast_login_required': 'Debes iniciar sesión para guardar',
      'toast_photo_error': 'Error al cargar la foto',
      'settings_title': 'Ajustes',
      'settings_section_theme': 'Tema',
      'settings_change_theme': 'Cambiar tema',
      'settings_theme_dark_active': 'El tema oscuro está activo',
      'settings_theme_light_active': 'El tema claro está activo',
      'settings_section_account': 'Cuenta',
      'settings_section_profile': 'Perfil',
      'settings_profile_manage_title': 'Gestión del perfil',
      'settings_profile_manage_subtitle': 'Modificar nombre, fecha de nacimiento, rol, deporte...',
      'settings_section_language': 'Idioma',
      'settings_language_app': 'Idioma de la app',
      'settings_language_select_title': 'Selecciona el idioma',
      'settings_account_email_subtitle': 'Correo vinculado a la cuenta',
      'language_italian': 'Italiano',
      'language_english': 'Inglés',
      'language_spanish': 'Español',
      'language_french': 'Francés',
      'language_german': 'Alemán',
      'language_portuguese': 'Portugués',
      'language_changed_snackbar': 'Idioma establecido en {language}',
      'logout_button': 'Salir',
      'validation_insert_email': 'Introduce tu correo',
      'validation_email_invalid': 'Correo inválido',
      'validation_insert_password': 'Introduce la contraseña',
      'validation_insert_password_register': 'Introduce una contraseña',
      'validation_min_6_chars': 'Mínimo 6 caracteres',
      'validation_confirm_password': 'Confirma la contraseña',
      'validation_passwords_not_match': 'Las contraseñas no coinciden',
      'error_login': 'Error durante el inicio de sesión',
      'error_register': 'Error durante el registro',
      'error_unexpected_login': 'Error inesperado durante el inicio',
      'error_unexpected_register': 'Error inesperado durante el registro',
      'error_user_not_found': 'Usuario no encontrado',
      'error_wrong_password': 'Contraseña incorrecta',
      'error_invalid_email': 'Correo inválido',
      'error_email_in_use': 'Este correo ya está registrado',
      'error_weak_password': 'La contraseña es demasiado débil',
    },

    // 🇫🇷 FRENCH
    'fr': {
      'app_title': 'Grouply - Gestion d\'équipe',
      'login_title': 'Bon retour !',
      'login_subtitle': 'Connectez-vous pour continuer',
      'email_label': 'Email',
      'password_label': 'Mot de passe',
      'forgot_password': 'Mot de passe oublié ?',
      'login_button': 'Se connecter',
      'login_with_google': 'Continuer avec Google',
      'no_account': 'Pas encore de compte ?',
      'go_to_register': 'S\'inscrire',
      'or_label': 'ou',
      'google_signin_loading': 'Connexion avec Google...',
      'google_signup_loading': 'Inscription avec Google...',
      'register_title': 'Créer un compte',
      'register_subtitle': 'Inscrivez-vous pour commencer',
      'confirm_password_label': 'Confirmer le mot de passe',
      'register_button': 'S\'inscrire',
      'register_with_google': 'S\'inscrire avec Google',
      'registration_success': 'Inscription réussie.\nBienvenue sur Grouply',
      'go_to_login_button': 'Aller à la page de connexion',
      'have_account': 'Déjà un compte ?',
      'home_title': 'Accueil',
      'home_message': 'Bienvenue sur l\'accueil de Grouply',
      'close_button': 'Fermer',
      'home_groups_dialog_title': 'Groupes',
      'home_groups_create': 'Créer un nouveau groupe',
      'home_groups_join': 'Rejoindre un groupe',
      'home_groups_create_snackbar': 'Fonctionnalité "Créer groupe" en développement',
      'home_groups_join_snackbar': 'Fonctionnalité "Code groupe" en développement',
      'dialog_create_group_title': 'Créer un nouveau groupe',
      'label_team_name': 'Nom de l\'équipe (ex. PSG)',
      'label_team_sport': 'Sport (ex. Football)',
      'button_cancel': 'Annuler',
      'button_create': 'Créer',
      'snack_group_created': 'Groupe créé ! Code : {code}',
      'snack_create_error': 'Erreur lors de la création : {error}',
      'group_placeholder': 'Section Groupes',
      'group_empty_title': 'Aucun groupe',
      'group_empty_subtitle': 'Vous ne faites partie d\'aucune équipe.\nCréez un groupe ou rejoignez-en un !',
      'group_members_count': '{count} membres',
      'tab_board': 'Tableau',
      'tab_members': 'Membres',
      'tab_info': 'Infos',
      'info_invite_code_label': 'Code d\'invitation',
      'info_copy_code': 'Copier le code',
      'info_code_copied': 'Code copié dans le presse-papiers',
      'info_sport': 'Sport',
      'board_empty': 'Aucune annonce sur le tableau',
      'members_list_title': 'Membres de l\'équipe',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Quitter le groupe',
      'dialog_leave_title': 'Quitter le groupe ?',
      'dialog_leave_content': 'Vous ne verrez plus ce groupe dans votre liste.',
      'leave_success': 'Vous avez quitté le groupe.',
      'leave_error': 'Erreur lors de la sortie : {error}',
      'messages_placeholder': 'Section Messages\n(vos discussions ici)',
      'payments_placeholder': 'Section Paiements\n(abonnements, cotisations, etc.)',
      'profile_title': 'Gestion du Profil',
      'profile_change_photo': 'Changer la photo de profil',
      'label_name': 'Nom',
      'label_day': 'Jour',
      'label_month': 'Mois',
      'label_year': 'Année',
      'label_gender': 'Genre',
      'label_sport': 'Sport pratiqué',
      'label_role': 'Rôle du joueur',
      'button_save': 'Enregistrer',
      'toast_save_success': 'Profil enregistré',
      'toast_login_required': 'Connectez-vous pour enregistrer',
      'toast_photo_error': 'Erreur lors du chargement de la photo',
      'settings_title': 'Paramètres',
      'settings_section_theme': 'Thème',
      'settings_change_theme': 'Changer de thème',
      'settings_theme_dark_active': 'Thème sombre actif',
      'settings_theme_light_active': 'Thème clair actif',
      'settings_section_account': 'Compte',
      'settings_section_profile': 'Profil',
      'settings_profile_manage_title': 'Gérer le profil',
      'settings_profile_manage_subtitle': 'Modifier nom, naissance, rôle, sport...',
      'settings_section_language': 'Langue',
      'settings_language_app': 'Langue de l\'application',
      'settings_language_select_title': 'Sélectionner la langue',
      'settings_account_email_subtitle': 'Email lié au compte',
      'language_italian': 'Italien',
      'language_english': 'Anglais',
      'language_spanish': 'Espagnol',
      'language_french': 'Français',
      'language_german': 'Allemand',
      'language_portuguese': 'Portugais',
      'language_changed_snackbar': 'Langue définie sur {language}',
      'logout_button': 'Se déconnecter',
      'validation_insert_email': 'Entrez votre email',
      'validation_email_invalid': 'Email invalide',
      'validation_insert_password': 'Entrez votre mot de passe',
      'validation_insert_password_register': 'Entrez un mot de passe',
      'validation_min_6_chars': 'Minimum 6 caractères',
      'validation_confirm_password': 'Confirmez le mot de passe',
      'validation_passwords_not_match': 'Les mots de passe ne correspondent pas',
      'error_login': 'Erreur de connexion',
      'error_register': 'Erreur d\'inscription',
      'error_unexpected_login': 'Erreur inattendue de connexion',
      'error_unexpected_register': 'Erreur inattendue d\'inscription',
      'error_user_not_found': 'Utilisateur non trouvé',
      'error_wrong_password': 'Mot de passe incorrect',
      'error_invalid_email': 'Email invalide',
      'error_email_in_use': 'Cet email est déjà enregistré',
      'error_weak_password': 'Mot de passe trop faible',
    },

    // 🇩🇪 GERMAN
    'de': {
      'app_title': 'Grouply - Team Manager',
      'login_title': 'Willkommen zurück!',
      'login_subtitle': 'Anmelden um fortzufahren',
      'email_label': 'E-Mail',
      'password_label': 'Passwort',
      'forgot_password': 'Passwort vergessen?',
      'login_button': 'Anmelden',
      'login_with_google': 'Mit Google anmelden',
      'no_account': 'Kein Konto?',
      'go_to_register': 'Registrieren',
      'or_label': 'oder',
      'google_signin_loading': 'Anmeldung mit Google...',
      'google_signup_loading': 'Registrierung mit Google...',
      'register_title': 'Konto erstellen',
      'register_subtitle': 'Registrieren um zu beginnen',
      'confirm_password_label': 'Passwort bestätigen',
      'register_button': 'Registrieren',
      'register_with_google': 'Mit Google registrieren',
      'registration_success': 'Registrierung erfolgreich.\nWillkommen bei Grouply',
      'go_to_login_button': 'Zur Login-Seite',
      'have_account': 'Bereits ein Konto?',
      'home_title': 'Startseite',
      'home_message': 'Willkommen bei Grouply Home',
      'close_button': 'Schließen',
      'home_groups_dialog_title': 'Gruppen',
      'home_groups_create': 'Neue Gruppe erstellen',
      'home_groups_join': 'Gruppe beitreten',
      'home_groups_create_snackbar': 'Funktion "Gruppe erstellen" in Entwicklung',
      'home_groups_join_snackbar': 'Funktion "Code eingeben" in Entwicklung',
      'dialog_create_group_title': 'Neue Gruppe erstellen',
      'label_team_name': 'Teamname (z.B. Bayern München)',
      'label_team_sport': 'Sportart (z.B. Fußball)',
      'button_cancel': 'Abbrechen',
      'button_create': 'Erstellen',
      'snack_group_created': 'Gruppe erstellt! Code: {code}',
      'snack_create_error': 'Fehler beim Erstellen: {error}',
      'group_placeholder': 'Gruppenbereich',
      'group_empty_title': 'Keine Gruppen',
      'group_empty_subtitle': 'Du bist noch in keinem Team.\nErstelle eine Gruppe oder tritt einer bei!',
      'group_members_count': '{count} Mitglieder',
      'tab_board': 'Pinnwand',
      'tab_members': 'Mitglieder',
      'tab_info': 'Info',
      'info_invite_code_label': 'Einladungscode',
      'info_copy_code': 'Code kopieren',
      'info_code_copied': 'Code in die Zwischenablage kopiert',
      'info_sport': 'Sportart',
      'board_empty': 'Keine Beiträge auf der Pinnwand',
      'members_list_title': 'Teammitglieder',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Gruppe verlassen',
      'dialog_leave_title': 'Gruppe verlassen?',
      'dialog_leave_content': 'Du wirst diese Gruppe nicht mehr in deiner Liste sehen.',
      'leave_success': 'Du hast die Gruppe verlassen.',
      'leave_error': 'Fehler beim Verlassen: {error}',
      'messages_placeholder': 'Nachrichtenbereich\n(hier siehst du deine Chats)',
      'payments_placeholder': 'Zahlungsbereich\n(Abos, Gebühren verwalten)',
      'profile_title': 'Profilverwaltung',
      'profile_change_photo': 'Profilbild ändern',
      'label_name': 'Name',
      'label_day': 'Tag',
      'label_month': 'Monat',
      'label_year': 'Jahr',
      'label_gender': 'Geschlecht',
      'label_sport': 'Sportart',
      'label_role': 'Spielerrolle',
      'button_save': 'Speichern',
      'toast_save_success': 'Profil gespeichert',
      'toast_login_required': 'Bitte anmelden zum Speichern',
      'toast_photo_error': 'Fehler beim Hochladen des Fotos',
      'settings_title': 'Einstellungen',
      'settings_section_theme': 'Design',
      'settings_change_theme': 'Design ändern',
      'settings_theme_dark_active': 'Dunkles Design aktiv',
      'settings_theme_light_active': 'Helles Design aktiv',
      'settings_section_account': 'Konto',
      'settings_section_profile': 'Profil',
      'settings_profile_manage_title': 'Profil verwalten',
      'settings_profile_manage_subtitle': 'Name, Geburtsdatum, Rolle bearbeiten...',
      'settings_section_language': 'Sprache',
      'settings_language_app': 'App-Sprache',
      'settings_language_select_title': 'Sprache wählen',
      'settings_account_email_subtitle': 'Verknüpfte E-Mail',
      'language_italian': 'Italienisch',
      'language_english': 'Englisch',
      'language_spanish': 'Spanisch',
      'language_french': 'Französisch',
      'language_german': 'Deutsch',
      'language_portuguese': 'Portugiesisch',
      'language_changed_snackbar': 'Sprache geändert auf {language}',
      'logout_button': 'Abmelden',
      'validation_insert_email': 'Gib deine E-Mail ein',
      'validation_email_invalid': 'Ungültige E-Mail',
      'validation_insert_password': 'Gib dein Passwort ein',
      'validation_insert_password_register': 'Wähle ein Passwort',
      'validation_min_6_chars': 'Mindestens 6 Zeichen',
      'validation_confirm_password': 'Passwort bestätigen',
      'validation_passwords_not_match': 'Passwörter stimmen nicht überein',
      'error_login': 'Fehler bei der Anmeldung',
      'error_register': 'Fehler bei der Registrierung',
      'error_unexpected_login': 'Unerwarteter Fehler bei der Anmeldung',
      'error_unexpected_register': 'Unerwarteter Fehler bei der Registrierung',
      'error_user_not_found': 'Benutzer nicht gefunden',
      'error_wrong_password': 'Falsches Passwort',
      'error_invalid_email': 'Ungültige E-Mail',
      'error_email_in_use': 'Diese E-Mail ist bereits registriert',
      'error_weak_password': 'Passwort ist zu schwach',
    },

    // 🇧🇷 PORTUGUESE
    'pt': {
      'app_title': 'Grouply - Gestão de Equipes',
      'login_title': 'Bem-vindo de volta!',
      'login_subtitle': 'Faça login para continuar',
      'email_label': 'E-mail',
      'password_label': 'Senha',
      'forgot_password': 'Esqueceu a senha?',
      'login_button': 'Entrar',
      'login_with_google': 'Entrar com Google',
      'no_account': 'Não tem conta?',
      'go_to_register': 'Cadastrar',
      'or_label': 'ou',
      'google_signin_loading': 'Entrando com Google...',
      'google_signup_loading': 'Cadastrando com Google...',
      'register_title': 'Criar conta',
      'register_subtitle': 'Cadastre-se para começar',
      'confirm_password_label': 'Confirmar senha',
      'register_button': 'Cadastrar',
      'register_with_google': 'Cadastrar com Google',
      'registration_success': 'Cadastro realizado com sucesso.\nBem-vindo ao Grouply',
      'go_to_login_button': 'Ir para login',
      'have_account': 'Já tem conta?',
      'home_title': 'Início',
      'home_message': 'Bem-vindo ao Grouply Home',
      'close_button': 'Fechar',
      'home_groups_dialog_title': 'Grupos',
      'home_groups_create': 'Criar novo grupo',
      'home_groups_join': 'Entrar em grupo existente',
      'home_groups_create_snackbar': 'Função "Criar grupo" em desenvolvimento',
      'home_groups_join_snackbar': 'Função "Digitar código" em desenvolvimento',
      'dialog_create_group_title': 'Criar Novo Grupo',
      'label_team_name': 'Nome do Time (ex. Flamengo)',
      'label_team_sport': 'Esporte (ex. Futebol)',
      'button_cancel': 'Cancelar',
      'button_create': 'Criar',
      'snack_group_created': 'Grupo criado! Código: {code}',
      'snack_create_error': 'Erro ao criar grupo: {error}',
      'group_placeholder': 'Seção de Grupos',
      'group_empty_title': 'Sem grupos',
      'group_empty_subtitle': 'Você não participa de nenhum time.\nCrie um grupo ou entre em um existente!',
      'group_members_count': '{count} membros',
      'tab_board': 'Mural',
      'tab_members': 'Membros',
      'tab_info': 'Info',
      'info_invite_code_label': 'Código de Convite',
      'info_copy_code': 'Copiar código',
      'info_code_copied': 'Código copiado para a área de transferência',
      'info_sport': 'Esporte',
      'board_empty': 'Nenhum aviso no mural',
      'members_list_title': 'Membros da equipe',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Sair do grupo',
      'dialog_leave_title': 'Sair do grupo?',
      'dialog_leave_content': 'Você não verá mais este grupo na sua lista.',
      'leave_success': 'Você saiu do grupo.',
      'leave_error': 'Erro ao sair: {error}',
      'messages_placeholder': 'Seção de Mensagens\n(veja seus chats aqui)',
      'payments_placeholder': 'Seção de Pagamentos\n(gerencie assinaturas, taxas, etc.)',
      'profile_title': 'Gerenciar Perfil',
      'profile_change_photo': 'Alterar foto de perfil',
      'label_name': 'Nome',
      'label_day': 'Dia',
      'label_month': 'Mês',
      'label_year': 'Ano',
      'label_gender': 'Gênero',
      'label_sport': 'Esporte praticado',
      'label_role': 'Função do jogador',
      'button_save': 'Salvar',
      'toast_save_success': 'Dados salvos',
      'toast_login_required': 'Faça login para salvar',
      'toast_photo_error': 'Erro ao carregar foto',
      'settings_title': 'Configurações',
      'settings_section_theme': 'Tema',
      'settings_change_theme': 'Alterar tema',
      'settings_theme_dark_active': 'Tema escuro ativo',
      'settings_theme_light_active': 'Tema claro ativo',
      'settings_section_account': 'Conta',
      'settings_section_profile': 'Perfil',
      'settings_profile_manage_title': 'Gerenciar perfil',
      'settings_profile_manage_subtitle': 'Editar nome, nascimento, função...',
      'settings_section_language': 'Idioma',
      'settings_language_app': 'Idioma do app',
      'settings_language_select_title': 'Selecionar idioma',
      'settings_account_email_subtitle': 'E-mail vinculado à conta',
      'language_italian': 'Italiano',
      'language_english': 'Inglês',
      'language_spanish': 'Espanhol',
      'language_french': 'Francês',
      'language_german': 'Alemão',
      'language_portuguese': 'Português',
      'language_changed_snackbar': 'Idioma definido para {language}',
      'logout_button': 'Sair',
      'validation_insert_email': 'Digite seu e-mail',
      'validation_email_invalid': 'E-mail inválido',
      'validation_insert_password': 'Digite sua senha',
      'validation_insert_password_register': 'Crie uma senha',
      'validation_min_6_chars': 'Mínimo 6 caracteres',
      'validation_confirm_password': 'Confirme a senha',
      'validation_passwords_not_match': 'As senhas não coincidem',
      'error_login': 'Erro no login',
      'error_register': 'Erro no cadastro',
      'error_unexpected_login': 'Erro inesperado no login',
      'error_unexpected_register': 'Erro inesperado no cadastro',
      'error_user_not_found': 'Usuário não encontrado',
      'error_wrong_password': 'Senha incorreta',
      'error_invalid_email': 'E-mail inválido',
      'error_email_in_use': 'Este e-mail já está em uso',
      'error_weak_password': 'Senha muito fraca',
    },
  };

  String t(String key, {Map<String, String>? params}) {
    final langCode = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';

    String value =
        _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;

    if (params != null) {
      params.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }

    return value;
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['it', 'en', 'es', 'fr', 'de', 'pt'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      true;
}