import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const _localizedValues = <String, Map<String, String>>{
    // 🇮🇹 ITALIANO
    'it': {
      'app_title': 'Grouply - Team Manager',

      // AGENDA
      'label_today': 'Oggi',
      'label_tomorrow': 'Domani',
      'home_upcoming_events': 'Prossimi Eventi',
      'home_no_events': 'Nessun evento in programma',
      'home_no_groups': 'Non sei in nessun gruppo. Unisciti a uno per vedere gli eventi!',
      'event_group_label': 'Gruppo: {group}',

      // TAB HOME
      'home_tab_events': 'Eventi',
      'home_tab_posts': 'Post',
      'home_tab_polls': 'Sondaggi',
      'home_no_posts': 'Nessun post in bacheca',
      'home_no_polls': 'Nessun sondaggio attivo',

      // LOGIN & REGISTER
      'login_title': 'Bentornato!',
      'login_subtitle': 'Accedi per continuare',
      'email_label': 'Email',
      'password_label': 'Password',
      'forgot_password': 'Password dimenticata?',
      'login_button': 'Accedi',
      'login_with_google': 'Accedi con Google',
      'no_account': 'Non hai un account?',
      'go_to_register': 'Registrati',
      'or_label': 'oppure',
      'google_signin_loading': 'Accesso con Google...',
      'google_signup_loading': 'Registrazione con Google...',
      'register_title': 'Crea un account',
      'register_subtitle': 'Registrati per iniziare',
      'confirm_password_label': 'Conferma password',
      'register_button': 'Registrati',
      'register_with_google': 'Registrati con Google',
      'registration_success': 'Registrazione avvenuta con successo.\nTi diamo il benvenuto in Grouply',
      'go_to_login_button': 'Vai alla pagina di login',
      'have_account': 'Hai già un account?',

      // GESTIONE GRUPPI
      'home_title': 'Home',
      'home_message': 'Benvenuto nella Home di Grouply',
      'close_button': 'Chiudi',
      'home_groups_dialog_title': 'Gruppi',
      'home_groups_create': 'Crea nuovo gruppo',
      'home_groups_join': 'Inserisci codice gruppo',
      'home_groups_create_snackbar': 'Funzione "Crea nuovo gruppo" in sviluppo',
      'home_groups_join_snackbar': 'Funzione "Inserisci codice gruppo" in sviluppo',
      'dialog_create_group_title': 'Crea Nuovo Gruppo',
      'label_team_name': 'Nome del Team (es. Real Madrid)',
      'label_team_sport': 'Sport (es. Calcio)',
      'button_cancel': 'Annulla',
      'button_create': 'Crea',
      'snack_group_created': 'Gruppo creato! Codice: {code}',
      'snack_create_error': 'Errore creazione gruppo: {error}',
      'dialog_join_group_title': 'Unisciti a un Gruppo',
      'label_insert_code': 'Inserisci codice invito (6 caratteri)',
      'button_join': 'Unisciti',
      'error_code_not_found': 'Nessun gruppo trovato con questo codice',
      'error_already_member': 'Fai già parte di questo gruppo!',
      'snack_join_success': 'Ti sei unito al gruppo {groupName}!',
      'snack_join_error': 'Errore durante l\'unione: {error}',
      'group_placeholder': 'Sezione Gruppo',
      'group_empty_title': 'Nessun gruppo',
      'group_empty_subtitle': 'Non fai ancora parte di nessun team.\nCrea un gruppo o unisciti a uno esistente!',
      'group_members_count': '{count} membri',

      // DASHBOARD GRUPPO
      'tab_board': 'Bacheca',
      'tab_members': 'Membri',
      'tab_info': 'Info',
      'info_invite_code_label': 'Codice Invito',
      'info_copy_code': 'Copia codice',
      'info_code_copied': 'Codice copiato negli appunti',
      'info_sport': 'Sport',
      'board_empty': 'Nessun avviso in bacheca',
      'members_list_title': 'Membri del team',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Esci dal gruppo',
      'dialog_leave_title': 'Vuoi uscire dal gruppo?',
      'dialog_leave_content': 'Non vedrai più questo gruppo nella tua lista.',
      'leave_success': 'Sei uscito dal gruppo correttamente.',
      'leave_error': 'Errore durante l\'uscita: {error}',

      // FAB OPZIONI
      'fab_option_event': 'Evento',
      'fab_option_post': 'Post',
      'fab_option_post_sub': 'Condividi informazioni, foto e file',
      'fab_option_poll': 'Sondaggio',
      'fab_option_poll_sub': 'Chiedi ai membri la loro opinione',
      'fab_option_payment': 'Richieste di pagamento',
      'fab_option_payment_sub': 'Raccogli quote dai membri',

      // CREAZIONE EVENTO
      'event_select_type_title': 'Seleziona tipo',
      'event_type_single': 'Evento',
      'event_type_single_sub': 'Invita persone a partite, tornei o altri eventi sociali',
      'event_type_recurring': 'Evento ricorrente',
      'event_type_recurring_sub': 'Invita persone ad allenamenti o altri eventi',
      'create_event_title': 'Crea evento',
      'create_recurring_event_title': 'Crea evento ricorrente',
      'label_event_name': 'Nome evento',
      'default_event_training': 'Allenamento',
      'label_recurrence': 'Ripetizione',
      'recurrence_daily': 'Ogni giorno',
      'recurrence_weekly': 'Ogni settimana',
      'recurrence_monthly': 'Ogni mese',
      'recurrence_info': 'Verranno generati eventi per i prossimi 3 mesi.',
      'label_match_type': 'Tipo di partita',
      'match_type_home': 'Partita in casa',
      'match_type_away': 'Partita in trasferta',
      'match_type_tournament': 'Torneo',
      'match_type_friendly': 'Amichevole',
      'label_home_team': 'Squadra in casa',
      'label_away_team': 'Squadra fuori casa',
      'label_start_time': 'Orario di inizio',
      'label_date': 'Data',
      'label_meeting_point': 'Luogo di ritrovo',
      'label_meeting_time': 'Orario ritrovo',
      'label_match_location': 'Luogo della partita',
      'label_location': 'Luogo',
      'map_select_placeholder': 'Seleziona sulla mappa',
      'label_tournament_teams': 'Squadre partecipanti',
      'btn_add_team': 'Aggiungi squadra',
      'hint_team_n': 'Squadra {number}',
      'event_created_success': 'Evento creato con successo!',
      'error_missing_fields': 'Compila tutti i campi obbligatori',

      // 🔥 NUOVO: CREAZIONE POST
      'create_post_title': 'Crea un post',
      'label_publish_in': 'Pubblica in:',
      'label_post_title': 'Titolo del post',
      'label_post_description': 'Descrizione',
      'btn_add_media': 'Foto/Video',
      'btn_add_attachment': 'Allegato',
      'btn_publish': 'Pubblica',
      'post_created_success': 'Post pubblicato con successo!',
      'error_no_group_selected': 'Nessun gruppo selezionato',

      // DETTAGLI EVENTO
      'event_details_title': 'Dettagli Evento',
      'status_title': 'La tua presenza',
      'btn_accept': 'Ci sarò',
      'btn_decline': 'Non ci sarò',
      'status_going': 'Presente',
      'status_not_going': 'Assente',
      'status_pending': 'In attesa',
      'participants_list': 'Partecipanti ({count})',
      'tab_details': 'Dettagli',
      'tab_participants': 'Partecipanti',
      'delete_event_title': 'Elimina evento',
      'delete_event_confirm': 'Sei sicuro di voler eliminare questo evento? L\'azione è irreversibile.',
      'event_deleted': 'Evento eliminato correttamente.',
      'error_deleting_event': 'Errore durante l\'eliminazione: {error}',

      // ALTRE PAGINE
      'messages_placeholder': 'Sezione Messaggi\n(qui vedrai le tue chat)',
      'payments_placeholder': 'Sezione Pagamenti\n(qui gestirai abbonamenti, quote, ecc.)',

      // PROFILO
      'profile_title': 'Gestione Profilo',
      'profile_change_photo': 'Cambia foto profilo',
      'label_name': 'Nome',
      'label_day': 'Giorno',
      'label_month': 'Mese',
      'label_year': 'Anno',
      'label_gender': 'Genere',
      'label_sport': 'Sport praticato',
      'label_role': 'Ruolo del giocatore',
      'button_save': 'Salva',
      'toast_save_success': 'Dati profilo salvati',
      'toast_login_required': 'Devi essere loggato per salvare',
      'toast_photo_error': 'Errore durante il caricamento della foto',

      // IMPOSTAZIONI
      'settings_title': 'Impostazioni',
      'settings_section_theme': 'Tema',
      'settings_change_theme': 'Cambia tema',
      'settings_theme_dark_active': 'Il tema scuro è attivo',
      'settings_theme_light_active': 'Il tema chiaro è attivo',
      'settings_section_account': 'Account',
      'settings_section_profile': 'Profilo',
      'settings_profile_manage_title': 'Gestione profilo',
      'settings_profile_manage_subtitle': 'Modifica nome, nascita, ruolo, sport...',
      'settings_section_language': 'Lingua',
      'settings_language_app': 'Lingua dell\'app',
      'settings_language_select_title': 'Seleziona lingua',
      'settings_account_email_subtitle': 'Email collegata all\'account',
      'language_italian': 'Italiano',
      'language_english': 'Inglese',
      'language_spanish': 'Spagnolo',
      'language_french': 'Francese',
      'language_german': 'Tedesco',
      'language_portuguese': 'Portoghese',
      'language_changed_snackbar': 'Lingua impostata su {language}',
      'logout_button': 'Esci',

      // VALIDAZIONE
      'validation_insert_email': 'Inserisci la tua email',
      'validation_email_invalid': 'Email non valida',
      'validation_insert_password': 'Inserisci la password',
      'validation_insert_password_register': 'Inserisci una password',
      'validation_min_6_chars': 'Minimo 6 caratteri',
      'validation_confirm_password': 'Conferma la password',
      'validation_passwords_not_match': 'Le password non coincidono',
      'validation_code_length': 'Il codice deve essere lungo 6 caratteri',
      'error_login': 'Errore durante il login',
      'error_register': 'Errore durante la registrazione',
      'error_unexpected_login': 'Errore imprevisto durante il login',
      'error_unexpected_register': 'Errore imprevisto durante la registrazione',
      'error_user_not_found': 'Utente non trovato',
      'error_wrong_password': 'Password errata',
      'error_invalid_email': 'Email non valida',
      'error_email_in_use': 'Questa email è già registrata',
      'error_weak_password': 'La password è troppo debole',

      //Messaggi
      'messages_empty_title': 'Nessuna chat',
      'messages_empty_subtitle': 'Entra in un gruppo per iniziare a chattare.',
      'chat_empty': 'Nessun messaggio. Scrivi il primo!',
      'chat_hint': 'Scrivi un messaggio...',
      'chat_send_error': 'Errore invio: {error}',
      'chat_error_generic': 'Errore',
      'chat_no_messages_yet': 'Nessun messaggio ancora',
      'chat_message_deleted_or_empty': '(messaggio vuoto)',

      //Sondaggi
      'create_poll_title': 'Crea un sondaggio',
      'poll_question_label': 'Domanda',
      'poll_question_hint': 'Es. Chi viene all’allenamento?',
      'poll_option_label': 'Opzione {number}',
      'poll_add_option': 'Aggiungi opzione',
      'poll_remove_option': 'Rimuovi',
      'poll_publish': 'Pubblica sondaggio',
      'poll_creating': 'Creazione sondaggio...',
      'poll_min_options_error': 'Inserisci almeno 2 opzioni',
      'poll_missing_fields_error': 'Compila domanda e opzioni',
      'poll_created_success': 'Sondaggio creato con successo!',
      'poll_allow_multiple': 'Consenti selezioni multiple',
      'poll_vote_saved': 'Voto salvato',
      'poll_total_votes': '{count} voti',
      'poll_multiple_hint': 'puoi selezionare più opzioni',
      "poll_delete_title": "Elimina sondaggio",
      "poll_delete_confirm": "Vuoi davvero eliminare questo sondaggio del gruppo {groupName}?",
      "poll_deleted_success": "Sondaggio eliminato.",

      //Pagamenti
      'payment_select_people_title': 'Seleziona membri',
      'payment_select_people_subtitle': 'Scegli le persone a cui inviare la richiesta di pagamento',
      'payment_select_all': 'Seleziona tutti',
      'payment_clear_all': 'Deseleziona',
      'payment_next': 'Avanti',

      'payment_create_title': 'Richiesta di pagamento',
      'payment_recipients_label': 'Destinatari',
      'payment_amount_label': 'Importo',
      'payment_amount_hint': 'Es. 10,00',
      'payment_note_label': 'Descrizione',
      'payment_note_hint': 'Es. Quota mensile / Campo / Divise...',
      'payment_due_date_label': 'Scadenza (opzionale)',
      'payment_pick_date': 'Scegli data',

      'payment_send_request': 'Invia richiesta',
      'payment_creating': 'Invio...',
      'payment_request_created_success': 'Richiesta creata con successo!',
      'payment_invalid_amount_error': 'Inserisci un importo valido',
      'payment_missing_fields_error': 'Compila tutti i campi richiesti',
      'payment_no_recipients_error': 'Seleziona almeno una persona',

      "home_no_payments": "Nessuna richiesta di pagamento.",
      "payments_for_you_title": "Richieste per te",
      "payments_created_by_you_title": "Create da te",
      "payment_default_title": "Richiesta di pagamento",
      "payment_open_details_placeholder": "Dettagli pagamento in arrivo",

      "payment_status_pending": "In sospeso",
      "payment_status_paid": "Pagato",
      "payment_status_partial": "Parziale",
      "payment_targets_paid_hint": "pagati",

      "label_admin": "Admin",
      "payment_admin_only_error": "Solo l'amministratore può creare richieste di pagamento.",

      "payment_delete_title": "Elimina richiesta",
      "payment_delete_confirm": "Vuoi davvero eliminare questa richiesta di pagamento del gruppo \"{groupName}\"?",
      "payment_deleted_success": "Richiesta di pagamento eliminata.",
      "button_delete": "Elimina",
    },

    // 🇺🇸 ENGLISH
    'en': {
      'app_title': 'Grouply - Team Manager',
      'home_tab_events': 'Events',
      'home_tab_posts': 'Posts',
      'home_tab_polls': 'Polls',
      'home_no_posts': 'No posts on the board',
      'home_no_polls': 'No active polls',
      'label_today': 'Today',
      'label_tomorrow': 'Tomorrow',
      'home_upcoming_events': 'Upcoming Events',
      'home_no_events': 'No scheduled events',
      'home_no_groups': 'You are not in any group. Join one to see events!',
      'event_group_label': 'Group: {group}',
      'create_post_title': 'Create post',
      'label_publish_in': 'Publish in:',
      'label_post_title': 'Post title',
      'label_post_description': 'Description',
      'btn_add_media': 'Photo/Video',
      'btn_add_attachment': 'Attachment',
      'btn_publish': 'Publish',
      'post_created_success': 'Post published successfully!',
      'error_no_group_selected': 'No group selected',
      // ... (Resto delle chiavi EN)
      'label_location': 'Location',
      'label_meeting_point': 'Meeting point',
      'label_meeting_time': 'Meeting time',
      'label_match_location': 'Match location',
      'login_title': 'Welcome back!',
      'login_subtitle': 'Sign in to continue',
      'email_label': 'Email',
      'password_label': 'Password',
      'forgot_password': 'Forgot password?',
      'login_button': 'Sign in',
      'login_with_google': 'Sign in with Google',
      'no_account': 'Don\'t have an account?',
      'go_to_register': 'Register',
      'or_label': 'or',
      'google_signin_loading': 'Signing in with Google...',
      'google_signup_loading': 'Signing up with Google...',
      'register_title': 'Create an account',
      'register_subtitle': 'Sign up to get started',
      'confirm_password_label': 'Confirm password',
      'register_button': 'Sign up',
      'register_with_google': 'Sign up with Google',
      'registration_success': 'Registration successful.\nWelcome to Grouply',
      'go_to_login_button': 'Go to login page',
      'have_account': 'Already have an account?',
      'home_title': 'Home',
      'home_message': 'Welcome to Grouply Home',
      'close_button': 'Close',
      'home_groups_dialog_title': 'Groups',
      'home_groups_create': 'Create new group',
      'home_groups_join': 'Join existing group',
      'home_groups_create_snackbar': '“Create new group” feature under development',
      'home_groups_join_snackbar': '“Enter group code” feature under development',
      'dialog_create_group_title': 'Create New Group',
      'label_team_name': 'Team Name (e.g. Real Madrid)',
      'label_team_sport': 'Sport (e.g. Soccer)',
      'button_cancel': 'Cancel',
      'button_create': 'Create',
      'snack_group_created': 'Group created! Code: {code}',
      'snack_create_error': 'Error creating group: {error}',
      'dialog_join_group_title': 'Join a Group',
      'label_insert_code': 'Enter invite code (6 chars)',
      'button_join': 'Join',
      'error_code_not_found': 'No group found with this code',
      'error_already_member': 'You are already a member of this group!',
      'snack_join_success': 'Joined group {groupName}!',
      'snack_join_error': 'Error joining group: {error}',
      'group_placeholder': 'Group Section',
      'group_empty_title': 'No groups',
      'group_empty_subtitle': 'You are not part of any team yet.\nCreate a group or join an existing one!',
      'group_members_count': '{count} members',
      'tab_board': 'Board',
      'tab_members': 'Members',
      'tab_info': 'Info',
      'info_invite_code_label': 'Invite Code',
      'info_copy_code': 'Copy code',
      'info_code_copied': 'Code copied to clipboard',
      'info_sport': 'Sport',
      'board_empty': 'No posts on the board',
      'members_list_title': 'Team members',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Leave group',
      'dialog_leave_title': 'Leave group?',
      'dialog_leave_content': 'You will no longer see this group in your list.',
      'leave_success': 'You left the group.',
      'leave_error': 'Error leaving group: {error}',
      'fab_option_event': 'Event',
      'fab_option_post': 'Post',
      'fab_option_post_sub': 'Share info, photos, and files',
      'fab_option_poll': 'Poll',
      'fab_option_poll_sub': 'Ask members for their opinion',
      'fab_option_payment': 'Payment request',
      'fab_option_payment_sub': 'Collect fees from members',
      'event_select_type_title': 'Select type',
      'event_type_single': 'Event',
      'event_type_single_sub': 'Invite people to matches, tournaments or other social events',
      'event_type_recurring': 'Recurring event',
      'event_type_recurring_sub': 'Invite people to practices or other events',
      'create_event_title': 'Create event',
      'create_recurring_event_title': 'Create recurring event',
      'label_event_name': 'Event name',
      'default_event_training': 'Training',
      'label_recurrence': 'Repeat',
      'recurrence_daily': 'Every day',
      'recurrence_weekly': 'Every week',
      'recurrence_monthly': 'Every month',
      'recurrence_info': 'Events will be generated for the next 3 months.',
      'label_match_type': 'Match type',
      'match_type_home': 'Home match',
      'match_type_away': 'Away match',
      'match_type_tournament': 'Tournament',
      'match_type_friendly': 'Friendly',
      'label_home_team': 'Home team',
      'label_away_team': 'Away team',
      'label_start_time': 'Start time',
      'label_date': 'Date',
      'map_select_placeholder': 'Select on map',
      'label_tournament_teams': 'Participating teams',
      'btn_add_team': 'Add team',
      'hint_team_n': 'Team {number}',
      'event_created_success': 'Event created successfully!',
      'error_missing_fields': 'Please fill all required fields',
      'event_details_title': 'Event Details',
      'status_title': 'Your status',
      'btn_accept': 'Going',
      'btn_decline': 'Not going',
      'status_going': 'Going',
      'status_not_going': 'Not going',
      'status_pending': 'Pending',
      'participants_list': 'Participants ({count})',
      'tab_details': 'Details',
      'tab_participants': 'Participants',
      'delete_event_title': 'Delete event',
      'delete_event_confirm': 'Are you sure you want to delete this event? This action cannot be undone.',
      'event_deleted': 'Event deleted successfully.',
      'error_deleting_event': 'Error deleting event: {error}',
      'messages_placeholder': 'Messages Section\n(view your chats here)',
      'payments_placeholder': 'Payments Section\n(manage subscriptions, fees, etc.)',
      'profile_title': 'Profile Management',
      'profile_change_photo': 'Change profile photo',
      'label_name': 'Name',
      'label_day': 'Day',
      'label_month': 'Month',
      'label_year': 'Year',
      'label_gender': 'Gender',
      'label_sport': 'Sport played',
      'label_role': 'Player role',
      'button_save': 'Save',
      'toast_save_success': 'Profile data saved',
      'toast_login_required': 'You must be logged in to save',
      'toast_photo_error': 'Error uploading photo',
      'settings_title': 'Settings',
      'settings_section_theme': 'Theme',
      'settings_change_theme': 'Change theme',
      'settings_theme_dark_active': 'Dark theme is active',
      'settings_theme_light_active': 'Light theme is active',
      'settings_section_account': 'Account',
      'settings_section_profile': 'Profile',
      'settings_profile_manage_title': 'Manage profile',
      'settings_profile_manage_subtitle': 'Edit name, birthday, role, sport...',
      'settings_section_language': 'Language',
      'settings_language_app': 'App language',
      'settings_language_select_title': 'Select language',
      'settings_account_email_subtitle': 'Email linked to the account',
      'language_italian': 'Italian',
      'language_english': 'English',
      'language_spanish': 'Spanish',
      'language_french': 'French',
      'language_german': 'German',
      'language_portuguese': 'Portuguese',
      'language_changed_snackbar': 'Language set to {language}',
      'logout_button': 'Logout',
      'validation_insert_email': 'Enter your email',
      'validation_email_invalid': 'Invalid email',
      'validation_insert_password': 'Enter your password',
      'validation_insert_password_register': 'Enter a password',
      'validation_min_6_chars': 'Minimum 6 characters',
      'validation_confirm_password': 'Confirm your password',
      'validation_passwords_not_match': 'Passwords do not match',
      'validation_code_length': 'Code must be 6 characters long',
      'error_login': 'Error during login',
      'error_register': 'Error during registration',
      'error_unexpected_login': 'Unexpected error during login',
      'error_unexpected_register': 'Unexpected error during registration',
      'error_user_not_found': 'User not found',
      'error_wrong_password': 'Wrong password',
      'error_invalid_email': 'Invalid email',
      'error_email_in_use': 'This email is already registered',
      'error_weak_password': 'Password is too weak',

      //Messaggi
      'messages_empty_title': 'No chats',
      'messages_empty_subtitle': 'Join a group to start chatting.',
      'chat_empty': 'No messages yet. Write the first one!',
      'chat_hint': 'Type a message...',
      'chat_send_error': 'Send error: {error}',
      'chat_error_generic': 'Error',
      'chat_no_messages_yet': 'No messages yet',
      'chat_message_deleted_or_empty': '(empty message)',

      //Sondaggi
      'create_poll_title': 'Create poll',
      'poll_question_label': 'Question',
      'poll_question_hint': 'E.g. Who is coming to training?',
      'poll_option_label': 'Option {number}',
      'poll_add_option': 'Add option',
      'poll_remove_option': 'Remove',
      'poll_publish': 'Publish poll',
      'poll_creating': 'Creating poll...',
      'poll_min_options_error': 'Enter at least 2 options',
      'poll_missing_fields_error': 'Fill in question and options',
      'poll_created_success': 'Poll created successfully!',
      'poll_allow_multiple': 'Allow multiple choices',
      'poll_vote_saved': 'Vote saved',
      'poll_total_votes': '{count} votes',
      'poll_multiple_hint': 'you can select multiple options',
      "poll_delete_title": "Delete poll",
      "poll_delete_confirm": "Do you really want to delete this poll from the group {groupName}?",
      "poll_deleted_success": "Poll deleted.",

      //Pagamenti
      'payment_select_people_title': 'Select members',
      'payment_select_people_subtitle': 'Choose who will receive the payment request',
      'payment_select_all': 'Select all',
      'payment_clear_all': 'Clear',
      'payment_next': 'Next',

      'payment_create_title': 'Payment request',
      'payment_recipients_label': 'Recipients',
      'payment_amount_label': 'Amount',
      'payment_amount_hint': 'e.g. 10.00',
      'payment_note_label': 'Description',
      'payment_note_hint': 'e.g. Monthly fee / Field / Jerseys...',
      'payment_due_date_label': 'Due date (optional)',
      'payment_pick_date': 'Pick date',

      'payment_send_request': 'Send request',
      'payment_creating': 'Sending...',
      'payment_request_created_success': 'Request created successfully!',
      'payment_invalid_amount_error': 'Enter a valid amount',
      'payment_missing_fields_error': 'Please fill in all required fields',
      'payment_no_recipients_error': 'Select at least one person',

      "home_no_payments": "No payment requests.",
      "payments_for_you_title": "Requests for you",
      "payments_created_by_you_title": "Created by you",
      "payment_default_title": "Payment request",
      "payment_open_details_placeholder": "Payment details coming soon",

      "payment_status_pending": "Pending",
      "payment_status_paid": "Paid",
      "payment_status_partial": "Partial",
      "payment_targets_paid_hint": "paid",

      "label_admin": "Admin",
      "payment_admin_only_error": "Only the admin can create payment requests.",

      "payment_delete_title": "Delete request",
      "payment_delete_confirm": "Do you really want to delete this payment request for the group \"{groupName}\"?",
      "payment_deleted_success": "Payment request deleted.",
      "button_delete": "Delete",
    },

    // 🇪🇸 SPANISH
    'es': {
      'app_title': 'Grouply - Team Manager',
      'create_post_title': 'Crear publicación',
      'label_publish_in': 'Publicar en:',
      'label_post_title': 'Título de la publicación',
      'label_post_description': 'Descripción',
      'btn_add_media': 'Foto/Video',
      'btn_add_attachment': 'Adjunto',
      'btn_publish': 'Publicar',
      'post_created_success': '¡Publicación creada con éxito!',
      'error_no_group_selected': 'Ningún grupo seleccionado',
      // ... (Resto delle chiavi ES) ...
      'home_tab_events': 'Eventos',
      'home_tab_posts': 'Publicaciones',
      'home_tab_polls': 'Encuestas',
      'home_no_posts': 'No hay publicaciones',
      'home_no_polls': 'No hay encuestas activas',
      'label_location': 'Lugar',
      'label_today': 'Hoy',
      'label_tomorrow': 'Mañana',
      'home_upcoming_events': 'Próximos eventos',
      'home_no_events': 'No hay eventos programados',
      'home_no_groups': 'No estás en ningún grupo. ¡Únete a uno para ver eventos!',
      'event_group_label': 'Grupo: {group}',
      'login_title': '¡Bienvenido de nuevo!',
      'login_subtitle': 'Inicia sesión para continuar',
      'email_label': 'Correo electrónico',
      'password_label': 'Contraseña',
      'forgot_password': '¿Olvidaste la contraseña?',
      'login_button': 'Iniciar sesión',
      'login_with_google': 'Iniciar con Google',
      'no_account': '¿No tienes una cuenta?',
      'go_to_register': 'Regístrate',
      'or_label': 'o',
      'google_signin_loading': 'Iniciando con Google...',
      'google_signup_loading': 'Registrando con Google...',
      'register_title': 'Crea una cuenta',
      'register_subtitle': 'Regístrate para empezar',
      'confirm_password_label': 'Confirmar contraseña',
      'register_button': 'Registrarse',
      'register_with_google': 'Registrarse con Google',
      'registration_success': 'Registro exitoso.\nBienvenido a Grouply',
      'go_to_login_button': 'Ir a la página de inicio de sesión',
      'have_account': '¿Ya tienes una cuenta?',
      'home_title': 'Inicio',
      'home_message': 'Bienvenido al inicio de Grouply',
      'close_button': 'Cerrar',
      'home_groups_dialog_title': 'Grupos',
      'home_groups_create': 'Crear nuevo grupo',
      'home_groups_join': 'Unirse a un grupo',
      'home_groups_create_snackbar': 'Función "Crear nuevo grupo" en desarrollo',
      'home_groups_join_snackbar': 'Función "Introducir código" en desarrollo',
      'dialog_create_group_title': 'Crear Nuevo Grupo',
      'label_team_name': 'Nombre del Equipo (ej. Real Madrid)',
      'label_team_sport': 'Deporte (ej. Fútbol)',
      'button_cancel': 'Cancelar',
      'button_create': 'Crear',
      'snack_group_created': '¡Grupo creado! Código: {code}',
      'snack_create_error': 'Error al crear grupo: {error}',
      'dialog_join_group_title': 'Unirse a un Grupo',
      'label_insert_code': 'Código de invitación (6 letras)',
      'button_join': 'Unirse',
      'error_code_not_found': 'No se encontró ningún grupo',
      'error_already_member': '¡Ya eres miembro de este grupo!',
      'snack_join_success': '¡Te has unido al grupo {groupName}!',
      'snack_join_error': 'Error al unirse: {error}',
      'group_placeholder': 'Sección de Grupos',
      'group_empty_title': 'Sin grupos',
      'group_empty_subtitle': 'Aún no eres parte de ningún equipo.\n¡Crea un grupo o unnete a uno existente!',
      'group_members_count': '{count} miembros',
      'tab_board': 'Tablón',
      'tab_members': 'Miembros',
      'tab_info': 'Info',
      'info_invite_code_label': 'Código de invitación',
      'info_copy_code': 'Copiar código',
      'info_code_copied': 'Código copiado al portapapeles',
      'info_sport': 'Deporte',
      'board_empty': 'No hay avisos en el tablón',
      'members_list_title': 'Miembros del equipo',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Salir del grupo',
      'dialog_leave_title': '¿Salir del grupo?',
      'dialog_leave_content': 'Ya no verás este grupo en tu lista.',
      'leave_success': 'Has salido del grupo.',
      'leave_error': 'Error al salir: {error}',
      'fab_option_event': 'Evento',
      'fab_option_post': 'Publicación',
      'fab_option_post_sub': 'Comparte información, fotos y archivos',
      'fab_option_poll': 'Encuesta',
      'fab_option_poll_sub': 'Pide su opinión a los miembros',
      'fab_option_payment': 'Solicitud de pago',
      'fab_option_payment_sub': 'Recauda cuotas de los miembros',
      'event_select_type_title': 'Seleccionar tipo',
      'event_type_single': 'Evento',
      'event_type_single_sub': 'Invita personas a partidos, torneos u otros eventos',
      'event_type_recurring': 'Evento recurrente',
      'event_type_recurring_sub': 'Invita personas a entrenamientos',
      'create_event_title': 'Crear evento',
      'create_recurring_event_title': 'Crear evento recurrente',
      'label_event_name': 'Nombre del evento',
      'default_event_training': 'Entrenamiento',
      'label_recurrence': 'Repetir',
      'recurrence_daily': 'Diariamente',
      'recurrence_weekly': 'Semanalmente',
      'recurrence_monthly': 'Mensualmente',
      'recurrence_info': 'Se generarán eventos para los próximos 3 meses.',
      'label_match_type': 'Tipo de partido',
      'match_type_home': 'Partido en casa',
      'match_type_away': 'Partido fuera',
      'match_type_tournament': 'Torneio',
      'match_type_friendly': 'Amistoso',
      'label_home_team': 'Equipo local',
      'label_away_team': 'Equipo visitante',
      'label_start_time': 'Hora de inicio',
      'label_date': 'Fecha',
      'label_meeting_point': 'Punto de encuentro',
      'label_meeting_time': 'Hora de encuentro',
      'label_match_location': 'Lugar del partido',
      'map_select_placeholder': 'Seleccionar en el mapa',
      'label_tournament_teams': 'Equipos participantes',
      'btn_add_team': 'Añadir equipo',
      'hint_team_n': 'Equipo {number}',
      'event_created_success': '¡Evento creado con éxito!',
      'error_missing_fields': 'Por favor, completa todos los campos requeridos',
      'event_details_title': 'Detalles del Evento',
      'status_title': 'Tu estado',
      'btn_accept': 'Asistiré',
      'btn_decline': 'No asistiré',
      'status_going': 'Asistiré',
      'status_not_going': 'No asistiré',
      'status_pending': 'Pendiente',
      'participants_list': 'Participantes ({count})',
      'tab_details': 'Detalles',
      'tab_participants': 'Participantes',
      'delete_event_title': 'Eliminar evento',
      'delete_event_confirm': '¿Estás seguro de que quieres eliminar este evento? Esta acción no se puede deshacer.',
      'event_deleted': 'Evento eliminado correctamente.',
      'error_deleting_event': 'Error al eliminar: {error}',
      'messages_placeholder': 'Sección de Mensajes\n(aquí verás tus chats)',
      'payments_placeholder': 'Sección de Pagos\n(gestiona suscripciones, cuotas, etc.)',
      'profile_title': 'Gestión del Perfil',
      'profile_change_photo': 'Cambiar foto de perfil',
      'label_name': 'Nombre',
      'label_day': 'Día',
      'label_month': 'Mes',
      'label_year': 'Año',
      'label_gender': 'Género',
      'label_sport': 'Deporte practicado',
      'label_role': 'Rol del jugador',
      'button_save': 'Guardar',
      'toast_save_success': 'Datos del perfil guardados',
      'toast_login_required': 'Debes iniciar sesión para guardar',
      'toast_photo_error': 'Error al cargar la foto',
      'settings_title': 'Ajustes',
      'settings_section_theme': 'Tema',
      'settings_change_theme': 'Cambiar tema',
      'settings_theme_dark_active': 'El tema oscuro está activo',
      'settings_theme_light_active': 'El tema claro está activo',
      'settings_section_account': 'Cuenta',
      'settings_section_profile': 'Perfil',
      'settings_profile_manage_title': 'Gestión del perfil',
      'settings_profile_manage_subtitle': 'Modificar nombre, fecha de nacimiento, rol, deporte...',
      'settings_section_language': 'Idioma',
      'settings_language_app': 'Idioma de la app',
      'settings_language_select_title': 'Selecciona el idioma',
      'settings_account_email_subtitle': 'Correo vinculado a la cuenta',
      'language_italian': 'Italiano',
      'language_english': 'Inglés',
      'language_spanish': 'Español',
      'language_french': 'Francés',
      'language_german': 'Alemán',
      'language_portuguese': 'Portugués',
      'language_changed_snackbar': 'Idioma establecido en {language}',
      'logout_button': 'Salir',
      'validation_insert_email': 'Introduce tu correo',
      'validation_email_invalid': 'Correo inválido',
      'validation_insert_password': 'Introduce la contraseña',
      'validation_insert_password_register': 'Introduce una contraseña',
      'validation_min_6_chars': 'Mínimo 6 caracteres',
      'validation_confirm_password': 'Confirma la contraseña',
      'validation_passwords_not_match': 'Las contraseñas no coinciden',
      'validation_code_length': 'El código debe tener 6 caracteres',
      'error_login': 'Error durante el inicio de sesión',
      'error_register': 'Error durante el registro',
      'error_unexpected_login': 'Error inesperado durante el inicio',
      'error_unexpected_register': 'Error inesperado durante el registro',
      'error_user_not_found': 'Usuario no encontrado',
      'error_wrong_password': 'Contraseña incorrecta',
      'error_invalid_email': 'Correo inválido',
      'error_email_in_use': 'Este correo ya está registrado',
      'error_weak_password': 'La contraseña es demasiado débil',

      //Messaggi
      'messages_empty_title': 'Sin chats',
      'messages_empty_subtitle': 'Únete a un grupo para empezar a chatear.',
      'chat_empty': 'Aún no hay mensajes. ¡Escribe el primero!',
      'chat_hint': 'Escribe un mensaje...',
      'chat_send_error': 'Error al enviar: {error}',
      'chat_error_generic': 'Error',
      'chat_no_messages_yet': 'Aún no hay mensajes',
      'chat_message_deleted_or_empty': '(mensaje vacío)',

      //Sondaggi
      'create_poll_title': 'Crear encuesta',
      'poll_question_label': 'Pregunta',
      'poll_question_hint': 'Ej. ¿Quién viene al entrenamiento?',
      'poll_option_label': 'Opción {number}',
      'poll_add_option': 'Añadir opción',
      'poll_remove_option': 'Quitar',
      'poll_publish': 'Publicar encuesta',
      'poll_creating': 'Creando encuesta...',
      'poll_min_options_error': 'Introduce al menos 2 opciones',
      'poll_missing_fields_error': 'Completa la pregunta y las opciones',
      'poll_created_success': '¡Encuesta creada con éxito!',
      'poll_allow_multiple': 'Permitir selecciones múltiples',
      'poll_vote_saved': 'Voto guardado',
      'poll_total_votes': '{count} votos',
      'poll_multiple_hint': 'puedes seleccionar varias opciones',
      "poll_delete_title": "Eliminar encuesta",
      "poll_delete_confirm": "¿De verdad quieres eliminar esta encuesta del grupo {groupName}?",
      "poll_deleted_success": "Encuesta eliminada.",

      //Pagamenti
      'payment_select_people_title': 'Seleccionar miembros',
      'payment_select_people_subtitle': 'Elige a quién enviar la solicitud de pago',
      'payment_select_all': 'Seleccionar todo',
      'payment_clear_all': 'Deseleccionar',
      'payment_next': 'Siguiente',

      'payment_create_title': 'Solicitud de pago',
      'payment_recipients_label': 'Destinatarios',
      'payment_amount_label': 'Importe',
      'payment_amount_hint': 'Ej. 10,00',
      'payment_note_label': 'Descripción',
      'payment_note_hint': 'Ej. Cuota mensual / Campo / Equipación...',
      'payment_due_date_label': 'Vencimiento (opcional)',
      'payment_pick_date': 'Elegir fecha',

      'payment_send_request': 'Enviar solicitud',
      'payment_creating': 'Enviando...',
      'payment_request_created_success': '¡Solicitud creada con éxito!',
      'payment_invalid_amount_error': 'Introduce un importe válido',
      'payment_missing_fields_error': 'Completa todos los campos obligatorios',
      'payment_no_recipients_error': 'Selecciona al menos una persona',

      "home_no_payments": "No hay solicitudes de pago.",
      "payments_for_you_title": "Solicitudes para ti",
      "payments_created_by_you_title": "Creadas por ti",
      "payment_default_title": "Solicitud de pago",
      "payment_open_details_placeholder": "Detalles del pago próximamente",

      "payment_status_pending": "Pendiente",
      "payment_status_paid": "Pagado",
      "payment_status_partial": "Parcial",
      "payment_targets_paid_hint": "pagados",

      "label_admin": "Admin",
      "payment_admin_only_error": "Solo el administrador puede crear solicitudes de pago.",

      "payment_delete_title": "Eliminar solicitud",
      "payment_delete_confirm": "¿De verdad quieres eliminar esta solicitud de pago del grupo \"{groupName}\"?",
      "payment_deleted_success": "Solicitud de pago eliminada.",
      "button_delete": "Eliminar",
    },

    // 🇫🇷 FRENCH
    'fr': {
      'app_title': 'Grouply - Gestion d\'équipe',
      'create_post_title': 'Créer une publication',
      'label_publish_in': 'Publier dans :',
      'label_post_title': 'Titre de la publication',
      'label_post_description': 'Description',
      'btn_add_media': 'Photo/Vidéo',
      'btn_add_attachment': 'Pièce jointe',
      'btn_publish': 'Publier',
      'post_created_success': 'Publication créée avec succès !',
      'error_no_group_selected': 'Aucun groupe sélectionné',
      // ... (Resto delle chiavi FR) ...
      'home_tab_events': 'Événements',
      'home_tab_posts': 'Publications',
      'home_tab_polls': 'Sondages',
      'home_no_posts': 'Aucune publication',
      'home_no_polls': 'Aucun sondage actif',
      'label_location': 'Lieu',
      'label_meeting_point': 'Point de rendez-vous',
      'label_meeting_time': 'Heure de rendez-vous',
      'label_match_location': 'Lieu du match',
      'create_recurring_event_title': 'Créer un événement récurrent',
      'label_event_name': 'Nom de l\'événement',
      'default_event_training': 'Entraînement',
      'label_recurrence': 'Répétition',
      'recurrence_daily': 'Chaque jour',
      'recurrence_weekly': 'Chaque semaine',
      'recurrence_monthly': 'Chaque mois',
      'recurrence_info': 'Les événements seront générés pour les 3 prochains mois.',
      'label_today': 'Aujourd\'hui',
      'label_tomorrow': 'Demain',
      'home_upcoming_events': 'Événements à venir',
      'home_no_events': 'Aucun événement prévu',
      'home_no_groups': 'Vous n\'êtes dans aucun groupe. Rejoignez-en un !',
      'event_group_label': 'Groupe : {group}',
      'login_title': 'Bon retour !',
      'login_subtitle': 'Connectez-vous pour continuer',
      'email_label': 'Email',
      'password_label': 'Mot de passe',
      'forgot_password': 'Mot de passe oublié ?',
      'login_button': 'Se connecter',
      'login_with_google': 'Continuer avec Google',
      'no_account': 'Pas encore de compte ?',
      'go_to_register': 'S\'inscrire',
      'or_label': 'ou',
      'google_signin_loading': 'Connexion avec Google...',
      'google_signup_loading': 'Inscription avec Google...',
      'register_title': 'Créer un compte',
      'register_subtitle': 'Inscrivez-vous pour commencer',
      'confirm_password_label': 'Confirmer le mot de passe',
      'register_button': 'S\'inscrire',
      'register_with_google': 'S\'inscrire avec Google',
      'registration_success': 'Inscription réussie.\nBienvenue sur Grouply',
      'go_to_login_button': 'Aller à la page de connexion',
      'have_account': 'Déjà un compte ?',
      'home_title': 'Accueil',
      'home_message': 'Bienvenue sur l\'accueil de Grouply',
      'close_button': 'Fermer',
      'home_groups_dialog_title': 'Groupes',
      'home_groups_create': 'Créer un nouveau groupe',
      'home_groups_join': 'Rejoindre un groupe',
      'home_groups_create_snackbar': 'Fonctionnalité "Créer groupe" en développement',
      'home_groups_join_snackbar': 'Fonctionnalité "Code groupe" en développement',
      'dialog_create_group_title': 'Créer un nouveau groupe',
      'label_team_name': 'Nom de l\'équipe (ex. PSG)',
      'label_team_sport': 'Sport (ex. Football)',
      'button_cancel': 'Annuler',
      'button_create': 'Créer',
      'snack_group_created': 'Groupe créé ! Code : {code}',
      'snack_create_error': 'Erreur lors de la création : {error}',
      'dialog_join_group_title': 'Rejoindre un groupe',
      'label_insert_code': 'Entrez le code (6 caractères)',
      'button_join': 'Rejoindre',
      'error_code_not_found': 'Aucun groupe trouvé avec ce code',
      'error_already_member': 'Vous êtes déjà membre !',
      'snack_join_success': 'Vous avez rejoint le groupe {groupName} !',
      'snack_join_error': 'Erreur lors de l\'ajout : {error}',
      'group_placeholder': 'Section Groupes',
      'group_empty_title': 'Aucun groupe',
      'group_empty_subtitle': 'Vous ne faites partie d\'aucune équipe.\nCréez un groupe ou rejoignez-en un !',
      'group_members_count': '{count} membres',
      'tab_board': 'Tableau',
      'tab_members': 'Membres',
      'tab_info': 'Infos',
      'info_invite_code_label': 'Code d\'invitation',
      'info_copy_code': 'Copier le code',
      'info_code_copied': 'Code copié dans le presse-papiers',
      'info_sport': 'Sport',
      'board_empty': 'Aucune annonce sur le tableau',
      'members_list_title': 'Membres de l\'équipe',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Quitter le groupe',
      'dialog_leave_title': 'Quitter le groupe ?',
      'dialog_leave_content': 'Vous ne verrez plus ce groupe dans votre liste.',
      'leave_success': 'Vous avez quitté le groupe.',
      'leave_error': 'Erreur lors de la sortie : {error}',
      'fab_option_event': 'Événement',
      'fab_option_post': 'Publication',
      'fab_option_post_sub': 'Partagez infos, photos et fichiers',
      'fab_option_poll': 'Sondage',
      'fab_option_poll_sub': 'Demandez leur avis aux membres',
      'fab_option_payment': 'Demande de paiement',
      'fab_option_payment_sub': 'Collectez des cotisations',
      'event_select_type_title': 'Sélectionner le type',
      'event_type_single': 'Événement',
      'event_type_single_sub': 'Invitez des personnes à des matchs ou tournois',
      'event_type_recurring': 'Événement récurrent',
      'event_type_recurring_sub': 'Invitez des personnes aux entraînements',
      'create_event_title': 'Créer un événement',
      'label_match_type': 'Type de match',
      'match_type_home': 'Match à domicile',
      'match_type_away': 'Match à l\'extérieur',
      'match_type_tournament': 'Tournoi',
      'match_type_friendly': 'Amical',
      'label_home_team': 'Équipe domicile',
      'label_away_team': 'Équipe extérieure',
      'label_start_time': 'Heure de début',
      'label_date': 'Date',
      'map_select_placeholder': 'Sélectionner sur la carte',
      'label_tournament_teams': 'Équipes participantes',
      'btn_add_team': 'Ajouter une équipe',
      'hint_team_n': 'Équipe {number}',
      'event_created_success': 'Événement créé avec succès !',
      'error_missing_fields': 'Veuillez remplir tous les champs obligatoires',
      'event_details_title': 'Détails de l\'événement',
      'status_title': 'Votre présence',
      'btn_accept': 'Présent',
      'btn_decline': 'Absent',
      'status_going': 'Présent',
      'status_not_going': 'Absent',
      'status_pending': 'En attente',
      'participants_list': 'Participants ({count})',
      'tab_details': 'Détails',
      'tab_participants': 'Participants',
      'delete_event_title': 'Supprimer l\'événement',
      'delete_event_confirm': 'Êtes-vous sûr de vouloir supprimer cet événement ? Cette action est irréversible.',
      'event_deleted': 'Événement supprimé avec succès.',
      'error_deleting_event': 'Erreur lors de la suppression : {error}',
      'messages_placeholder': 'Section Messages\n(vos discussions ici)',
      'payments_placeholder': 'Section Paiements\n(abonnements, cotisations, etc.)',
      'profile_title': 'Gestion du Profil',
      'profile_change_photo': 'Changer la photo de profil',
      'label_name': 'Nom',
      'label_day': 'Jour',
      'label_month': 'Mois',
      'label_year': 'Année',
      'label_gender': 'Genre',
      'label_sport': 'Sport pratiqué',
      'label_role': 'Rôle du joueur',
      'button_save': 'Enregistrer',
      'toast_save_success': 'Profil enregistré',
      'toast_login_required': 'Connectez-vous pour enregistrer',
      'toast_photo_error': 'Erreur lors du chargement de la photo',
      'settings_title': 'Paramètres',
      'settings_section_theme': 'Thème',
      'settings_change_theme': 'Changer de thème',
      'settings_theme_dark_active': 'Thème sombre actif',
      'settings_theme_light_active': 'Thème clair actif',
      'settings_section_account': 'Compte',
      'settings_section_profile': 'Profil',
      'settings_profile_manage_title': 'Gérer le profil',
      'settings_profile_manage_subtitle': 'Modifier nom, naissance, rôle, sport...',
      'settings_section_language': 'Langue',
      'settings_language_app': 'Langue de l\'application',
      'settings_language_select_title': 'Sélectionner la langue',
      'settings_account_email_subtitle': 'Email lié au compte',
      'language_italian': 'Italien',
      'language_english': 'Anglais',
      'language_spanish': 'Espagnol',
      'language_french': 'Français',
      'language_german': 'Allemand',
      'language_portuguese': 'Portugais',
      'language_changed_snackbar': 'Langue définie sur {language}',
      'logout_button': 'Se déconnecter',
      'validation_insert_email': 'Entrez votre email',
      'validation_email_invalid': 'Email invalide',
      'validation_insert_password': 'Entrez votre mot de passe',
      'validation_insert_password_register': 'Entrez un mot de passe',
      'validation_min_6_chars': 'Minimum 6 caractères',
      'validation_confirm_password': 'Confirmez le mot de passe',
      'validation_passwords_not_match': 'Les mots de passe ne correspondent pas',
      'validation_code_length': 'Le code doit comporter 6 caractères',
      'error_login': 'Erreur de connexion',
      'error_register': 'Erreur d\'inscription',
      'error_unexpected_login': 'Erreur inattendue de connexion',
      'error_unexpected_register': 'Erreur inattendue d\'inscription',
      'error_user_not_found': 'Utilisateur non trouvé',
      'error_wrong_password': 'Mot de passe incorrect',
      'error_invalid_email': 'Email invalide',
      'error_email_in_use': 'Cet email est déjà enregistré',
      'error_weak_password': 'Mot de passe trop faible',

      //Messaggi
      'messages_empty_title': 'Aucune discussion',
      'messages_empty_subtitle': 'Rejoignez un groupe pour commencer à discuter.',
      'chat_empty': 'Aucun message. Écrivez le premier !',
      'chat_hint': 'Écrire un message...',
      'chat_send_error': 'Erreur d’envoi : {error}',
      'chat_error_generic': 'Erreur',
      'chat_no_messages_yet': 'Aucun message pour l’instant',
      'chat_message_deleted_or_empty': '(message vide)',

      //Sondaggi
      'create_poll_title': 'Créer un sondage',
      'poll_question_label': 'Question',
      'poll_question_hint': 'Ex. Qui vient à l’entraînement ?',
      'poll_option_label': 'Option {number}',
      'poll_add_option': 'Ajouter une option',
      'poll_remove_option': 'Retirer',
      'poll_publish': 'Publier le sondage',
      'poll_creating': 'Création du sondage...',
      'poll_min_options_error': 'Ajoutez au moins 2 options',
      'poll_missing_fields_error': 'Remplissez la question et les options',
      'poll_created_success': 'Sondage créé avec succès !',
      'poll_allow_multiple': 'Autoriser plusieurs choix',
      'poll_vote_saved': 'Vote enregistré',
      'poll_total_votes': '{count} votes',
      'poll_multiple_hint': 'vous pouvez sélectionner plusieurs options',
      "poll_delete_title": "Supprimer le sondage",
      "poll_delete_confirm": "Voulez-vous vraiment supprimer ce sondage du groupe {groupName} ?",
      "poll_deleted_success": "Sondage supprimé.",

      //Pagamenti
      'payment_select_people_title': 'Sélectionner des membres',
      'payment_select_people_subtitle': 'Choisissez les personnes qui recevront la demande de paiement',
      'payment_select_all': 'Tout sélectionner',
      'payment_clear_all': 'Désélectionner',
      'payment_next': 'Suivant',

      'payment_create_title': 'Demande de paiement',
      'payment_recipients_label': 'Destinataires',
      'payment_amount_label': 'Montant',
      'payment_amount_hint': 'Ex. 10,00',
      'payment_note_label': 'Description',
      'payment_note_hint': 'Ex. Cotisation mensuelle / Terrain / Maillots...',
      'payment_due_date_label': 'Date limite (optionnel)',
      'payment_pick_date': 'Choisir la date',

      'payment_send_request': 'Envoyer',
      'payment_creating': 'Envoi...',
      'payment_request_created_success': 'Demande créée avec succès !',
      'payment_invalid_amount_error': 'Entrez un montant valide',
      'payment_missing_fields_error': 'Veuillez remplir tous les champs requis',
      'payment_no_recipients_error': 'Sélectionnez au moins une personne',

      "home_no_payments": "Aucune demande de paiement.",
      "payments_for_you_title": "Demandes pour vous",
      "payments_created_by_you_title": "Créées par vous",
      "payment_default_title": "Demande de paiement",
      "payment_open_details_placeholder": "Détails du paiement bientôt disponibles",

      "payment_status_pending": "En attente",
      "payment_status_paid": "Payé",
      "payment_status_partial": "Partiel",
      "payment_targets_paid_hint": "payés",

      "label_admin": "Admin",
      "payment_admin_only_error": "Seul l’administrateur peut créer des demandes de paiement.",

      "payment_delete_title": "Supprimer la demande",
      "payment_delete_confirm": "Voulez-vous vraiment supprimer cette demande de paiement pour le groupe \"{groupName}\" ?",
      "payment_deleted_success": "Demande de paiement supprimée.",
      "button_delete": "Supprimer",
    },

    // 🇩🇪 GERMAN
    'de': {
      'app_title': 'Grouply - Team Manager',
      'create_post_title': 'Beitrag erstellen',
      'label_publish_in': 'Veröffentlichen in:',
      'label_post_title': 'Beitragstitel',
      'label_post_description': 'Beschreibung',
      'btn_add_media': 'Foto/Video',
      'btn_add_attachment': 'Anhang',
      'btn_publish': 'Veröffentlichen',
      'post_created_success': 'Beitrag erfolgreich erstellt!',
      'error_no_group_selected': 'Keine Gruppe ausgewählt',
      // ... (Resto delle chiavi DE) ...
      'home_tab_events': 'Termine',
      'home_tab_posts': 'Beiträge',
      'home_tab_polls': 'Umfragen',
      'home_no_posts': 'Keine Beiträge',
      'home_no_polls': 'Keine aktiven Umfragen',
      'label_location': 'Ort',
      'label_meeting_point': 'Treffpunkt',
      'label_meeting_time': 'Treffpunktzeit',
      'label_match_location': 'Spielort',
      'create_recurring_event_title': 'Wiederkehrenden Termin erstellen',
      'label_event_name': 'Terminname',
      'default_event_training': 'Training',
      'label_recurrence': 'Wiederholung',
      'recurrence_daily': 'Täglich',
      'recurrence_weekly': 'Wöchentlich',
      'recurrence_monthly': 'Monatlich',
      'recurrence_info': 'Termine werden für die nächsten 3 Monate erstellt.',
      'label_today': 'Heute',
      'label_tomorrow': 'Morgen',
      'home_upcoming_events': 'Anstehende Termine',
      'home_no_events': 'Keine Termine geplant',
      'home_no_groups': 'Du bist in keiner Gruppe. Tritt einer bei!',
      'event_group_label': 'Gruppe: {group}',
      'login_title': 'Willkommen zurück!',
      'login_subtitle': 'Anmelden um fortzufahren',
      'email_label': 'E-Mail',
      'password_label': 'Passwort',
      'forgot_password': 'Passwort vergessen?',
      'login_button': 'Anmelden',
      'login_with_google': 'Mit Google anmelden',
      'no_account': 'Kein Konto?',
      'go_to_register': 'Registrieren',
      'or_label': 'oder',
      'google_signin_loading': 'Anmeldung mit Google...',
      'google_signup_loading': 'Registrierung mit Google...',
      'register_title': 'Konto erstellen',
      'register_subtitle': 'Registrieren um zu beginnen',
      'confirm_password_label': 'Passwort bestätigen',
      'register_button': 'Registrieren',
      'register_with_google': 'Mit Google registrieren',
      'registration_success': 'Registrierung erfolgreich.\nWillkommen bei Grouply',
      'go_to_login_button': 'Zur Login-Seite',
      'have_account': 'Bereits ein Konto?',
      'home_title': 'Startseite',
      'home_message': 'Willkommen bei Grouply Home',
      'close_button': 'Schließen',
      'home_groups_dialog_title': 'Gruppen',
      'home_groups_create': 'Neue Gruppe erstellen',
      'home_groups_join': 'Gruppe beitreten',
      'home_groups_create_snackbar': 'Funktion "Gruppe erstellen" in Entwicklung',
      'home_groups_join_snackbar': 'Funktion "Code eingeben" in Entwicklung',
      'dialog_create_group_title': 'Neue Gruppe erstellen',
      'label_team_name': 'Teamname (z.B. Bayern München)',
      'label_team_sport': 'Sportart (z.B. Fußball)',
      'button_cancel': 'Abbrechen',
      'button_create': 'Erstellen',
      'snack_group_created': 'Gruppe erstellt! Code: {code}',
      'snack_create_error': 'Fehler beim Erstellen: {error}',
      'dialog_join_group_title': 'Gruppe beitreten',
      'label_insert_code': 'Code eingeben (6 Zeichen)',
      'button_join': 'Beitreten',
      'error_code_not_found': 'Keine Gruppe mit diesem Code gefunden',
      'error_already_member': 'Du bist bereits Mitglied!',
      'snack_join_success': 'Du bist der Gruppe {groupName} beigetreten!',
      'snack_join_error': 'Fehler beim Beitreten: {error}',
      'group_placeholder': 'Gruppenbereich',
      'group_empty_title': 'Keine Gruppen',
      'group_empty_subtitle': 'Du bist noch in keinem Team.\nErstelle eine Gruppe oder tritt einer bei!',
      'group_members_count': '{count} Mitglieder',
      'tab_board': 'Pinnwand',
      'tab_members': 'Mitglieder',
      'tab_info': 'Info',
      'info_invite_code_label': 'Einladungscode',
      'info_copy_code': 'Code kopieren',
      'info_code_copied': 'Code in die Zwischenablage kopiert',
      'info_sport': 'Sportart',
      'board_empty': 'Keine Beiträge auf der Pinnwand',
      'members_list_title': 'Teammitglieder',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Gruppe verlassen',
      'dialog_leave_title': 'Gruppe verlassen?',
      'dialog_leave_content': 'Du wirst diese Gruppe nicht mehr in deiner Liste sehen.',
      'leave_success': 'Du hast die Gruppe verlassen.',
      'leave_error': 'Fehler beim Verlassen: {error}',
      'fab_option_event': 'Termin',
      'fab_option_post': 'Beitrag',
      'fab_option_post_sub': 'Teile Infos, Fotos und Dateien',
      'fab_option_poll': 'Umfrage',
      'fab_option_poll_sub': 'Frage Mitglieder nach ihrer Meinung',
      'fab_option_payment': 'Zahlungsaufforderung',
      'fab_option_payment_sub': 'Sammle Beiträge von Mitgliedern',
      'event_select_type_title': 'Typ wählen',
      'event_type_single': 'Termin',
      'event_type_single_sub': 'Lade Leute zu Spielen oder Turnieren ein',
      'event_type_recurring': 'Wiederkehrender Termin',
      'event_type_recurring_sub': 'Lade Leute zum Training ein',
      'create_event_title': 'Termin erstellen',
      'label_match_type': 'Spielart',
      'match_type_home': 'Heimspiel',
      'match_type_away': 'Auswärtsspiel',
      'match_type_tournament': 'Turnier',
      'match_type_friendly': 'Freundschaftsspiel',
      'label_home_team': 'Heimmannschaft',
      'label_away_team': 'Auswärtsmannschaft',
      'label_start_time': 'Startzeit',
      'label_date': 'Datum',
      'map_select_placeholder': 'Auf Karte wählen',
      'label_tournament_teams': 'Teilnehmende Teams',
      'btn_add_team': 'Team hinzufügen',
      'hint_team_n': 'Team {number}',
      'event_created_success': 'Termin erfolgreich erstellt!',
      'error_missing_fields': 'Bitte alle Pflichtfelder ausfüllen',
      'event_details_title': 'Termindetails',
      'status_title': 'Dein Status',
      'btn_accept': 'Zusagen',
      'btn_decline': 'Absagen',
      'status_going': 'Dabei',
      'status_not_going': 'Nicht dabei',
      'status_pending': 'Ausstehend',
      'participants_list': 'Teilnehmer ({count})',
      'tab_details': 'Details',
      'tab_participants': 'Teilnehmer',
      'delete_event_title': 'Termin löschen',
      'delete_event_confirm': 'Möchtest du diesen Termin wirklich löschen? Dies kann nicht rückgängig gemacht werden.',
      'event_deleted': 'Termin erfolgreich gelöscht.',
      'error_deleting_event': 'Fehler beim Löschen: {error}',
      'messages_placeholder': 'Nachrichtenbereich\n(hier siehst du deine Chats)',
      'payments_placeholder': 'Zahlungsbereich\n(Abos, Gebühren verwalten)',
      'profile_title': 'Profilverwaltung',
      'profile_change_photo': 'Profilbild ändern',
      'label_name': 'Name',
      'label_day': 'Tag',
      'label_month': 'Monat',
      'label_year': 'Jahr',
      'label_gender': 'Geschlecht',
      'label_sport': 'Sportart',
      'label_role': 'Spielerrolle',
      'button_save': 'Speichern',
      'toast_save_success': 'Profil gespeichert',
      'toast_login_required': 'Bitte anmelden zum Speichern',
      'toast_photo_error': 'Fehler beim Hochladen des Fotos',
      'settings_title': 'Einstellungen',
      'settings_section_theme': 'Design',
      'settings_change_theme': 'Design ändern',
      'settings_theme_dark_active': 'Dunkles Design aktiv',
      'settings_theme_light_active': 'Helles Design aktiv',
      'settings_section_account': 'Konto',
      'settings_section_profile': 'Profil',
      'settings_profile_manage_title': 'Profil verwalten',
      'settings_profile_manage_subtitle': 'Name, Geburtsdatum, Rolle bearbeiten...',
      'settings_section_language': 'Sprache',
      'settings_language_app': 'App-Sprache',
      'settings_language_select_title': 'Sprache wählen',
      'settings_account_email_subtitle': 'Verknüpfte E-Mail',
      'language_italian': 'Italienisch',
      'language_english': 'Englisch',
      'language_spanish': 'Spanisch',
      'language_french': 'Französisch',
      'language_german': 'Deutsch',
      'language_portuguese': 'Portugiesisch',
      'language_changed_snackbar': 'Sprache geändert auf {language}',
      'logout_button': 'Abmelden',
      'validation_insert_email': 'Gib deine E-Mail ein',
      'validation_email_invalid': 'Ungültige E-Mail',
      'validation_insert_password': 'Gib dein Passwort ein',
      'validation_insert_password_register': 'Wähle ein Passwort',
      'validation_min_6_chars': 'Mindestens 6 Zeichen',
      'validation_confirm_password': 'Passwort bestätigen',
      'validation_passwords_not_match': 'Passwörter stimmen nicht überein',
      'validation_code_length': 'Der Code muss 6 Zeichen lang sein',
      'error_login': 'Fehler bei der Anmeldung',
      'error_register': 'Fehler bei der Registrierung',
      'error_unexpected_login': 'Unerwarteter Fehler bei der Anmeldung',
      'error_unexpected_register': 'Unerwarteter Fehler bei der Registrierung',
      'error_user_not_found': 'Benutzer nicht gefunden',
      'error_wrong_password': 'Falsches Passwort',
      'error_invalid_email': 'Ungültige E-Mail',
      'error_email_in_use': 'Diese E-Mail ist bereits registriert',
      'error_weak_password': 'Passwort ist zu schwach',

      //Messaggi
      'messages_empty_title': 'Keine Chats',
      'messages_empty_subtitle': 'Tritt einer Gruppe bei, um zu chatten.',
      'chat_empty': 'Noch keine Nachrichten. Schreib die erste!',
      'chat_hint': 'Nachricht schreiben...',
      'chat_send_error': 'Senden fehlgeschlagen: {error}',
      'chat_error_generic': 'Fehler',
      'chat_no_messages_yet': 'Noch keine Nachrichten',
      'chat_message_deleted_or_empty': '(leere Nachricht)',

      //Sondaggi
      'create_poll_title': 'Umfrage erstellen',
      'poll_question_label': 'Frage',
      'poll_question_hint': 'Z.B. Wer kommt zum Training?',
      'poll_option_label': 'Option {number}',
      'poll_add_option': 'Option hinzufügen',
      'poll_remove_option': 'Entfernen',
      'poll_publish': 'Umfrage veröffentlichen',
      'poll_creating': 'Umfrage wird erstellt...',
      'poll_min_options_error': 'Mindestens 2 Optionen eingeben',
      'poll_missing_fields_error': 'Frage und Optionen ausfüllen',
      'poll_created_success': 'Umfrage erfolgreich erstellt!',
      'poll_allow_multiple': 'Mehrfachauswahl erlauben',
      'poll_vote_saved': 'Stimme gespeichert',
      'poll_total_votes': '{count} Stimmen',
      'poll_multiple_hint': 'du kannst mehrere Optionen wählen',
      "poll_delete_title": "Umfrage löschen",
      "poll_delete_confirm": "Möchtest du diese Umfrage aus der Gruppe {groupName} wirklich löschen?",
      "poll_deleted_success": "Umfrage gelöscht.",

      //Pagamenti
      'payment_select_people_title': 'Mitglieder auswählen',
      'payment_select_people_subtitle': 'Wähle aus, wer die Zahlungsaufforderung erhalten soll',
      'payment_select_all': 'Alle auswählen',
      'payment_clear_all': 'Auswahl löschen',
      'payment_next': 'Weiter',

      'payment_create_title': 'Zahlungsaufforderung',
      'payment_recipients_label': 'Empfänger',
      'payment_amount_label': 'Betrag',
      'payment_amount_hint': 'z.B. 10,00',
      'payment_note_label': 'Beschreibung',
      'payment_note_hint': 'z.B. Monatsbeitrag / Platz / Trikots...',
      'payment_due_date_label': 'Fälligkeitsdatum (optional)',
      'payment_pick_date': 'Datum wählen',

      'payment_send_request': 'Senden',
      'payment_creating': 'Senden...',
      'payment_request_created_success': 'Anfrage erfolgreich erstellt!',
      'payment_invalid_amount_error': 'Bitte einen gültigen Betrag eingeben',
      'payment_missing_fields_error': 'Bitte alle Pflichtfelder ausfüllen',
      'payment_no_recipients_error': 'Wähle mindestens eine Person aus',

      "home_no_payments": "Keine Zahlungsanforderungen.",
      "payments_for_you_title": "Anfragen für dich",
      "payments_created_by_you_title": "Von dir erstellt",
      "payment_default_title": "Zahlungsanforderung",
      "payment_open_details_placeholder": "Zahlungsdetails folgen in Kürze",

      "payment_status_pending": "Ausstehend",
      "payment_status_paid": "Bezahlt",
      "payment_status_partial": "Teilweise",
      "payment_targets_paid_hint": "bezahlt",

      "label_admin": "Admin",
      "payment_admin_only_error": "Nur der Admin kann Zahlungsanforderungen erstellen.",

      "payment_delete_title": "Anfrage löschen",
      "payment_delete_confirm": "Möchtest du diese Zahlungsanforderung für die Gruppe \"{groupName}\" wirklich löschen?",
      "payment_deleted_success": "Zahlungsanforderung gelöscht.",
      "button_delete": "Löschen",
    },

    // 🇧🇷 PORTUGUESE
    'pt': {
      'app_title': 'Grouply - Gestão de Equipes',
      'create_post_title': 'Criar publicação',
      'label_publish_in': 'Publicar em:',
      'label_post_title': 'Título da publicação',
      'label_post_description': 'Descrição',
      'btn_add_media': 'Foto/Vídeo',
      'btn_add_attachment': 'Anexo',
      'btn_publish': 'Publicar',
      'post_created_success': 'Publicação criada com sucesso!',
      'error_no_group_selected': 'Nenhum grupo selecionado',
      // ... (Resto delle chiavi PT) ...
      'home_tab_events': 'Eventos',
      'home_tab_posts': 'Publicações',
      'home_tab_polls': 'Enquetes',
      'home_no_posts': 'Nenhuma publicação',
      'home_no_polls': 'Nenhuma enquete ativa',
      'label_location': 'Local',
      'label_meeting_point': 'Ponto de encontro',
      'label_meeting_time': 'Horário de encontro',
      'label_match_location': 'Local da partida',
      'create_recurring_event_title': 'Criar evento recorrente',
      'label_event_name': 'Nome do evento',
      'default_event_training': 'Treino',
      'label_recurrence': 'Repetição',
      'recurrence_daily': 'Diariamente',
      'recurrence_weekly': 'Semanalmente',
      'recurrence_monthly': 'Mensalmente',
      'recurrence_info': 'Eventos serão gerados para os próximos 3 meses.',
      'label_today': 'Hoje',
      'label_tomorrow': 'Amanhã',
      'home_upcoming_events': 'Próximos Eventos',
      'home_no_events': 'Nenhum evento agendado',
      'home_no_groups': 'Você não participa de nenhum grupo. Entre em um!',
      'event_group_label': 'Grupo: {group}',
      'login_title': 'Bem-vindo de volta!',
      'login_subtitle': 'Faça login para continuar',
      'email_label': 'E-mail',
      'password_label': 'Senha',
      'forgot_password': 'Esqueceu a senha?',
      'login_button': 'Entrar',
      'login_with_google': 'Entrar com Google',
      'no_account': 'Não tem conta?',
      'go_to_register': 'Cadastrar',
      'or_label': 'ou',
      'google_signin_loading': 'Entrando com Google...',
      'google_signup_loading': 'Cadastrando com Google...',
      'register_title': 'Criar conta',
      'register_subtitle': 'Cadastre-se para começar',
      'confirm_password_label': 'Confirmar senha',
      'register_button': 'Cadastrar',
      'register_with_google': 'Cadastrar com Google',
      'registration_success': 'Cadastro realizado com sucesso.\nBem-vindo ao Grouply',
      'go_to_login_button': 'Ir para login',
      'have_account': 'Já tem conta?',
      'home_title': 'Início',
      'home_message': 'Bem-vindo ao Grouply Home',
      'close_button': 'Fechar',
      'home_groups_dialog_title': 'Grupos',
      'home_groups_create': 'Criar novo grupo',
      'home_groups_join': 'Entrar em grupo existente',
      'home_groups_create_snackbar': 'Função "Criar grupo" em desenvolvimento',
      'home_groups_join_snackbar': 'Função "Digitar código" em desenvolvimento',
      'dialog_create_group_title': 'Criar Novo Grupo',
      'label_team_name': 'Nome do Time (ex. Flamengo)',
      'label_team_sport': 'Esporte (ex. Futebol)',
      'button_cancel': 'Cancelar',
      'button_create': 'Criar',
      'snack_group_created': 'Grupo criado! Código: {code}',
      'snack_create_error': 'Erro ao criar grupo: {error}',
      'dialog_join_group_title': 'Entrar em um Grupo',
      'label_insert_code': 'Digite o código (6 letras)',
      'button_join': 'Entrar',
      'error_code_not_found': 'Nenhum grupo encontrado com este código',
      'error_already_member': 'Você já é membro deste grupo!',
      'snack_join_success': 'Você entrou no grupo {groupName}!',
      'snack_join_error': 'Erro ao entrar: {error}',
      'group_placeholder': 'Seção de Grupos',
      'group_empty_title': 'Sem grupos',
      'group_empty_subtitle': 'Você não participa de nenhum time.\nCrie um grupo ou entre em um existente!',
      'group_members_count': '{count} membros',
      'tab_board': 'Mural',
      'tab_members': 'Membros',
      'tab_info': 'Info',
      'info_invite_code_label': 'Código de Convite',
      'info_copy_code': 'Copiar código',
      'info_code_copied': 'Código copiado para a área de transferência',
      'info_sport': 'Esporte',
      'board_empty': 'Nenhum aviso no mural',
      'members_list_title': 'Membros da equipe',
      'member_admin_badge': 'Admin',
      'info_leave_group': 'Sair do grupo',
      'dialog_leave_title': 'Sair do grupo?',
      'dialog_leave_content': 'Você não verá mais este grupo na sua lista.',
      'leave_success': 'Você saiu do grupo.',
      'leave_error': 'Erro ao sair: {error}',
      'fab_option_event': 'Evento',
      'fab_option_post': 'Postagem',
      'fab_option_post_sub': 'Compartilhe informações, fotos e arquivos',
      'fab_option_poll': 'Enquete',
      'fab_option_poll_sub': 'Peça a opinião dos membros',
      'fab_option_payment': 'Solicitação de pagamento',
      'fab_option_payment_sub': 'Recolha taxas dos membros',
      'event_select_type_title': 'Selecionar tipo',
      'event_type_single': 'Evento',
      'event_type_single_sub': 'Convide para partidas ou torneios',
      'event_type_recurring': 'Evento recorrente',
      'event_type_recurring_sub': 'Convide para treinos',
      'create_event_title': 'Criar evento',
      'label_match_type': 'Tipo de partida',
      'match_type_home': 'Jogo em casa',
      'match_type_away': 'Jogo fora',
      'match_type_tournament': 'Torneio',
      'match_type_friendly': 'Amistoso',
      'label_home_team': 'Time da casa',
      'label_away_team': 'Time visitante',
      'label_start_time': 'Hora de início',
      'label_date': 'Data',
      'map_select_placeholder': 'Selecionar no mapa',
      'label_tournament_teams': 'Times participantes',
      'btn_add_team': 'Adicionar time',
      'hint_team_n': 'Time {number}',
      'event_created_success': 'Evento criado com sucesso!',
      'error_missing_fields': 'Por favor, preencha todos os campos obrigatórios',
      'event_details_title': 'Detalhes do Evento',
      'status_title': 'Sua presença',
      'btn_accept': 'Vou',
      'btn_decline': 'Não vou',
      'status_going': 'Vai',
      'status_not_going': 'Não vai',
      'status_pending': 'Pendente',
      'participants_list': 'Participantes ({count})',
      'tab_details': 'Detalhes',
      'tab_participants': 'Participantes',
      'delete_event_title': 'Excluir evento',
      'delete_event_confirm': 'Tem certeza de que deseja excluir este evento? Esta ação não pode ser desfeita.',
      'event_deleted': 'Evento excluído com sucesso.',
      'error_deleting_event': 'Erro ao excluir: {error}',
      'messages_placeholder': 'Seção de Mensagens\n(veja seus chats aqui)',
      'payments_placeholder': 'Seção de Pagamentos\n(gerencie assinaturas, taxas, etc.)',
      'profile_title': 'Gerenciar Perfil',
      'profile_change_photo': 'Alterar foto de perfil',
      'label_name': 'Nome',
      'label_day': 'Dia',
      'label_month': 'Mês',
      'label_year': 'Ano',
      'label_gender': 'Gênero',
      'label_sport': 'Esporte praticado',
      'label_role': 'Função do jogador',
      'button_save': 'Salvar',
      'toast_save_success': 'Dados salvos',
      'toast_login_required': 'Faça login para salvar',
      'toast_photo_error': 'Erro ao carregar foto',
      'settings_title': 'Configurações',
      'settings_section_theme': 'Tema',
      'settings_change_theme': 'Alterar tema',
      'settings_theme_dark_active': 'Tema escuro ativo',
      'settings_theme_light_active': 'Tema claro ativo',
      'settings_section_account': 'Conta',
      'settings_section_profile': 'Perfil',
      'settings_profile_manage_title': 'Gerenciar perfil',
      'settings_profile_manage_subtitle': 'Editar nome, nascimento, função...',
      'settings_section_language': 'Idioma',
      'settings_language_app': 'Idioma do app',
      'settings_language_select_title': 'Selecionar idioma',
      'settings_account_email_subtitle': 'E-mail vinculado à conta',
      'language_italian': 'Italiano',
      'language_english': 'Inglês',
      'language_spanish': 'Espanhol',
      'language_french': 'Francês',
      'language_german': 'Alemão',
      'language_portuguese': 'Português',
      'language_changed_snackbar': 'Idioma definido para {language}',
      'logout_button': 'Sair',
      'validation_insert_email': 'Digite seu e-mail',
      'validation_email_invalid': 'E-mail inválido',
      'validation_insert_password': 'Digite sua senha',
      'validation_insert_password_register': 'Crie uma senha',
      'validation_min_6_chars': 'Mínimo 6 caracteres',
      'validation_confirm_password': 'Confirmar senha',
      'validation_passwords_not_match': 'As senhas não coincidem',
      'validation_code_length': 'O código deve ter 6 caracteres',
      'error_login': 'Erro no login',
      'error_register': 'Erro no cadastro',
      'error_unexpected_login': 'Erro inesperado no login',
      'error_unexpected_register': 'Erro inesperado no cadastro',
      'error_user_not_found': 'Usuário não encontrado',
      'error_wrong_password': 'Senha incorreta',
      'error_invalid_email': 'E-mail inválido',
      'error_email_in_use': 'Este e-mail já está em uso',
      'error_weak_password': 'Senha muito fraca',

      //Messaggi
      'messages_empty_title': 'Sem chats',
      'messages_empty_subtitle': 'Entre em um grupo para começar a conversar.',
      'chat_empty': 'Ainda não há mensagens. Escreva a primeira!',
      'chat_hint': 'Digite uma mensagem...',
      'chat_send_error': 'Erro ao enviar: {error}',
      'chat_error_generic': 'Erro',
      'chat_no_messages_yet': 'Ainda não há mensagens',
      'chat_message_deleted_or_empty': '(mensagem vazia)',

      //Sondaggi
      'create_poll_title': 'Criar enquete',
      'poll_question_label': 'Pergunta',
      'poll_question_hint': 'Ex. Quem vai ao treino?',
      'poll_option_label': 'Opção {number}',
      'poll_add_option': 'Adicionar opção',
      'poll_remove_option': 'Remover',
      'poll_publish': 'Publicar enquete',
      'poll_creating': 'Criando enquete...',
      'poll_min_options_error': 'Insira pelo menos 2 opções',
      'poll_missing_fields_error': 'Preencha a pergunta e as opções',
      'poll_created_success': 'Enquete criada com sucesso!',
      'poll_allow_multiple': 'Permitir múltiplas seleções',
      'poll_vote_saved': 'Voto salvo',
      'poll_total_votes': '{count} votos',
      'poll_multiple_hint': 'você pode selecionar várias opções',
      "poll_delete_title": "Eliminar enquete",
      "poll_delete_confirm": "Tem certeza de que deseja eliminar esta enquete do grupo {groupName}?",
      "poll_deleted_success": "Enquete eliminada.",

      //Pagamenti
      'payment_select_people_title': 'Selecionar membros',
      'payment_select_people_subtitle': 'Escolha quem vai receber a solicitação de pagamento',
      'payment_select_all': 'Selecionar todos',
      'payment_clear_all': 'Limpar',
      'payment_next': 'Avançar',

      'payment_create_title': 'Solicitação de pagamento',
      'payment_recipients_label': 'Destinatários',
      'payment_amount_label': 'Valor',
      'payment_amount_hint': 'Ex: 10,00',
      'payment_note_label': 'Descrição',
      'payment_note_hint': 'Ex: Mensalidade / Campo / Uniformes...',
      'payment_due_date_label': 'Vencimento (opcional)',
      'payment_pick_date': 'Escolher data',

      'payment_send_request': 'Enviar solicitação',
      'payment_creating': 'Enviando...',
      'payment_request_created_success': 'Solicitação criada com sucesso!',
      'payment_invalid_amount_error': 'Informe um valor válido',
      'payment_missing_fields_error': 'Preencha todos os campos obrigatórios',
      'payment_no_recipients_error': 'Selecione pelo menos uma pessoa',

      "home_no_payments": "Nenhum pedido de pagamento.",
      "payments_for_you_title": "Pedidos para você",
      "payments_created_by_you_title": "Criados por você",
      "payment_default_title": "Pedido de pagamento",
      "payment_open_details_placeholder": "Detalhes do pagamento em breve",

      "payment_status_pending": "Pendente",
      "payment_status_paid": "Pago",
      "payment_status_partial": "Parcial",
      "payment_targets_paid_hint": "pagos",

      "label_admin": "Admin",
      "payment_admin_only_error": "Apenas o administrador pode criar solicitações de pagamento.",

      "payment_delete_title": "Eliminar pedido",
      "payment_delete_confirm": "Tens a certeza de que queres eliminar este pedido de pagamento do grupo \"{groupName}\"?",
      "payment_deleted_success": "Pedido de pagamento eliminado.",
      "button_delete": "Eliminar",
    },
  };

  String t(String key, {Map<String, String>? params}) {
    final langCode = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';

    String value =
        _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;

    if (params != null) {
      params.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }

    return value;
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      ['it', 'en', 'es', 'fr', 'de', 'pt'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}